### ISSUE TITLE
Test in `test_nfs_feature_enable_for_ODF_clusters.py` Erroring on tierdown when looking for `openshift-dev.pem` file.

### ISSUE THREAD

**Issue by abdulkandathil** [red-hat-storage/ocs-ci#10710]
Test : tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py

The test is passing but erroring during tierdown as it is looking for `openshift-dev.pem` file.

May I know where to get this file from? Maybe looks like it is not skipping if the file is not found?

```

self = <[AttributeError("'NoneType' object has no attribute 'key_size'") raised in repr()] RSAKey object at 0x7f6dfcf14430>
tag = 'RSA', filename = '/home/automation/.ssh/openshift-dev.pem'
password = None

    def _read_private_key_file(self, tag, filename, password=None):
        """
        Read an SSH2-format private key file, looking for a string of the type
        ``"BEGIN xxx PRIVATE KEY"`` for some ``xxx``, base64-decode the text we
        find, and return it as a string.  If the private key is encrypted and
        ``password`` is not ``None``, the given password will be used to
        decrypt the key (otherwise `.PasswordRequiredException` is thrown).

        :param str tag: ``"RSA"`` or ``"DSA"``, the tag used to mark the
            data block.
        :param str filename: name of the file to read.
        :param str password:
            an optional password to use to decrypt the key file, if it's
            encrypted.
        :return: the `bytes` that make up the private key.

        :raises: ``IOError`` -- if there was an error reading the file.
        :raises: `.PasswordRequiredException` -- if the private key file is
            encrypted, and ``password`` is ``None``.
        :raises: `.SSHException` -- if the key file is invalid.
        """
>       with open(filename, "r") as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/automation/.ssh/openshift-dev.pem'

venv/lib/python3.10/site-packages/paramiko/pkey.py:494: FileNotFoundError
---------------------------- live log sessionfinish ----------------------------
```

Full test log : 
https://drive.google.com/file/d/1Tj5yqd-LsmUBRBRMEIM_aJBWEFh0spDj/view?usp=sharing

**Comment by vavuthu** [comment]
for tests/functional/nfs_feature/test_nfs_feature_enable_for_ODF_clusters.py, we need to pass the below NFS client details. if nfs_client_private_key doesn't exist, ocs-ci will take the ssh_key_private from default-config.yaml

```
But if someone will run locally, they will need to create custom config file and provide that via
        --ocsci-conf in order to run the external nfs consume tests. Example:
        ENV_DATA:
            nfs_client_ip: "10.xx.xxx.xx"
            nfs_client_user: "root"
            nfs_client_private_key: "<path to ssh private key>"
```

**Comment by abdulkandathil** [comment]
Thank you.. It worked, but only with nfs client host public key.. with private key it was throwing below error.

```
------------------------------ live log teardown -------------------------------
13:51:17 - MainThread - test_nfs_feature_enable_for_ODF_clusters - INFO  - Connecting to nfs client test VM
13:51:17 - Thread-10 - paramiko.transport - INFO  - Connected (version 2.0, client OpenSSH_8.0)
13:51:17 - Thread-10 - paramiko.transport - INFO  - Authentication (publickey) failed.
13:51:17 - Thread-10 - paramiko.transport - ERROR  - Unknown exception: q must be exactly 160, 224, or 256 bits long
13:51:17 - Thread-10 - paramiko.transport - ERROR  - Traceback (most recent call last):
13:51:17 - Thread-10 - paramiko.transport - ERROR  -   File "/home/automation/ocs-ci-other/venv/lib/python3.10/site-packages/paramiko/transport.py", line 2220, in run
13:51:17 - Thread-10 - paramiko.transport - ERROR  -     handler(m)
13:51:17 - Thread-10 - paramiko.transport - ERROR  -   File "/home/automation/ocs-ci-other/venv/lib/python3.10/site-packages/paramiko/auth_handler.py", line 404, in _parse_service_accept
13:51:17 - Thread-10 - paramiko.transport - ERROR  -     sig = self.private_key.sign_ssh_data(blob, algorithm)
13:51:17 - Thread-10 - paramiko.transport - ERROR  -   File "/home/automation/ocs-ci-other/venv/lib/python3.10/site-packages/paramiko/dsskey.py", line 112, in sign_ssh_data
13:51:17 - Thread-10 - paramiko.transport - ERROR  -     key = dsa.DSAPrivateNumbers(
13:51:17 - Thread-10 - paramiko.transport - ERROR  - ValueError: q must be exactly 160, 224, or 256 bits long
13:51:17 - Thread-10 - paramiko.transport - ERROR  - 
```
