### ISSUE TITLE
When trying to rebuild a pull request Jenkins job it failed with the error: "groovy.lang.MissingPropertyException: No such field found: field org.jenkinsci.plugins.workflow.cps.replay.ReplayCause userId"

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#10928]
See, for example, this pull request build: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-trigger-test-pr/7854/ and the associated deploy Jenkins job build: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/44325/console. 
In the build above, you can see the following error:

> 2024-11-25 17:00:49  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: da642094-ce2b-4814-ac6b-c6395fdf4c47
2024-11-25 17:00:49  groovy.lang.MissingPropertyException: No such field found: field org.jenkinsci.plugins.workflow.cps.replay.ReplayCause userId
2024-11-25 17:00:49  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.unclassifiedField(SandboxInterceptor.java:402)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:386)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:375)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:379)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker$checkedGetProperty$0.callStatic(Unknown Source)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:233)
2024-11-25 17:00:49  	at getBuildUser.call(getBuildUser.groovy:11)
2024-11-25 17:00:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-11-25 17:00:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-11-25 17:00:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-11-25 17:00:49  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-11-25 17:00:49  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
2024-11-25 17:00:49  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
2024-11-25 17:00:49  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
2024-11-25 17:00:49  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:180)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:163)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:178)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:182)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker$checkedCall$1.callStatic(Unknown Source)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
2024-11-25 17:00:49  	at getBuildUser.call(getBuildUser.groovy)
2024-11-25 17:00:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-11-25 17:00:49  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-11-25 17:00:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-11-25 17:00:49  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-11-25 17:00:49  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
2024-11-25 17:00:49  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
2024-11-25 17:00:49  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
2024-11-25 17:00:49  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
2024-11-25 17:00:49  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:822)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:116)
2024-11-25 17:00:49  	at jdk.internal.reflect.GeneratedMethodAccessor256747.invoke(Unknown Source)
2024-11-25 17:00:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-11-25 17:00:49  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-11-25 17:00:49  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
2024-11-25 17:00:49  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
2024-11-25 17:00:49  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
2024-11-25 17:00:49  	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:180)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:163)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:178)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:182)
2024-11-25 17:00:49  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:152)
2024-11-25 17:00:49  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.LoggingInvoker.methodCall(LoggingInvoker.java:105)
2024-11-25 17:00:49  	at deployJobInit.call(deployJobInit.groovy:29)
2024-11-25 17:00:49  	at ___cps.transform___(Native Method)
2024-11-25 17:00:49  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:90)
2024-11-25 17:00:49  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:116)
2024-11-25 17:00:49  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixName(FunctionCallBlock.java:80)
2024-11-25 17:00:49  	at jdk.internal.reflect.GeneratedMethodAccessor741.invoke(Unknown Source)
2024-11-25 17:00:49  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-11-25 17:00:49  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-11-25 17:00:49  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
2024-11-25 17:00:49  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
2024-11-25 17:00:49  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
2024-11-25 17:00:49  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:147)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:17)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:49)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:180)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:423)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:331)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:295)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$4(CpsVmExecutorService.java:136)
2024-11-25 17:00:49  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2024-11-25 17:00:49  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
2024-11-25 17:00:49  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
2024-11-25 17:00:49  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
2024-11-25 17:00:49  	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
2024-11-25 17:00:49  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2024-11-25 17:00:49  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2024-11-25 17:00:49  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024-11-25 17:00:49  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:53)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:50)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
2024-11-25 17:00:49  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
2024-11-25 17:00:49  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0(CpsVmExecutorService.java:50)
2024-11-25 17:00:49  	at java.base/java.lang.Thread.run(Unknown Source)
2024-11-25 17:00:49  Finished: FAILURE

**Comment by yitzhak12** [comment]
The issue is no longer relevant.
