### ISSUE TITLE
pkg_resources.ContextualVersionConflict: kubernetes 11.0.0

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#1644]
Looks like we're pulling `kubernetes` version `11.0.0` while `openshift` requires `~=10.0.1`

```
+ run-ci tests/ecosystem/ -m deployment --ocs-version 4.3 --ocsci-conf=**** '--ocsci-conf=~/current-cluster-dir/ocsci_conf.yaml' --ocsci-conf conf/ocsci/ocp-4.3-config.yaml --ocsci-conf=conf/deployment/vsphere/upi_1az_rhel_vmfs_3m_3w.yaml --ocsci-conf=conf/ocsci/production_device_size.yaml --cluster-name jnk-vu1rv33-t4a --cluster-path /home/jenkins/current-cluster-dir/openshift-cluster-dir --junit-xml /home/jenkins/current-cluster-dir/logs/destroy_results.xml -o junit_suite_name=jnk-vu1rv33-t4a --html=/home/jenkins/current-cluster-dir/logs/destroy_report.html --self-contained-html --teardown
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (kubernetes 11.0.0 (/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages), Requirement.parse('kubernetes~=10.0.1'), {'openshift'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/bin/run-ci", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3254, in <module>
    @_call_aside
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3238, in _call_aside
    f(*args, **kwargs)
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3267, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (kubernetes 11.0.0 (/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages), Requirement.parse('kubernetes~=10.0.1'), {'openshift'})
+ run_ci_rc=1
```

**Comment by clacroix12** [comment]
When attempting to `pip install -r requirements.txt` in a fresh venv I get this:
```
ERROR: openshift 0.10.2 has requirement kubernetes~=10.0.1, but you'll have kubernetes 11.0.0 which is incompatible.```
