### ISSUE TITLE
4.4 not supported yet?

### ISSUE THREAD

**Issue by zmc** [red-hat-storage/ocs-ci#1711]
We tried to test a 4.4 build:
```
Traceback (most recent call last):
  File "/home/jenkins-build/workspace/ocs-ci/venv/bin/run-ci", line 11, in <module>
    load_entry_point('ocs-ci', 'console_scripts', 'run-ci')()
  File "/home/jenkins-build/workspace/ocs-ci/ocs_ci/framework/main.py", line 94, in main
    init_ocsci_conf(arguments)
  File "/home/jenkins-build/workspace/ocs-ci/ocs_ci/framework/main.py", line 81, in init_ocsci_conf
    load_config([version_config_file])
  File "/home/jenkins-build/workspace/ocs-ci/ocs_ci/framework/main.py", line 50, in load_config
    os.path.abspath(os.path.expanduser(config_file))
FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins-build/workspace/ocs-ci/conf/ocs_version/ocs-4.4.yaml'
```

I guess a file specifically for 4.4 needs to be added.

**Comment by zmc** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/1713
