### ISSUE TITLE
aws-cleanup failing with ocs_ci.ocs.exceptions.ClusterIOTagNotFound: Unable to find valid cluster IO tag from ec2 instance tags

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#1850]
aws-cleanup script sometimes fails with following error ([full log](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-aws-cleanup/901//consoleFull)):
```
2020-04-16 06:46:36,011 - MainThread - boto3.resources.action - DEBUG - Response: {'Reservations': [{'Groups': [], 'Instances': [{'AmiLaunchIndex': 0, 'ImageId': 'ami-07b31fa95714c4e45', 'InstanceId': 'i-06d25604690bf7682', 'InstanceType': 't2.medium', 'KeyName': 'openshift-dev', 'LaunchTime': datetime.datetime(2020, 4, 16, 6, 39, 16, tzinfo=tzlocal()), 'Monitoring': {'State': 'disabled'}, 'Placement': {'AvailabilityZone': 'us-east-2a', 'GroupName': '', 'Tenancy': 'default'}, 'PrivateDnsName': 'ip-10-0-3-38.us-east-2.compute.internal', 'PrivateIpAddress': '10.0.3.38', 'ProductCodes': [], 'PublicDnsName': 'ec2-18-218-197-105.us-east-2.compute.amazonaws.com', 'PublicIpAddress': '18.218.197.105', 'State': {'Code': 16, 'Name': 'running'}, 'StateTransitionReason': '', 'SubnetId': 'subnet-05b0d26b655f83886', 'VpcId': 'vpc-0f31902cde8b3769e', 'Architecture': 'x86_64', 'BlockDeviceMappings': [{'DeviceName': '/dev/sda1', 'Ebs': {'AttachTime': datetime.datetime(2020, 4, 16, 6, 39, 17, tzinfo=tzlocal()), 'DeleteOnTermination': True, 'Status': 'attached', 'VolumeId': 'vol-0e1a330c4e08ce82e'}}], 'ClientToken': 'dahor-RHELM-4LW835XGEDNO', 'EbsOptimized': False, 'EnaSupport': True, 'Hypervisor': 'xen', 'NetworkInterfaces': [{'Association': {'IpOwnerId': 'amazon', 'PublicDnsName': 'ec2-18-218-197-105.us-east-2.compute.amazonaws.com', 'PublicIp': '18.218.197.105'}, 'Attachment': {'AttachTime': datetime.datetime(2020, 4, 16, 6, 39, 16, tzinfo=tzlocal()), 'AttachmentId': 'eni-attach-017a933632a6d3163', 'DeleteOnTermination': True, 'DeviceIndex': 0, 'Status': 'attached'}, 'Description': '', 'Groups': [{'GroupName': 'dahorak-int-svc-CustomSecurityGroup-AFV96K0ADO2L', 'GroupId': 'sg-051f56416a6d66e22'}], 'Ipv6Addresses': [], 'MacAddress': '02:2c:6e:73:84:4e', 'NetworkInterfaceId': 'eni-0009d5f51b738dd07', 'OwnerId': '861790564636', 'PrivateDnsName': 'ip-10-0-3-38.us-east-2.compute.internal', 'PrivateIpAddress': '10.0.3.38', 'PrivateIpAddresses': [{'Association': {'IpOwnerId': 'amazon', 'PublicDnsName': 'ec2-18-218-197-105.us-east-2.compute.amazonaws.com', 'PublicIp': '18.218.197.105'}, 'Primary': True, 'PrivateDnsName': 'ip-10-0-3-38.us-east-2.compute.internal', 'PrivateIpAddress': '10.0.3.38'}], 'SourceDestCheck': True, 'Status': 'in-use', 'SubnetId': 'subnet-05b0d26b655f83886', 'VpcId': 'vpc-0f31902cde8b3769e', 'InterfaceType': 'interface'}], 'RootDeviceName': '/dev/sda1', 'RootDeviceType': 'ebs', 'SecurityGroups': [{'GroupName': 'dahorak-int-svc-CustomSecurityGroup-AFV96K0ADO2L', 'GroupId': 'sg-051f56416a6d66e22'}], 'SourceDestCheck': True, 'Tags': [{'Key': 'aws:cloudformation:logical-id', 'Value': 'RHELMachine'}, {'Key': 'Name', 'Value': 'dahorak-int-svc'}, {'Key': 'aws:cloudformation:stack-id', 'Value': 'arn:aws:cloudformation:us-east-2:861790564636:stack/dahorak-int-svc/f7176730-7fac-11ea-b3bb-0abbead6f3aa'}, {'Key': 'aws:cloudformation:stack-name', 'Value': 'dahorak-int-svc'}], 'VirtualizationType': 'hvm', 'CpuOptions': {'CoreCount': 2, 'ThreadsPerCore': 1}, 'CapacityReservationSpecification': {'CapacityReservationPreference': 'open'}, 'HibernationOptions': {'Configured': False}, 'MetadataOptions': {'State': 'applied', 'HttpTokens': 'optional', 'HttpPutResponseHopLimit': 1, 'HttpEndpoint': 'enabled'}}], 'OwnerId': '861790564636', 'RequesterId': '043320173835', 'ReservationId': 'r-04e0393e89286c191'}], 'ResponseMetadata': {'RequestId': '75d70f0d-e554-4612-b45f-f7cf90b1b5c0', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '75d70f0d-e554-4612-b45f-f7cf90b1b5c0', 'content-type': 'text/xml;charset=UTF-8', 'content-length': '8043', 'vary': 'accept-encoding', 'date': 'Thu, 16 Apr 2020 06:46:35 GMT', 'server': 'AmazonEC2'}, 'RetryAttempts': 0}}
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-aws-cleanup/ocs-ci/.venv/bin/aws-cleanup", line 11, in <module>
    load_entry_point('ocs-ci', 'console_scripts', 'aws-cleanup')()
  File "/home/jenkins/workspace/qe-aws-cleanup/ocs-ci/ocs_ci/cleanup/aws/cleanup.py", line 307, in aws_cleanup
    prefixes_hours_to_spare=prefixes_hours_to_spare,
  File "/home/jenkins/workspace/qe-aws-cleanup/ocs-ci/ocs_ci/cleanup/aws/cleanup.py", line 198, in get_clusters_to_delete
    "Unable to find valid cluster IO tag from ec2 instance tags"
ocs_ci.ocs.exceptions.ClusterIOTagNotFound: Unable to find valid cluster IO tag from ec2 instance tags
```
The failure might be connected with instances which are not part of OCP cluster (e.g. `dahorak-int-svc` instance is part of disconnected cluster setup installed using Flexy).

**Comment by clacroix12** [comment]
This bring up a good point. Currently we are kind of assuming that anything in cloudformation is an OCS cluster that can and should be cleaned up by our `aws-cleanup`. This is clearly not true. I think instead of raising this error (causing the entire cleanup to fail) we should simply log that we were unable to find the cluster IO tag (at warning level) and then break out of the loop without appending the corresponding `cluster_name` to the list of clusters to delete.

@ebenahar does this make sense / maintain the functionality that we are trying to achieve here in the aws-cleanup?
