### ISSUE TITLE
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/mcg.py", line 436, in request_aws_credentials

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#2412]
Seen during PR Testing of  https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/2192/testReport/

```
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/mcg.py", line 436, in request_aws_credentials
    for api_test_result in TimeoutSampler(40, 5, _check_aws_credentials):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 772, in __iter__
    raise self.timeout_exc_cls(*self.timeout_exc_args)
ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed Out: (40,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/_pytest/main.py", line 197, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/_pytest/main.py", line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/_pytest/main.py", line 271, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/_pytest/runner.py", line 84, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/_pytest/runner.py", line 99, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/_pytest/runner.py", line 187, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 414, in pytest_runtest_makereport
    collect_performance_stats(test_case_name)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/tests/helpers.py", line 2211, in collect_performance_stats
    ceph_obj = CephCluster()
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/cluster.py", line 112, in __init__
    self.mcg_obj = MCG()
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/mcg.py", line 125, in __init__
    ) = self.request_aws_credentials()
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/mcg.py", line 445, in request_aws_credentials
    assert False
AssertionError
```

**Comment by MeridianExplorer** [comment]
Same issue that caused [9312](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/9312/) to fail - 
`<Error><Code>TooManyBuckets</Code><Message>You have attempted to create more buckets than allowed</Message><CurrentNumberOfBuckets>400</CurrentNumberOfBuckets><AllowedNumberOfBuckets>400</AllowedNumberOfBuckets>`

Our S3 buckets have since been cleaned.
