### ISSUE TITLE
IndexError during collect_noobaa_db_dump if noobaa pod isn't found

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#2828]
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 439, in pytest_runtest_makereport
    collect_ocs_logs(dir_name=test_case_name, ocp=ocp_logs_collection, mcg=mcg)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/utils.py", line 849, in collect_ocs_logs
    collect_noobaa_db_dump(log_dir_path)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/utils.py", line 774, in collect_noobaa_db_dump
    )[0]
IndexError: list index out of range
```

We should probably add a try/except and log an informative message when `get_pods_having_label` does not return anything for the noobaa label here in `collect_noobaa_db_dump`.

**Comment by petr-balogh** [comment]
@MeridianExplorer  once you have some time, can you please take a look at this one? Thanks

**Comment by clacroix12** [comment]
Still seeing this issue in recent executions: https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1676//console
