### ISSUE TITLE
Test case test_pvc_expand_expanded_pvc failed due to timeout (600) on zVM cluster.

### ISSUE THREAD

**Issue by chidanandbh** [red-hat-storage/ocs-ci#3335]
tests/manage/pv_services/pvc_resize/test_pvc_expansion.py::TestPvcExpand::test_pvc_expand_expanded_pvc

Timeout occurred while waiting for fio setup to be completed for `pre_expand IO`.  Setup takes more than 600 seconds to complete. So the wait time should be updated to a higher value.

```
14:53:19 - ThreadPoolExecutor-8_0 - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-4bae371c7dac4bbbb74ffeb6c82bd25b --kubeconfig /root/ocp4-workdir/auth/kubeconfig rsh pod-test-rbd-16bd44e328e5429dbeaca8cdd7370469 fio --name=fio-rand-write --filename=/dev/rbdblock --rw=randwrite --bs=4K --direct=0 --numjobs=1 --time_based=1 --runtime=60 --size=4G --ioengine=libaio --iodepth=4 --rate=1m --rate_process=poisson --output-format=json
14:53:19 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - pre_expand IO started on pod pod-test-rbd-16bd44e328e5429dbeaca8cdd7370469.
14:53:19 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - pre_expand IO started on pods.
14:53:19 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - Verifying pre_expand IO on pods.
14:53:19 - MainThread - ocs_ci.ocs.resources.pod - INFO - Waiting for FIO results from pod pod-test-cephfs-1c180a15aa174116b6b4612f6acdf51b
14:54:21 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - Verified pre_expand IO on pod pod-test-cephfs-1c180a15aa174116b6b4612f6acdf51b.
14:54:21 - MainThread - ocs_ci.ocs.resources.pod - INFO - Waiting for FIO results from pod pod-test-cephfs-a959bca1b4b54fdfa2a6c00a3bf1e5b8
14:54:21 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - Verified pre_expand IO on pod pod-test-cephfs-a959bca1b4b54fdfa2a6c00a3bf1e5b8.
14:54:21 - MainThread - ocs_ci.ocs.resources.pod - INFO - Waiting for FIO results from pod pod-test-cephfs-fe71490b6947488a820de3d8bba75923
14:54:21 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - Verified pre_expand IO on pod pod-test-cephfs-fe71490b6947488a820de3d8bba75923.
14:54:21 - MainThread - ocs_ci.ocs.resources.pod - INFO - Waiting for FIO results from pod pod-test-rbd-a66b45929afb4e59a69b05bfed269895
15:03:19 - MainThread - ocs_ci.ocs.resources.pod - ERROR - Found Exception: Command '['oc', '-n', 'namespace-test-4bae371c7dac4bbbb74ffeb6c82bd25b', '--kubeconfig', '/root/ocp4-workdir/auth/kubeconfig', 'rsh', 'pod-test-rbd-a66b45929afb4e59a69b05bfed269895', 'fio', '--name=fio-rand-write', '--filename=/var/lib/www/html/pod-test-rbd-a66b45929afb4e59a69b05bfed269895_pre_expand', '--rw=randwrite', '--bs=4K', '--direct=0', '--numjobs=1', '--time_based=1', '--runtime=60', '--size=9G', '--ioengine=libaio', '--iodepth=4', '--rate=1m', '--rate_process=poisson', '--output-format=json']' timed out after 600 seconds
Traceback (most recent call last):
  File "/usr/lib64/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 1535, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib64/python3.6/subprocess.py", line 891, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['oc', '-n', 'namespace-test-4bae371c7dac4bbbb74ffeb6c82bd25b', '--kubeconfig', '/root/ocp4-workdir/auth/kubeconfig', 'rsh', 'pod-test-rbd-a66b45929afb4e59a69b05bfed269895', 'fio', '--name=fio-rand-write', '--filename=/var/lib/www/html/pod-test-rbd-a66b45929afb4e59a69b05bfed269895_pre_expand', '--rw=randwrite', '--bs=4K', '--direct=0', '--numjobs=1', '--time_based=1', '--runtime=60', '--size=9G', '--ioengine=libaio', '--iodepth=4', '--rate=1m', '--rate_process=poisson', '--output-format=json']' timed out after 600 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ocs-ci/ocs_ci/ocs/resources/pod.py", line 124, in get_fio_results
    result = self.fio_thread.result(timeout)
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/ocs-ci/ocs_ci/utility/workloads/fio.py", line 93, in run
    fio_cmd, out_yaml_format=False, timeout=timeout
  File "/root/ocs-ci/ocs_ci/ocs/resources/pod.py", line 158, in exec_cmd_on_pod
    rsh_cmd, out_yaml_format, secrets=secrets, timeout=timeout, **kwargs
  File "/root/ocs-ci/ocs_ci/ocs/ocp.py", line 138, in exec_oc_cmd
    ignore_error=ignore_error, **kwargs
  File "/root/ocs-ci/ocs_ci/utility/utils.py", line 415, in run_cmd
    completed_process = exec_cmd(cmd, secrets, timeout, ignore_error, **kwargs)
  File "/root/ocs-ci/ocs_ci/utility/utils.py", line 454, in exec_cmd
    **kwargs
  File "/usr/lib64/python3.6/subprocess.py", line 430, in run
    stderr=stderr)
subprocess.TimeoutExpired: Command '['oc', '-n', 'namespace-test-4bae371c7dac4bbbb74ffeb6c82bd25b', '--kubeconfig', '/root/ocp4-workdir/auth/kubeconfig', 'rsh', 'pod-test-rbd-a66b45929afb4e59a69b05bfed269895', 'fio', '--name=fio-rand-write', '--filename=/var/lib/www/html/pod-test-rbd-a66b45929afb4e59a69b05bfed269895_pre_expand', '--rw=randwrite', '--bs=4K', '--direct=0', '--numjobs=1', '--time_based=1', '--runtime=60', '--size=9G', '--ioengine=libaio', '--iodepth=4', '--rate=1m', '--rate_process=poisson', '--output-format=json']' timed out after 600 seconds
FAILED                                                                                                                                                                   [100%]
```

Work Around applied to pass this issue.
Updated this file by increase timeout value from 600 to 800.
```/root/ocs-ci/ocs_ci/utility/workloads/fio.py
timeout = 800  # default timeout for the FIO test
```

After above workaround able to succeed with `pre-expand IO result` and proceeded further. 

```
17:07:08 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - Verified pre-expand IO result on pods.
17:07:08 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - Expanding all PVCs.
17:07:08 - MainThread - tests.manage.pv_services.pvc_resize.test_pvc_expansion - INFO - Expanding size of PVC pvc-test-f708f4a31c4c4050879caa267508a649 to 20G
17:07:08 - MainThread - ocs_ci.ocs.ocp - INFO - Command: patch PersistentVolumeClaim pvc-test-f708f4a31c4c4050879caa267508a649 -n namespace-test-27a0005ca80a491c90be669822fcb8e1 -p '{"spec": {"resources": {"requests": {"storage": "20Gi"}}}}'
17:07:08 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-27a0005ca80a491c90be669822fcb8e1 --kubeconfig /root/ocp4-workdir/auth/kubeconfig patch PersistentVolumeClaim pvc-test-f708f4a31c4c4050879caa267508a649 -n namespace-test-27a0005ca80a491c90be669822fcb8e1 -p '{"spec": {"resources": {"requests": {"storage": "20Gi"}}}}'
17:07:09 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-27a0005ca80a491c90be669822fcb8e1 --kubeconfig /root/ocp4-workdir/auth/kubeconfig get PersistentVolumeClaim pvc-test-f708f4a31c4c4050879caa267508a649 -n namespace-test-27a0005ca80a491c90be669822fcb8e1 -o yaml
17:07:10 - MainThread - ocs_ci.ocs.resources.pvc - INFO - Capacity of PVC pvc-test-f708f4a31c4c4050879caa267508a649 is not 20Gi as expected, but 10Gi. Retrying.
17:07:10 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 2 seconds before next iteration
17:07:12 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n namespace-test-27a0005ca80a491c90be669822fcb8e1 --kubeconfig /root/ocp4-workdir/auth/kubeconfig get PersistentVolumeClaim pvc-test-f708f4a31c4c4050879caa267508a649 -n namespace-test-27a0005ca80a491c90be669822fcb8e1 -o yaml
```

**Comment by chidanandbh** [comment]
currently this defect I am able to fix with work around by increasing the timeout for s390x(z hardware), after its proceeded further and failed with   below defect 

https://bugzilla.redhat.com/show_bug.cgi?id=1886365 		(during PVC expansion its take more then expected time for this defect is opened)
