### ISSUE TITLE
PR validation failed with no test results file

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#3337]
Job: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14671/consoleFull

```
+ run-ci --color=yes tests/ -m deployment -k '' --ocs-version 4.6 --ocp-version 4.6 --ocsci-conf=**** '--ocsci-conf=~/current-cluster-dir/ocsci_conf.yaml' --ocsci-conf=conf/ocsci/vsphere_upi.yaml '--ocsci-conf=~/current-cluster-dir/ocsci_custom_conf.yaml' --collect-logs --collect-logs-on-success-run --cluster-name jnk-pr3304-b3348 --cluster-path /home/jenkins/current-cluster-dir/openshift-cluster-dir --junit-xml /home/jenkins/current-cluster-dir/logs/test_results_1605606756.xml -o junit_suite_name=jnk-pr3304-b3348 '--html=~/current-cluster-dir/logs/test_report_1605606756.html' --self-contained-html --bugzilla --email=vavuthu@redhat.com --squad-analysis
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/bin/run-ci", line 33, in <module>
    sys.exit(load_entry_point('ocs-ci', 'console_scripts', 'run-ci')())
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/framework/main.py", line 107, in main
    init_ocsci_conf(arguments)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/framework/main.py", line 71, in init_ocsci_conf
    load_config(args.ocsci_conf)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/framework/main.py", line 49, in load_config
    custom_config_data = yaml.safe_load(file_stream)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.6/site-packages/yaml/composer.py", line 43, in get_single_node
    event.start_mark)
yaml.composer.ComposerError: expected a single document in the stream
  in "/home/jenkins/current-cluster-dir/ocsci_custom_conf.yaml", line 3, column 1
but found another document
  in "/home/jenkins/current-cluster-dir/ocsci_custom_conf.yaml", line 18, column 1
+ true
+ grep -q -v ' tests="0"' /home/jenkins/current-cluster-dir/logs/test_results_1605606756.xml
grep: /home/jenkins/current-cluster-dir/logs/test_results_1605606756.xml: No such file or directory
[Pipeline] }
```

**Comment by bernerhat** [comment]
Ran into the same issue, Job:
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/3352/
and here (different cluster):
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-trigger-test-pr/3335/

**Comment by petr-balogh** [comment]
Fixing it here:
https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/403
