### ISSUE TITLE
--teardown on partially destroyed cluster fails

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#335]
we need to ignore those errors during teardown

```
NTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/ebenahar/git/ocs-ci/ocs-venv/lib64/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/ebenahar/git/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 103, in pytest_configure
INTERNALERROR>     ceph_version = get_ceph_version()
INTERNALERROR>   File "/home/ebenahar/git/ocs-ci/ocs_ci/utility/utils.py", line 876, in get_ceph_version
INTERNALERROR>     ct_pod = pod.get_ceph_tools_pod()
INTERNALERROR>   File "/home/ebenahar/git/ocs-ci/ocs_ci/ocs/resources/pod.py", line 173, in get_ceph_tools_pod
INTERNALERROR>     )['items'][0]
INTERNALERROR> IndexError: list index out of range
I don't have the ceph pods:
[ebenahar@localhost ocs-ci]$ oc -n openshift-storage --kubeconfig /home/ebenahar/ebenahar-ocs/auth/kubeconfig get pod
NAME                                  READY   STATUS    RESTARTS   AGE
rook-ceph-operator-5c6fd4b7db-2twzd   1/1     Running   0          51m
rook-discover-c8sv5                   1/1     Running   0          42m
rook-discover-cs64z                   1/1     Running   0          42m
rook-discover-g6rsc                   1/1     Running   0          42m
```

**Comment by fbalak** [comment]
I believe that this is not fixed yet. I currently have incorrectly deployed cluster:
```
$ oc get pods -n openshift-storage
NAME                                  READY   STATUS                  RESTARTS   AGE
csi-cephfsplugin-2zq6c                2/2     Running                 0          49m
csi-cephfsplugin-provisioner-0        3/3     Running                 0          49m
csi-cephfsplugin-psx6z                2/2     Running                 0          49m
csi-cephfsplugin-px8rr                2/2     Running                 0          49m
csi-rbdplugin-dkrkn                   2/2     Running                 0          49m
csi-rbdplugin-ln59c                   2/2     Running                 0          49m
csi-rbdplugin-p79bp                   2/2     Running                 0          49m
csi-rbdplugin-provisioner-0           4/4     Running                 0          49m
rook-ceph-agent-26ghq                 1/1     Running                 0          49m
rook-ceph-agent-69vr9                 1/1     Running                 0          49m
rook-ceph-agent-kdlg8                 1/1     Running                 0          49m
rook-ceph-mon-a-8696c9ff58-ldt9b      0/1     Init:CrashLoopBackOff   14         48m
rook-ceph-operator-5c6fd4b7db-5w9vq   1/1     Running                 0          51m
rook-discover-5xpqr                   1/1     Running                 0          50m
rook-discover-bjg5h                   1/1     Running                 0          50m
rook-discover-q5hln                   1/1     Running                 0          50m
```
If I try to destroy it then it fails with similar error:
```
$ run-ci -m destroy  --cluster-conf conf/ocs_basic_install.yml     --cluster-name fbalak-ocs-deployment-2 --cluster-path /home/ocsqe/data/ocs-instances/current/
Collecting Cluster versions
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/venv3/lib64/python3.6/site-packages/_pytest/main.py", line 202, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/venv3/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 671, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/venv3/lib64/python3.6/site-packages/pluggy/hooks.py", line 311, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/venv3/lib64/python3.6/site-packages/pluggy/manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/venv3/lib64/python3.6/site-packages/pluggy/manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/venv3/lib64/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/venv3/lib64/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/venv3/lib64/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 119, in pytest_configure
INTERNALERROR>     ceph_version = get_ceph_version()
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/ocs_ci/utility/utils.py", line 877, in get_ceph_version
INTERNALERROR>     ct_pod = pod.get_ceph_tools_pod()
INTERNALERROR>   File "/home/ocsqe/data/fbalak/ocs-ci/ocs_ci/ocs/resources/pod.py", line 264, in get_ceph_tools_pod
INTERNALERROR>     )['items'][0]
INTERNALERROR> IndexError: list index out of range
```
I tested this with commit bab60ac7dd7b9ec30802cd5df8784cc1ec18c96b.

**Comment by dahorak** [comment]
Some of the failing cases should be fixed by https://github.com/red-hat-storage/ocs-ci/pull/730, but not sure if those specific one.

**Comment by vasukulkarni** [comment]
Closing stale issue.
