### ISSUE TITLE
wait longer/retry for the rook-ceph-operator 

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#34]
Not sure how much time it took, but when I reran the condition was met.

```
2019-05-09 19:52:26,809 - test_ocs_basic_install - INFO - Waiting 5 seconds...
INFO:utility.utils:Executing command: oc wait --for condition=ready pod -l app=rook-ceph-operator -n openshift-storage --timeout=120s
2019-05-09 19:52:31,816 - utility.utils - INFO - Executing command: oc wait --for condition=ready pod -l app=rook-ceph-operator -n openshift-storage --timeout=120s
DEBUG:utility.utils:CMD output: 
ERROR:utility.utils:CMD error:: error: no matching resources found

2019-05-09 19:52:32,331 - utility.utils - ERROR - CMD error:: error: no matching resources found

ERROR:ocsci.framework:Traceback (most recent call last):
  File "/Users/vasukulkarni/ocs/ocs-ci/ocsci/framework.py", line 116, in execute
    rc = self.test_mod.run(**self.test_kwargs)
  File "/Users/vasukulkarni/ocs/ocs-ci/tests/test_ocs_basic_install.py", line 134, in run
    "oc wait --for condition=ready pod "
  File "/Users/vasukulkarni/ocs/ocs-ci/utility/utils.py", line 650, in run_cmd
    f"Error during execution of command: {cmd}"
ocs.exceptions.CommandFailed: Error during execution of command: ['oc', 'wait', '--for', 'condition=ready', 'pod', '-l', 'app=rook-ceph-operator', '-n', 'openshift-storage', '--timeout=120s']

2019-05-09 19:52:32,335 - ocsci.framework - ERROR - Traceback (most recent call last):
  File "/Users/vasukulkarni/ocs/ocs-ci/ocsci/framework.py", line 116, in execute
    rc = self.test_mod.run(**self.test_kwargs)
  File "/Users/vasukulkarni/ocs/ocs-ci/tests/test_ocs_basic_install.py", line 134, in run
    "oc wait --for condition=ready pod "
  File "/Users/vasukulkarni/ocs/ocs-ci/utility/utils.py", line 650, in run_cmd
    f"Error during execution of command: {cmd}"
ocs.exceptions.CommandFailed: Error during execution of command: ['oc', 'wait', '--for', 'condition=ready', 'pod', '-l', 'app=rook-ceph-operator', '-n', 'openshift-storage', '--timeout=120s']

```

**Comment by ksandha** [comment]
Hitting the same issue.
2019-05-14 12:26:37,416 - test_ocs_basic_install - INFO - Waiting 5 seconds...
2019-05-14 12:26:42,427 - utility.utils - INFO - Executing command: oc wait --for condition=ready pod -l app=rook-ceph-operator -n openshift-storage --timeout=120s
2019-05-14 12:26:43,614 - utility.utils - DEBUG - CMD output: 
2019-05-14 12:26:43,614 - utility.utils - ERROR - CMD error:: error: no matching resources found

2019-05-14 12:26:43,617 - ocsci.framework - ERROR - Traceback (most recent call last):
  File "/home/ksandha/Documents/workspace/ocs-ci/ocsci/framework.py", line 131, in execute
    test_status = self.test_mod.run(**self.test_kwargs)
  File "/home/ksandha/Documents/workspace/ocs-ci/tests/test_ocs_basic_install.py", line 144, in run
    "oc wait --for condition=ready pod "
  File "/home/ksandha/Documents/workspace/ocs-ci/utility/utils.py", line 647, in run_cmd
    f"Error during execution of command: {cmd}"
ocs.exceptions.CommandFailed: Error during execution of command: ['oc', 'wait', '--for', 'condition=ready', 'pod', '-l', 'app=rook-ceph-operator', '-n', 'openshift-storage', '--timeout=120s']

**Comment by vasukulkarni** [comment]
@ksandha thanks, I will try this again today.

**Comment by petr-balogh** [comment]
Increased timeout for another 5 seconds in #57 , in case anyone will hit the issue again, feel free to reopen this issue.

**Comment by jilju** [comment]
I am still getting this error. 

```INFO:utility.utils:Executing command: oc create -f /home/jijoy/jijoy-testing-cluster/operator-openshift.yaml
2019-05-21 11:07:30,541 - utility.utils - INFO - Executing command: oc create -f /home/jijoy/jijoy-testing-cluster/operator-openshift.yaml
DEBUG:utility.utils:CMD output: securitycontextconstraints.security.openshift.io/rook-ceph created
deployment.apps/rook-ceph-operator created```

INFO:test_ocs_basic_install:Waiting 10 seconds...
2019-05-21 11:07:32,208 - test_ocs_basic_install - INFO - Waiting 10 seconds...
INFO:utility.utils:Executing command: oc wait --for condition=ready pod -l app=rook-ceph-operator -n openshift-storage --timeout=120s
2019-05-21 11:07:42,216 - utility.utils - INFO - Executing command: oc wait --for condition=ready pod -l app=rook-ceph-operator -n openshift-storage --timeout=120s
DEBUG:utility.utils:CMD output: 
ERROR:utility.utils:CMD error:: error: no matching resources found

2019-05-21 11:07:43,477 - utility.utils - ERROR - CMD error:: error: no matching resources found

ERROR:ocsci.framework:Traceback (most recent call last):
  File "/home/jijoy/ocs-ci/ocsci/framework.py", line 134, in execute
    test_status = self.test_mod.run(**self.test_kwargs)
  File "/home/jijoy/ocs-ci/tests/test_ocs_basic_install.py", line 119, in run
    f"oc wait --for condition=ready pod "
  File "/home/jijoy/ocs-ci/utility/utils.py", line 654, in run_cmd
    f"Error during execution of command: {cmd}"
ocs.exceptions.CommandFailed: Error during execution of command: ['oc', 'wait', '--for', 'condition=ready', 'pod', '-l', 'app=rook-ceph-operator', '-n', 'openshift-storage', '--timeout=120s']

2019-05-21 11:07:43,478 - ocsci.framework - ERROR - Traceback (most recent call last):
  File "/home/jijoy/ocs-ci/ocsci/framework.py", line 134, in execute
    test_status = self.test_mod.run(**self.test_kwargs)
  File "/home/jijoy/ocs-ci/tests/test_ocs_basic_install.py", line 119, in run
    f"oc wait --for condition=ready pod "
  File "/home/jijoy/ocs-ci/utility/utils.py", line 654, in run_cmd
    f"Error during execution of command: {cmd}"
ocs.exceptions.CommandFailed: Error during execution of command: ['oc', 'wait', '--for', 'condition=ready', 'pod', '-l', 'app=rook-ceph-operator', '-n', 'openshift-storage', '--timeout=120s'] ```
