### ISSUE TITLE
Could not deploy OCS using OCS-CI

### ISSUE THREAD

**Issue by gitsridhar** [red-hat-storage/ocs-ci#3686]
When we deploy OCS using ocs-ci/run-ci tool, getting an error 'No module named 'greenlet._greenlet''. We started seeing this error starting today.

When we run 

run-ci -m deployment --deploy \
        --ocs-version $OCS_VERSION --cluster-name ocstest \
        --ocsci-conf conf/ocsci/production_powervs_upi.yaml \
        --ocsci-conf $WORKSPACE/ocs-ci-conf.yaml \
        --cluster-path $WORKSPACE --collect-logs tests/

we get this error: 

Traceback (most recent call last):
  File "/home/test/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 575, in import_plugin
    __import__(importspec)
  File "/home/test/ocs-upi-kvm/src/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 33, in <module>
    from ocs_ci.ocs.utils import collect_ocs_logs, collect_prometheus_metrics
  File "/home/test/ocs-upi-kvm/src/ocs-ci/ocs_ci/ocs/utils.py", line 12, in <module>
    from gevent import sleep
  File "/home/test/venv/lib64/python3.6/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/home/test/venv/lib64/python3.6/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/test/venv/lib64/python3.6/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
  File "/home/test/venv/lib64/python3.6/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ModuleNotFoundError: No module named 'greenlet._greenlet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/venv/bin/run-ci", line 33, in <module>
    sys.exit(load_entry_point('ocs-ci', 'console_scripts', 'run-ci')())
  File "/home/test/ocs-upi-kvm/src/ocs-ci/ocs_ci/framework/main.py", line 127, in main
    return pytest.main(arguments)
  File "/home/test/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 73, in main
    config = _prepareconfig(args, plugins)
  File "/home/test/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 214, in _prepareconfig
    config = get_config(args, plugins)
  File "/home/test/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 186, in get_config
    pluginmanager.consider_preparse(args)
  File "/home/test/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 509, in consider_preparse
    self.consider_pluginarg(parg)
  File "/home/test/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 534, in consider_pluginarg
    self.import_plugin(arg, consider_entry_points=True)
  File "/home/test/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 583, in import_plugin
    raise new_exc.with_traceback(tb)
  File "/home/test/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 575, in import_plugin
    __import__(importspec)
  File "/home/test/ocs-upi-kvm/src/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 33, in <module>
    from ocs_ci.ocs.utils import collect_ocs_logs, collect_prometheus_metrics
  File "/home/test/ocs-upi-kvm/src/ocs-ci/ocs_ci/ocs/utils.py", line 12, in <module>
    from gevent import sleep
  File "/home/test/venv/lib64/python3.6/site-packages/gevent/__init__.py", line 86, in <module>
    from gevent._hub_local import get_hub
  File "/home/test/venv/lib64/python3.6/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/test/venv/lib64/python3.6/site-packages/gevent/_util.py", line 148, in import_c_accel
    mod = importlib.import_module(cname)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/_hub_local.py", line 1, in init gevent._gevent_c_hub_local
  File "/home/test/venv/lib64/python3.6/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: Error importing plugin "ocs_ci.framework.pytest_customization.ocscilib": No module named 'greenlet._greenlet'

**Comment by vavuthu** [comment]
could you try reinstalling requirements.txt and re-try

**Comment by petr-balogh** [comment]
Yep I also think that `pip install -U -r requirements.txt` will help here

**Comment by petr-balogh** [comment]
I am closing this now as we don't see such issues anywhere else so I guess only issue with your local venv.  Feel free to reopen if nothing helped, even if you removed and created new venv from scratch. Thanks

**Comment by gitsridhar** [comment]
Prior to running this run-ci, we do run the following: 
#!/bin/bash

set -e

if [ ! -e helper/parameters.sh ]; then
        echo "This script should be invoked from the directory ocs-upi-kvm/scripts"
        exit 1
fi

sudo yum -y install libffi-devel lapack atlas-devel openssl-devel gcc gcc-c++ gcc-gfortran make
sudo yum -y install python36-devel python3-setuptools python3-virtualenv python3-docutils

source helper/parameters.sh

pushd ../src/ocs-ci

rm -rf $WORKSPACE/venv

python3.6 -m venv $WORKSPACE/venv

source $WORKSPACE/venv/bin/activate             # activate named python venv

pip3 install --upgrade pip setuptools wheel
pip3 install -r requirements.txt
pip3 install yq

deactivate                                      # exit venv shell

popd

Did anything changed here, do we need to do anything else before running run-ci.?

**Comment by gitsridhar** [comment]
Trying to reopen this issue...

**Comment by lukebrowning** [comment]
The versions of python modules in the venv changed yesterday. 

These are the old versions:

(venv) [jenkins-build@cpt-ppc-011p ocs-ci]$ pip3 show greenlet gevent zope.event zope.interface setuptools | egrep '^Name|^Version'
Name: greenlet
Version: 0.4.17
Name: gevent
Version: 20.6.2
Name: zope.event
Version: 4.5.0
Name: zope.interface
Version: 5.1.2
Name: setuptools
Version: 50.3.0

New versions:

(venv) [luke@nx144-ahv hugepages]$ pip3 show greenlet gevent zope.event zope.interface setuptools | egrep '^Name|^Version'
Name: greenlet
Version: 1.0.0
Name: gevent
Version: 20.9.0
Name: zope.event
Version: 4.5.0
Name: zope.interface
Version: 5.2.0
Name: setuptools
Version: 51.1.2

**Comment by lukebrowning** [comment]
Actually, the OLD versions above appear to be from Oct 9.   The breakage occurred yesterday.    We create new clusters every day.

**Comment by lukebrowning** [comment]
Greenlet 1.0 was released yesterday.

**Comment by lukebrowning** [comment]
I worked this issue by pip installing the previous version of greenlet.

**Comment by lukebrowning** [comment]
This is not an issue anymore as Zack integrated a fix to restrict the version of greenlet below 1.0.

**Comment by gitsridhar** [comment]
Closing this issue, do not see this anylonger.
