### ISSUE TITLE
Prometheus error messages -- Is latest tests/conftest.py missing something?

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3704]
While running a run-ci test on a clone of the most recent ocs-ci code, I saw the following:

21:41:10 - Dummy-7 - ocs_ci.utility.utils - INFO - Executing command: oc get Namespace  -A -o yaml
21:41:31 - MainThread - tests.conftest - ERROR - There was a problem with connecting to Promeheus
Traceback (most recent call last):
  File "/home/wusui/ocs-ci/tests/conftest.py", line 2764, in log_alerts
    prometheus = PrometheusAPI()
  File "/home/wusui/ocs-ci/ocs_ci/utility/prometheus.py", line 314, in __init__
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/wusui/ocs-ci/auth/kubeadmin-password'
21:41:31 - MainThread - tests.conftest - ERROR - There was a problem with collecting alerts for analysis
Traceback (most recent call last):
  File "/home/wusui/ocs-ci/tests/conftest.py", line 2770, in _collect_alerts
    alerts_response = prometheus.get(
AttributeError: 'NoneType' object has no attribute 'get'
21:41:31 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc new-project my-ripsaw

When I diffed the tests/conftest.py file with the tests/conftest.py of an older branch, I saw that the following was missing from the latest branch.
70d69
< from ocs_ci.utility.prometheus import PrometheusAPI
2750,2798d2748
< 
< 
< @pytest.fixture(autouse=True)
< def log_alerts(request):
<     """
<     Log alerts at the beginning and end of each test case. At the end of test
<     case print a difference: what new alerts are in place after the test is
<     complete.
< 
<     """
<     alerts_before = []
<     prometheus = None
< 
<     try:
<         prometheus = PrometheusAPI()
<     except Exception:
<         log.exception("There was a problem with connecting to Promeheus")
< 
<     def _collect_alerts():
<         try:
<             alerts_response = prometheus.get(
<                 "alerts", payload={"silenced": False, "inhibited": False}
<             )
<             if alerts_response.ok:
<                 alerts = alerts_response.json().get("data").get("alerts")
<                 log.debug(f"Found alerts: {alerts}")
<                 return alerts
<             else:
<                 log.warning(
<                     f"There was a problem with collecting alerts for analysis: {alerts_response.text}"
<                 )
<                 return False
<         except Exception:
<             log.exception("There was a problem with collecting alerts for analysis")
<             return False
< 
<     def _print_diff():
<         if alerts_before:
<             alerts_after = _collect_alerts()
<             if alerts_after:
<                 alerts_new = [
<                     alert for alert in alerts_after if alert not in alerts_before
<                 ]
<                 if alerts_new:
<                     log.warning("During test were raised new alerts")
<                     log.warning(alerts_new)
< 
<     alerts_before = _collect_alerts()
<     request.addfinalizer(_print_diff)

When I reran the run-ci command using the older conftest.py, I did not get the Prometheus error messages.

The last commit on git for the latest cloned ocs-ci is:
commit a99be4d916e9ce7b2910fb0934e57fa4d288b35a

**Comment by wusui** [comment]
Closed -- looks like pilot error on my part.  Never mind...
