### ISSUE TITLE
test_create_pvc_random_storage_class.py is stuck 

### ISSUE THREAD

**Issue by RazTamir** [red-hat-storage/ocs-ci#384]
Hi,

test test_create_pvc_random_storage_class.py is stuck and cause the entire tier1 to stuck

**Comment by clacroix12** [comment]
It appears the issue here is in the teardown.

```
tests/manage/test_create_pvc_random_storage_class.py::TestCreatePVCRandomStorageClass::test_create_pvc_with_random_sc::teardown
```
**Duration: 4965.65** -- almost 1.5 hours stuck in this teardown

```
def finalizer():
> teardown()

tests/manage/test_create_pvc_random_storage_class.py:20:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/manage/test_create_pvc_random_storage_class.py:53: in teardown
assert pvc.delete_all_pvcs()
ocs_ci/ocs/resources/pvc.py:91: in delete_all_pvcs
ocp_pvc_obj.delete(resource_name=item.get('metadata').get('name'))
ocs_ci/ocs/ocp.py:172: in delete
return self.exec_oc_cmd(command)
ocs_ci/ocs/ocp.py:70: in exec_oc_cmd
out = run_cmd(cmd=oc_cmd)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['oc', '-n', 'openshift-storage', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'delete', ...], kwargs = {}
r = CompletedProcess(args=['oc', '-n', 'openshift-storage', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kube....0.105:61344->3.130.147.211:6443: read: operation timed out\nUnable to connect to the server: dial tcp: i/o timeout\n')

def run_cmd(cmd, **kwargs):
"""
Run an arbitrary command locally

Args:
cmd (str): command to run

Raises:
CommandFailed: In case the command execution fails

Returns:
(str) Decoded stdout of command

"""
log.info(f"Executing command: {cmd}")
if isinstance(cmd, str):
cmd = shlex.split(cmd)
r = subprocess.run(
cmd,
stdout=subprocess.PIPE,
stderr=subprocess.PIPE,
stdin=subprocess.PIPE,
**kwargs
)
log.debug(f"Command output: {r.stdout.decode()}")
if r.stderr and not r.returncode:
log.warning(f"Command warning:: {r.stderr.decode()}")
if r.returncode:
raise CommandFailed(
> f"Error during execution of command: {cmd}."
f"\nError is {r.stderr.decode()}"
)
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '-n', 'openshift-storage', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'delete', 'PersistentVolumeClaim', 'pvc-test-0914102550'].
E           Error is E0709 17:54:57.346758    6567 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 192.168.0.105:61344->3.130.147.211:6443: read: operation timed out
E           Unable to connect to the server: dial tcp: i/o timeout

ocs_ci/utility/utils.py:381: CommandFailed
--------------------------- Captured stderr teardown ---------------------------
Traceback (most recent call last): File "/Users/clacroix/workspace/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values env_status_dict[key] = kind.get(all_namespaces=True)['items'] File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get return self.exec_oc_cmd(command) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd out = run_cmd(cmd=oc_cmd) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd f"Error during execution of command: {cmd}." ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'get', 'StorageClass', '-A', '-o', 'yaml']. Error is Unable to connect to the server: dial tcp: i/o timeout 2019-07-10T00:57:57Z (<ThreadPool at 0x110c1f390 7/8/8 hub=<Hub at 0x1102bbf60 thread_ident=0x4724229568>>, <function assign_get_values at 0x110248c80>) failed with CommandFailed Traceback (most recent call last): File "/Users/clacroix/workspace/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values env_status_dict[key] = kind.get(all_namespaces=True)['items'] File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get return self.exec_oc_cmd(command) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd out = run_cmd(cmd=oc_cmd) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd f"Error during execution of command: {cmd}." ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'get', 'Pod', '-A', '-o', 'yaml']. Error is Unable to connect to the server: dial tcp: i/o timeout 2019-07-10T00:57:57Z (<ThreadPool at 0x110c1f390 6/8/8 hub=<Hub at 0x1102bbf60 thread_ident=0x4724229568>>, <function assign_get_values at 0x110248c80>) failed with CommandFailed Traceback (most recent call last): File "/Users/clacroix/workspace/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values env_status_dict[key] = kind.get(all_namespaces=True)['items'] File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get return self.exec_oc_cmd(command) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd out = run_cmd(cmd=oc_cmd) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd f"Error during execution of command: {cmd}." ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'get', 'CephFileSystem', '-A', '-o', 'yaml']. Error is Unable to connect to the server: dial tcp: i/o timeout 2019-07-10T00:57:57Z (<ThreadPool at 0x110c1f390 4/8/8 hub=<Hub at 0x1102bbf60 thread_ident=0x4724229568>>, <function assign_get_values at 0x110248c80>) failed with CommandFailed Traceback (most recent call last): File "/Users/clacroix/workspace/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values env_status_dict[key] = kind.get(all_namespaces=True)['items'] File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get return self.exec_oc_cmd(command) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd out = run_cmd(cmd=oc_cmd) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd f"Error during execution of command: {cmd}." ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'get', 'CephBlockPool', '-A', '-o', 'yaml']. Error is Unable to connect to the server: dial tcp: i/o timeout 2019-07-10T00:57:57Z (<ThreadPool at 0x110c1f390 4/8/8 hub=<Hub at 0x1102bbf60 thread_ident=0x4724229568>>, <function assign_get_values at 0x110248c80>) failed with CommandFailed Traceback (most recent call last): File "/Users/clacroix/workspace/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values env_status_dict[key] = kind.get(all_namespaces=True)['items'] File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get return self.exec_oc_cmd(command) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd out = run_cmd(cmd=oc_cmd) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd f"Error during execution of command: {cmd}." ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'get', 'PersistentVolume', '-A', '-o', 'yaml']. Error is Unable to connect to the server: dial tcp: i/o timeout 2019-07-10T00:57:57Z (<ThreadPool at 0x110c1f390 0/4/8 hub=<Hub at 0x1102bbf60 thread_ident=0x4724229568>>, <function assign_get_values at 0x110248c80>) failed with CommandFailed Traceback (most recent call last): File "/Users/clacroix/workspace/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values env_status_dict[key] = kind.get(all_namespaces=True)['items'] File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get return self.exec_oc_cmd(command) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd out = run_cmd(cmd=oc_cmd) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd f"Error during execution of command: {cmd}." ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'get', 'Secret', '-A', '-o', 'yaml']. Error is Unable to connect to the server: dial tcp: i/o timeout 2019-07-10T00:57:57Z (<ThreadPool at 0x110c1f390 0/4/8 hub=<Hub at 0x1102bbf60 thread_ident=0x4724229568>>, <function assign_get_values at 0x110248c80>) failed with CommandFailed Traceback (most recent call last): File "/Users/clacroix/workspace/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values env_status_dict[key] = kind.get(all_namespaces=True)['items'] File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get return self.exec_oc_cmd(command) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd out = run_cmd(cmd=oc_cmd) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd f"Error during execution of command: {cmd}." ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'get', 'Namespace', '-A', '-o', 'yaml']. Error is Unable to connect to the server: dial tcp: i/o timeout 2019-07-10T00:57:57Z (<ThreadPool at 0x110c1f390 0/4/8 hub=<Hub at 0x1102bbf60 thread_ident=0x4724229568>>, <function assign_get_values at 0x110248c80>) failed with CommandFailed Traceback (most recent call last): File "/Users/clacroix/workspace/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker value = func(*args, **kwargs) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values env_status_dict[key] = kind.get(all_namespaces=True)['items'] File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get return self.exec_oc_cmd(command) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd out = run_cmd(cmd=oc_cmd) File "/Users/clacroix/workspace/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd f"Error during execution of command: {cmd}." ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/Users/clacroix/clusters/log-test-2/auth/kubeconfig', 'get', 'PersistentVolumeClaim', '-A', '-o', 'yaml']. Error is Unable to connect to the server: dial tcp: i/o timeout 2019-07-10T00:57:57Z (<ThreadPool at 0x110c1f390 0/4/8 hub=<Hub at 0x1102bbf60 thread_ident=0x4724229568>>, <function assign_get_values at 0x110248c80>) failed with CommandFailed 
```

**Comment by prsurve** [comment]
Fixed in #385

**Comment by RazTamir** [comment]
@prsurve Is it still impacting us?

**Comment by vasukulkarni** [comment]
PR is merged and issue is Fixed.
