### ISSUE TITLE
stable testing ssh key invalid format 

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#3910]
Stable branch qualification is being blocked by the following error. We are seeing an invalid format error when attempting to clone the ocs-ci repository:

```
13:14:36  Checking out git repository: 'git@github.com:red-hat-storage/ocs-ci.git', branch: 'master', refspec: '+refs/heads/*:refs/remotes/origin/*'.
[Pipeline] checkout
13:14:36  The recommended git tool is: NONE
13:14:36  using credential ocs-ci-ssh-key
13:14:36  Cloning the remote Git repository
13:14:36  ERROR: Error cloning remote repo 'origin'
13:14:36  hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- git@github.com:red-hat-storage/ocs-ci.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
13:14:36  stdout: 
13:14:36  stderr: Load key "/home/jenkins/workspace/qe-ocs-ci-stable-branch-pipeline/ocs-ci@tmp/jenkins-gitclient-ssh3934710112167843282.key": invalid format
13:14:36  git@github.com: Permission denied (publickey).
13:14:36  fatal: Could not read from remote repository.
13:14:36  
13:14:36  Please make sure you have the correct access rights
13:14:36  and the repository exists.
13:14:36  
13:14:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2450)
13:14:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2051)
13:14:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:84)
13:14:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:573)
13:14:36  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:802)
13:14:36  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
13:14:36  	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
13:14:36  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
13:14:36  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
13:14:36  	at hudson.remoting.Request$2.run(Request.java:369)
13:14:36  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
13:14:36  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:14:36  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:14:36  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:14:36  	at java.lang.Thread.run(Thread.java:748)
13:14:36  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to ocs-ci-jslave-3
13:14:36  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
13:14:36  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
13:14:36  		at hudson.remoting.Channel.call(Channel.java:998)
13:14:36  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
13:14:36  		at sun.reflect.GeneratedMethodAccessor863.invoke(Unknown Source)
13:14:36  		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:14:36  		at java.lang.reflect.Method.invoke(Method.java:498)
13:14:36  		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
13:14:36  		at com.sun.proxy.$Proxy93.execute(Unknown Source)
13:14:36  		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1219)
13:14:36  		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
13:14:36  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
13:14:36  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
13:14:36  		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
13:14:36  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
13:14:36  		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13:14:36  		... 4 more
```

**Comment by clacroix12** [comment]
Moving this to gitlab
