### ISSUE TITLE
"fio-1-build" not found in tier1 test suite for s390x

### ISSUE THREAD

**Issue by Sarah-Kriesch** [red-hat-storage/ocs-ci#4004]
I had a test run with OCP 4.7.1 and OCS 4.7.0 with the tier1 test suite.
It seems there are problems with gettig the fio image based on Fedora running on Z (s390x) in the test tests/e2e/registry/test_pod_from_registry.py::TestRegistryImage::test_run_pod_local_image.

The test is running in a timeout with the status Failed:
```
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc describe Pod fio-1-build.
E           Error is Error from server (NotFound): pods "fio-1-build" not found
```

Some more information of the test log:
15:06:18 - MainThread - ocs_ci.helpers.helpers - INFO - Running command oc -n namespace-test-ecb6440b59614d70b4971cdf4 --kubeconfig /root/ocp4-workdir/auth/kubeconfig new-build -D $'FROM quay.io/ocsci/fedora:latest
  RUN yum install -y fio
CMD tail -f /dev/null' --name=fio
15:06:21 - MainThread - ocs_ci.helpers.helpers - INFO - --> Found container image 23e8b09 (4 months old) from quay.io for "quay.io/ocsci/fedora:latest"

    * An image stream tag will be created as "fedora:latest" that will track the source image
    * A Docker build using a predefined Dockerfile will be created
      * The resulting image will be pushed to image stream tag "fio:latest"
      * Every time "fedora:latest" changes a new build will be triggered

--> Creating resources with label build=fio ...
    imagestream.image.openshift.io "fedora" created
    imagestream.image.openshift.io "fio" created
    buildconfig.build.openshift.io "fio" created
--> Success

15:06:21 - MainThread - ocs_ci.ocs.ocp - INFO - Waiting for a resource(s) of kind Pod identified by name 'fio-1-build' using selector None at column name STATUS to reach desired condition Completed
15:06:21 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get Pod fio-1-build -o yaml
15:06:21 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (NotFound): pods "fio-1-build" not found

15:06:21 - MainThread - ocs_ci.ocs.ocp - WARNING - Failed to get resource: fio-1-build of kind: Pod, selector: None, Error: Error during execution of command: oc get Pod fio-1-build -o yaml.
Error is Error from server (NotFound): pods "fio-1-build" not found

15:06:21 - MainThread - ocs_ci.ocs.ocp - WARNING - Number of attempts to get resource reached!
15:06:21 - MainThread - ocs_ci.utility.utils - ERROR - Exception raised during iteration: Error during execution of command: oc get Pod fio-1-build -o yaml.
Error is Error from server (NotFound): pods "fio-1-build" not found
Traceback (most recent call last):
  File "/root/ocs-ci/ocs_ci/utility/utils.py", line 921, in __iter__
    yield self.func(*self.func_args, **self.func_kwargs)
  File "/root/ocs-ci/ocs_ci/ocs/ocp.py", line 232, in get
    return self.exec_oc_cmd(command)
  File "/root/ocs-ci/ocs_ci/ocs/ocp.py", line 144, in exec_oc_cmd
    **kwargs,
  File "/root/ocs-ci/ocs_ci/utility/utils.py", line 453, in run_cmd
    completed_process = exec_cmd(cmd, secrets, timeout, ignore_error, **kwargs)
  File "/root/ocs-ci/ocs_ci/utility/utils.py", line 508, in exec_cmd
    f"Error during execution of command: {masked_cmd}."
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc get Pod fio-1-build -o yaml.
Error is Error from server (NotFound): pods "fio-1-build" not found

**Comment by Sarah-Kriesch** [comment]
The solution would be to replace the used image with quay.io/multi-arch/cloud-bulldozer:fio .
