### ISSUE TITLE
oc get namespace -A -o yaml takes long time and error out saying "invalid character 'T' after top-level value"

### ISSUE THREAD

**Issue by hnallurv** [red-hat-storage/ocs-ci#411]
Following error message was seen when I ran my script (on my wip branch from forked repo created 4hrs back):

18:11:42 - Dummy-8 - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /home/hnallurv/OCS_cluster_dir/auth/kubeconfig get Namespace -A -o yaml

Traceback (most recent call last):
  File "/home/hnallurv/fork/ocs-ci/venv/lib/python3.7/site-packages/gevent/threadpool.py", line 281, in _worker
    value = func(*args, **kwargs)
  File "/home/hnallurv/fork/ocs-ci/ocs_ci/utility/environment_check.py", line 54, in assign_get_values
    env_status_dict[key] = kind.get(all_namespaces=True)['items']
  File "/home/hnallurv/fork/ocs-ci/ocs_ci/ocs/ocp.py", line 108, in get
    return self.exec_oc_cmd(command)
  File "/home/hnallurv/fork/ocs-ci/ocs_ci/ocs/ocp.py", line 70, in exec_oc_cmd
    out = run_cmd(cmd=oc_cmd)
  File "/home/hnallurv/fork/ocs-ci/ocs_ci/utility/utils.py", line 381, in run_cmd
    f"Error during execution of command: {cmd}."
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', '--kubeconfig', '/home/hnallurv/OCS_cluster_dir/auth/kubeconfig', 'get', 'Secret', '-A', '-o', 'yaml'].
Error is error: invalid character 'T' after top-level value

2019-07-16T12:48:54Z (<ThreadPool at 0x7f020d0b4710 0/1/8 hub=<Hub at 0x7f020d150608 thread_ident=0x139647103493952>>, <function assign_get_values at 0x7f020d1c5e18>) failed with CommandFailed
===========================
This error was seen consistently.
After the error message is printed, the script continues to run!

**Comment by vasukulkarni** [comment]
Closing stale issue.
