### ISSUE TITLE
Reportportal issue leads to unclear error and break whole test execution

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#4299]
In [this test run](https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/836/consoleFull), the test execution `run-ci` command failed with long unclear traceback, which is probably caused by Reportportal issue. If it will be possible, it would be better to handle such error and decide, if it is worth to just print meaningful warning and continue, or fail the execution with shorter and clean error message.

```
+ run-ci --color=yes tests/ -m tier2 -k '' --ocs-version 4.7 --ocp-version 4.7 '--ocsci-conf=~/current-cluster-dir/ocsci_conf.yaml' --ocsci-conf=conf/deployment/aws/ipi_3az_rhcos_3m_3w.yaml --collect-logs --collect-logs-on-success-run --cluster-name j010ai3c33-t2n --cluster-path /home/jenkins/current-cluster-dir/openshift-cluster-dir --junit-xml /home/jenkins/current-cluster-dir/logs/test_results_1621066916.xml -o junit_suite_name=j010ai3c33-t2n '--html=~/current-cluster-dir/logs/test_report_1621066916.html' --self-contained-html --bugzilla --email=ocs-ci@redhat.com --squad-analysis --reportportal
2021-05-15 09:28:00,992 - MainThread - ocs_ci.framework.pytest_customization.ocscilib - INFO - Dump of the consolidated config file is located here: /home/jenkins/current-cluster-dir/logs/run-1621070875-config.yaml
/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/ocs/amq.py:437: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if msg.find(substring) is -1:
Collecting Cluster versions
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/reportportal_client/service.py", line 67, in _get_json
INTERNALERROR>     return response.json()
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/requests/models.py", line 898, in json
INTERNALERROR>     return complexjson.loads(self.text, **kwargs)
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
INTERNALERROR>     return _default_decoder.decode(s)
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
INTERNALERROR>     obj, end = self.raw_decode(s)
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
INTERNALERROR>     return self.scan_once(s, idx=_w(s, idx).end())
INTERNALERROR> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/_pytest/main.py", line 195, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/src/pytest-reportportal/pytest_reportportal/plugin.py", line 45, in pytest_sessionstart
INTERNALERROR>     session.config.py_test_service.init_service(
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/src/pytest-reportportal/pytest_reportportal/service.py", line 114, in init_service
INTERNALERROR>     self.project_settings = self.RP.rp_client.get_project_settings()
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/reportportal_client/service.py", line 237, in get_project_settings
INTERNALERROR>     return _get_json(r)
INTERNALERROR>   File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/reportportal_client/service.py", line 71, in _get_json
INTERNALERROR>     raise ResponseError(
INTERNALERROR> reportportal_client.errors.ResponseError: Invalid response: Expecting value: line 1 column 1 (char 0): <!DOCTYPE html>
INTERNALERROR> <html lang="en">
INTERNALERROR> <head>
INTERNALERROR>     <meta charset="utf-8">
INTERNALERROR>     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
INTERNALERROR>     <meta name="viewport" content="initial-scale=1, maximum-scale=1">
INTERNALERROR> 
INTERNALERROR>     <meta name="description" content="">
INTERNALERROR>     <meta name="author" content="">
INTERNALERROR> 
INTERNALERROR>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
INTERNALERROR> 
INTERNALERROR>     <!-- Fav and touch icons -->
INTERNALERROR>     <link rel="apple-touch-icon-precomposed" sizes="144x144"
INTERNALERROR>         href="./img/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
INTERNALERROR>     <link rel="shortcut icon" href="./favicon.ico" type="image/x-icon">
INTERNALERROR> 
INTERNALERROR>     <title>Report Portal - Page 404</title>
INTERNALERROR> </head>
INTERNALERROR> <body>
INTERNALERROR>     <style type="text/css">
INTERNALERROR>         @font-face {
INTERNALERROR>             font-family: "OpenSansRegular";
INTERNALERROR>             /*src: local("OpenSansRegular");*/
INTERNALERROR>             src: local("☺");
INTERNALERROR>             src: url('compiled/fonts/font-OpenSansRegular/open-sans-regular.eot'),
INTERNALERROR>                  url('compiled/fonts/font-OpenSansRegular/open-sans-regular.eot?') format('eot'),
INTERNALERROR>                  url('compiled/fonts/font-OpenSansRegular/open-sans-regular.woff2') format('woff2'),
INTERNALERROR>                  url('compiled/fonts/font-OpenSansRegular/open-sans-regular.woff') format('woff'),
INTERNALERROR>                  url('compiled/fonts/font-OpenSansRegular/open-sans-regular.ttf') format('truetype'),
INTERNALERROR>                  url('compiled/fonts/font-OpenSansRegular/open-sans-regular.svg#OpenSansRegular') format('svg');
INTERNALERROR>             font-weight: 400;
INTERNALERROR>             font-style: normal;
INTERNALERROR>         }
INTERNALERROR>         *,
INTERNALERROR>         *:before,
INTERNALERROR>         *:after {
INTERNALERROR>             -webkit-box-sizing: border-box;
INTERNALERROR>             -moz-box-sizing: border-box;
INTERNALERROR>             box-sizing: border-box;
INTERNALERROR>         }
INTERNALERROR>         html,
INTERNALERROR>         body {
INTERNALERROR>             margin: 0;
INTERNALERROR>             padding: 0;
INTERNALERROR>             width: 100%;
INTERNALERROR>             height: 100%;
INTERNALERROR>             min-height: 100%;
INTERNALERROR>             min-width: 100px;
INTERNALERROR>         }
INTERNALERROR>         body {
INTERNALERROR>             font-size: 13px;
INTERNALERROR>             font-family: "OpenSansRegular", sans-serif;
INTERNALERROR>             min-width: 320px;
INTERNALERROR>             background:  #FBFFF1;
INTERNALERROR>         }
INTERNALERROR>         .content-err-wrapper {
INTERNALERROR>             position:relative;
INTERNALERROR>             width: 320px;
INTERNALERROR>             height: 320px;
INTERNALERROR>             top: 95px;
INTERNALERROR>             left: 50%;
INTERNALERROR>             margin-left: -160px;
INTERNALERROR>         }
INTERNALERROR>         .content-logotip {
INTERNALERROR>             position: absolute;
INTERNALERROR>             display: block;
INTERNALERROR>             z-index: 1;
INTERNALERROR>             top: 0;
INTERNALERROR>             left: 0;
INTERNALERROR>             width: 100%;
INTERNALERROR>             height: 60px;
INTERNALERROR>             background-color: #313131;
INTERNALERROR>         }
INTERNALERROR>         .content-logotip .logo {
INTERNALERROR>             position: absolute;
INTERNALERROR>             display: block;
INTERNALERROR>             z-index: 2;
INTERNALERROR>             top: 13px;
INTERNALERROR>             left: 22px;
INTERNALERROR>             width: 46px;
INTERNALERROR>             height: 39px;
INTERNALERROR>             background-color: #313131;
INTERNALERROR>             background-image: url("compiled/img/rp_logo.png");
INTERNALERROR>             background-repeat: no-repeat;
INTERNALERROR>             background-position: center center;
INTERNALERROR>         }
INTERNALERROR>         .content-left {
INTERNALERROR>             position: absolute;
INTERNALERROR>             display: none;
INTERNALERROR>             left: 0;
INTERNALERROR>             bottom: 0;
INTERNALERROR>             top: 0;
INTERNALERROR>             width: 90px;
INTERNALERROR>             background-color: #464547;
INTERNALERROR>         }
INTERNALERROR>         .content-err{
INTERNALERROR>             position: relative;
INTERNALERROR>             top: -320px;
INTERNALERROR>         }
INTERNALERROR>         .content-err-txt {
INTERNALERROR>             position: relative;
INTERNALERROR>             padding-top: 318px;
INTERNALERROR>         }
INTERNALERROR>         .content-err-txt p {
INTERNALERROR>             text-align: center;
INTERNALERROR>             margin-bottom: 20px;
INTERNALERROR>         }
INTERNALERROR>         .content-err-txt .content-err-greeting {
INTERNALERROR>             font-family: "OpenSansRegular", sans-serif;
INTERNALERROR>             font-size: 16px;
INTERNALERROR>             line-height: 16px;
INTERNALERROR>             font-weight: 600;
INTERNALERROR>             color: #464547;
INTERNALERROR>         }
INTERNALERROR>         .content-err::after{
INTERNALERROR>              background-repeat: no-repeat;
INTERNALERROR>              position: absolute;
INTERNALERROR>              top: 170px;
INTERNALERROR>              left: 50%;
INTERNALERROR>              margin-left: -152px;
INTERNALERROR>              content: "";
INTERNALERROR>              background-image: url('compiled/img/404/404.svg');
INTERNALERROR>              width: 294px;
INTERNALERROR>              height: 119px;
INTERNALERROR>              background-size: contain;
INTERNALERROR>          }
INTERNALERROR>         .content-action {
INTERNALERROR>             position: relative;
INTERNALERROR>             text-align: center;
INTERNALERROR>         }
INTERNALERROR>         .content-action a {
INTERNALERROR>             position: relative;
INTERNALERROR>             display: inline-block;
INTERNALERROR>             font-family: "OpenSansRegular", sans-serif;
INTERNALERROR>             font-size: 13px;
INTERNALERROR>             line-height: 13px;
INTERNALERROR>             font-weight: 400;
INTERNALERROR>             text-align: center;
INTERNALERROR>             color: #309cb2;
INTERNALERROR>             padding: 6px 22px;
INTERNALERROR>             background-color: #ffffff;
INTERNALERROR>             border: solid 1px #309cb2;
INTERNALERROR>             text-decoration: none;
INTERNALERROR>         }
INTERNALERROR>         .content-action a:hover {
INTERNALERROR>             color: #ffffff;
INTERNALERROR>             background-color: #39c2d7;
INTERNALERROR>             border-color: #39c2d7;
INTERNALERROR>             text-decoration: none;
INTERNALERROR>         }
INTERNALERROR>         .wrapper{
INTERNALERROR>             width: 100%;
INTERNALERROR>             height: 100%;
INTERNALERROR>             min-height: 520px;
INTERNALERROR>             overflow: hidden;
INTERNALERROR>         }
INTERNALERROR> 
INTERNALERROR>         .round{
INTERNALERROR>             border-radius: 50%;
INTERNALERROR>             opacity: 0.3;
INTERNALERROR>             position: absolute;
INTERNALERROR>             background: #A3C644;
INTERNALERROR>             top: 50%;
INTERNALERROR>             left: 50%;
INTERNALERROR>         }
INTERNALERROR>         .round-7{
INTERNALERROR>             width: 1780px;
INTERNALERROR>             height: 1780px;
INTERNALERROR>             margin-top: -890px;
INTERNALERROR>             margin-left: -890px;
INTERNALERROR>             box-shadow: rgba(255, 255, 255, 0.4) 0 0 13px;
INTERNALERROR>         }
INTERNALERROR>         .round-6{
INTERNALERROR>             width: 1500px;
INTERNALERROR>             height: 1500px;
INTERNALERROR>             margin-top: -750px;
INTERNALERROR>             margin-left: -750px;
INTERNALERROR>             box-shadow: rgba(255, 255, 255, 0.4) 0 0 11px;
INTERNALERROR>         }
INTERNALERROR>         .round-5{
INTERNALERROR>             width: 1250px;
INTERNALERROR>             height: 1250px;
INTERNALERROR>             margin-top: -625px;
INTERNALERROR>             margin-left: -625px;
INTERNALERROR>             box-shadow: rgba(255, 255, 255, 0.4) 0 0 9px;
INTERNALERROR>         }
INTERNALERROR>         .round-4{
INTERNALERROR>             width: 1008px;
INTERNALERROR>             height: 1008px;
INTERNALERROR>             margin-top: -504px;
INTERNALERROR>             margin-left: -504px;
INTERNALERROR>             box-shadow: rgba(255, 255, 255, 0.4) 0 0 7px;
INTERNALERROR>         }
INTERNALERROR>         .round-3{
INTERNALERROR>             width: 778px;
INTERNALERROR>             height: 778px;
INTERNALERROR>             margin-top: -389px;
INTERNALERROR>             margin-left: -389px;
INTERNALERROR>             box-shadow: rgba(255, 255, 255, 0.4) 0 0 5px;
INTERNALERROR>         }
INTERNALERROR>         .round-2{
INTERNALERROR>             width: 580px;
INTERNALERROR>             height: 580px;
INTERNALERROR>             margin-top: -290px;
INTERNALERROR>             margin-left: -290px;
INTERNALERROR>             box-shadow: rgba(255, 255, 255, 0.4) 0 0 3px;
INTERNALERROR>         }
INTERNALERROR>         .round-1{
INTERNALERROR>             width: 416px;
INTERNALERROR>             height: 416px;
INTERNALERROR>             margin-top: -208px;
INTERNALERROR>             margin-left: -208px;
INTERNALERROR>             box-shadow: rgba(255, 255, 255, 0.4) 0 0 2px;
INTERNALERROR>         }
INTERNALERROR>         .round-center {
INTERNALERROR>             position: absolute;
INTERNALERROR>             width: 320px;
INTERNALERROR>             height: 320px;
INTERNALERROR>         }
INTERNALERROR>         .red-planet div{
INTERNALERROR>             background-image: url('compiled/img/404/planet2.png');
INTERNALERROR>             width: 50px;
INTERNALERROR>             height: 45px;
INTERNALERROR>             position: absolute;
INTERNALERROR>             top: -20px;
INTERNALERROR>         }
INTERNALERROR>         .saturn div{
INTERNALERROR>             background-image: url('compiled/img/404/planet3.png');
INTERNALERROR>             width: 90px;
INTERNALERROR>             height: 60px;
INTERNALERROR>             position: absolute;
INTERNALERROR>             margin-left: -170px;
INTERNALERROR>             margin-top: 183px;
INTERNALERROR>         }
INTERNALERROR>         .orange-planet div{
INTERNALERROR>             background-image: url('compiled/img/404/planet1.png');
INTERNALERROR>             width: 100px;
INTERNALERROR>             height: 90px;
INTERNALERROR>             position: absolute;
INTERNALERROR>             right: -264px;
INTERNALERROR>             top: 193px;
INTERNALERROR>         }
INTERNALERROR>         .orbit-rotation{
INTERNALERROR>             animation: OrbitRotation 40s linear infinite;
INTERNALERROR>             transform-origin: center;
INTERNALERROR>         }
INTERNALERROR>         .rocket{
INTERNALERROR>             background-image: url('compiled/img/404/rocket 2.svg');
INTERNALERROR>             width: 70px;
INTERNALERROR>             height: 25px;
INTERNALERROR>             position: absolute;
INTERNALERROR>             left: -900px;
INTERNALERROR>             top: 400px;
INTERNALERROR>             animation: Rocket 8s ease-in infinite;
INTERNALERROR>         }
INTERNALERROR>         @keyframes Rocket {
INTERNALERROR>             0%{ opacity: 0;}
INTERNALERROR>             1% {opacity: 1;  transform:rotate(-35deg) translateX(0); }
INTERNALERROR>             99%{ opacity: 1; transform:rotate(-35deg) translateX(800px); }
INTERNALERROR>             100% {opacity: 0; transform:rotate(-35deg) translateX(800px);}
INTERNALERROR>         }
INTERNALERROR>         @keyframes Rocket-mobile {
INTERNALERROR>             0%{ opacity: 0;}
INTERNALERROR>             1% {opacity: 1;  transform: translateX(220px) scale(-1,1); }
INTERNALERROR>             99%{ opacity: 1; transform: translateX(-550px) scale(-1,1); }
INTERNALERROR>             100% {opacity: 0; transform: translateX(-550px) scale(-1,1);}
INTERNALERROR>         }
INTERNALERROR>         @keyframes OrbitRotation {
INTERNALERROR>             from{ transform: rotate(0deg) ; }
INTERNALERROR>             to{ transform: rotate(360deg) ; }
INTERNALERROR>         }
INTERNALERROR>         .self-rotation{
INTERNALERROR>             animation: SelfRotation 40s linear infinite;
INTERNALERROR>             transform-origin: center;
INTERNALERROR>         }
INTERNALERROR>         @keyframes SelfRotation {
INTERNALERROR>             from{ transform: rotate(0deg) ; }
INTERNALERROR>             to{ transform: rotate(-360deg) ; }
INTERNALERROR>         }
INTERNALERROR>         .bones{
INTERNALERROR>             background-image: url(compiled/img/404/bones.svg);
INTERNALERROR>             width: 210px;
INTERNALERROR>             height: 90px;
INTERNALERROR>             position: absolute;
INTERNALERROR>             right: -1070px;
INTERNALERROR>             top: -200px;
INTERNALERROR>             animation: Bones 17s linear infinite ;
INTERNALERROR>         }
INTERNALERROR>         @keyframes Bones{
INTERNALERROR>             0%{ opacity: 0; }
INTERNALERROR>             1% {opacity: 1;  transform:rotate(-35deg) translateX(0); }
INTERNALERROR>             50%{ opacity: 1; }
INTERNALERROR>             100% {opacity: 0; transform:rotate(-35deg) translateX(-2000px);}
INTERNALERROR>         }
INTERNALERROR>         .dog{
INTERNALERROR>             background-image: url(compiled/img/404/dog.svg);
INTERNALERROR>             width: 150px;
INTERNALERROR>             height: 120px;
INTERNALERROR>             position: absolute;
INTERNALERROR>             right: -1600px;
INTERNALERROR>             top:-600px;
INTERNALERROR>             animation: Dog 17s ease-in-out
INTERNALERROR>             infinite ;
INTERNALERROR>         }
INTERNALERROR>         @keyframes Dog{
INTERNALERROR>             0%{ opacity: 0; }
INTERNALERROR>             1% {opacity: 1;  transform:rotate(-35deg) translateX(0); }
INTERNALERROR>             50%{ opacity: 1; }
INTERNALERROR>             100% {opacity: 0; transform:rotate(-35deg) translateX(-2400px);}
INTERNALERROR>         }
INTERNALERROR>         .stars{
INTERNALERROR>             position: absolute;
INTERNALERROR>             left: 50%;
INTERNALERROR>         }
INTERNALERROR>         .layer-1{
INTERNALERROR>             top: -38px;
INTERNALERROR>             background-image: url(compiled/img/404/stars1.svg);
INTERNALERROR>             width: 1083px;
INTERNALERROR>             height: 488px;
INTERNALERROR>             margin-left: -543px;
INTERNALERROR>             animation: Stars 2s linear infinite;
INTERNALERROR>         }
INTERNALERROR>         .layer-2{
INTERNALERROR>             top: -22px;
INTERNALERROR>             background-image: url("compiled/img/404/stars2.svg");
INTERNALERROR>             width: 1155px;
INTERNALERROR>             height: 464px;
INTERNALERROR>             margin-left: -577px;
INTERNALERROR>             animation: Stars 3s ease-in infinite;
INTERNALERROR>         }
INTERNALERROR>         @keyframes Stars  {
INTERNALERROR>             0%{ opacity: 1;}
INTERNALERROR>             50% {opacity: 0.3;}
INTERNALERROR>             100% { opacity: 1;}
INTERNALERROR>         }
INTERNALERROR>         /* view max-width - 321px and min-width - 768px */
INTERNALERROR>         @media  (max-width: 768px) {
INTERNALERROR>             .content-err-txt {
INTERNALERROR>                 padding-top: 300px;
INTERNALERROR>             }
INTERNALERROR>         }
INTERNALERROR>         @media (max-width: 500px){
INTERNALERROR>             .round-1{
INTERNALERROR>                 width: 258px;
INTERNALERROR>                 height: 258px;
INTERNALERROR>                 margin-top: -129px;
INTERNALERROR>                 margin-left: -129px;
INTERNALERROR>             }
INTERNALERROR>             .round-2{
INTERNALERROR>                 width: 360px;
INTERNALERROR>                 height:  360px;
INTERNALERROR>                 margin-top: -180px;
INTERNALERROR>                 margin-left: -180px;
INTERNALERROR>             }
INTERNALERROR>             .round-3{
INTERNALERROR>                 width: 474px;
INTERNALERROR>                 height: 474px;
INTERNALERROR>                 margin-top: -237px;
INTERNALERROR>                 margin-left: -237px;
INTERNALERROR>             }
INTERNALERROR>             .round-4{
INTERNALERROR>                 width: 610px;
INTERNALERROR>                 height: 610px;
INTERNALERROR>                 margin-top: -305px;
INTERNALERROR>                 margin-left: -305px;
INTERNALERROR>             }
INTERNALERROR>             .content-err::after{
INTERNALERROR>                 width: 192px;
INTERNALERROR>                 height: 78px;
INTERNALERROR>                 margin-left: -91px;
INTERNALERROR>                 top: 176px;
INTERNALERROR>             }
INTERNALERROR>             .content-err-txt {
INTERNALERROR>                 padding-top: 280px;
INTERNALERROR>             }
INTERNALERROR>             .content-action a{
INTERNALERROR>                 padding: 8px 10px;
INTERNALERROR>                 left: 2px;
INTERNALERROR>                 top: 2px;
INTERNALERROR>             }
INTERNALERROR>             .red-planet div {
INTERNALERROR>                 top: 5px;
INTERNALERROR>                 left: 25px;
INTERNALERROR>                 width: 40px;
INTERNALERROR>                 height: 40px;
INTERNALERROR>                 background-size: cover;
INTERNALERROR>             }
INTERNALERROR>             .bones, .dog, .orange-planet, .saturn, .orange-planet div, .saturn div {
INTERNALERROR>                 animation: unset;
INTERNALERROR>                 display:none;
INTERNALERROR>             }
INTERNALERROR>             .content-err-txt .content-err-greeting{
INTERNALERROR>                 margin-bottom: 17px;
INTERNALERROR>             }
INTERNALERROR>             .rocket{
INTERNALERROR>                 top: 360px;
INTERNALERROR>                 transform: scale(-1,1);
INTERNALERROR>                 left: 220px;
INTERNALERROR>                 width: 60px;
INTERNALERROR>                 height: 20px;
INTERNALERROR>                 background-size: cover;
INTERNALERROR>                 animation: Rocket-mobile 6s ease-in infinite;
INTERNALERROR>             }
INTERNALERROR>             .layer-1 {
INTERNALERROR>                 top: -93px;
INTERNALERROR>                 background-image: url(compiled/img/404/Mobile_404_stars1.svg);
INTERNALERROR>             }
INTERNALERROR>             .stars{
INTERNALERROR>                 width: 320px;
INTERNALERROR>                 height: 568px;
INTERNALERROR>                 margin-left: 0;
INTERNALERROR>                 left: 0;
INTERNALERROR>             }
INTERNALERROR>             .layer-2 {
INTERNALERROR>                 top: -93px;
INTERNALERROR>                 background-image: url(compiled/img/404/Mobile_404_stars2.svg);
INTERNALERROR>             }
INTERNALERROR>             .content-logotip .logo{
INTERNALERROR>                 position: relative;
INTERNALERROR>                 background-image: url(compiled/img/404/mobile-logo.svg);
INTERNALERROR>                 margin: 0 auto;
INTERNALERROR>                 left: 0;
INTERNALERROR>                 width: 150px;
INTERNALERROR>                 top: 0;
INTERNALERROR>                 height: 60px;
INTERNALERROR>             }
INTERNALERROR>         }
INTERNALERROR> 
INTERNALERROR>         /*----------------------------------------------------------------*/
INTERNALERROR>     </style>
INTERNALERROR>     <div class="content-logotip">
INTERNALERROR>         <a href="/" class="logo"></a>
INTERNALERROR>     </div>
INTERNALERROR>     <div class="wrapper">
INTERNALERROR>         <div class="content-err-wrapper">
INTERNALERROR>             <div class="round round-7"></div>
INTERNALERROR>             <div class="round round-6"></div>
INTERNALERROR>             <div class="round round-5"></div>
INTERNALERROR>             <div class="round round-4"></div>
INTERNALERROR>             <div class="round round-3"></div>
INTERNALERROR>             <div class="round round-2"></div>
INTERNALERROR>             <div class="round round-1"></div>
INTERNALERROR>             <div class="stars layer-1"></div>
INTERNALERROR>             <div class="stars layer-2"></div>
INTERNALERROR>             <div class="orbit-rotation round-center red-planet">
INTERNALERROR>                 <div class="self-rotation"></div>
INTERNALERROR>             </div>
INTERNALERROR>             <div class="orbit-rotation round-center saturn">
INTERNALERROR>                 <div class="self-rotation"></div>
INTERNALERROR>             </div>
INTERNALERROR>             <div class="orbit-rotation round-center orange-planet">
INTERNALERROR>                 <div class="self-rotation"></div>
INTERNALERROR>             </div>
INTERNALERROR>             <div class="rocket"></div>
INTERNALERROR>             <div class="bones"></div>
INTERNALERROR>             <div class="dog"></div>
INTERNALERROR>         </div>
INTERNALERROR>         <!-- <div class="content-left"></div> -->
INTERNALERROR>         <div class="content-err">
INTERNALERROR>             <div class="content-err-txt">
INTERNALERROR>                 <p class="content-err-greeting">Oops. Looks like you have got lost.</p>
INTERNALERROR>                 <p>The page you are looking for does not exist.</p>
INTERNALERROR>             </div>
INTERNALERROR>             <div class="content-action">
INTERNALERROR>                 <a href="/" title="Get me out of Here">Get me out of Here</a>
INTERNALERROR>             </div>
INTERNALERROR>         </div>
INTERNALERROR>     </div>
INTERNALERROR> 
INTERNALERROR> 
INTERNALERROR> </body>
INTERNALERROR> </html>
```

**Comment by clacroix12** [comment]
I am seeing this issue in a recent execution (https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/1676//console), however it doesn't appear to be the cause of the execution failure. The reason for the execution failing is a vault command error, however this report portal failure is still reported in the "captured stderr setup." My initial thoughts are that this is being caused when the API is unreachable as we are getting a 404 back from the page.

I can't see the original linked issue anymore as I'm sure it's been deleted from jenkins by now. Based on this recent execution it seems like this isn't causing our executions to fail, at least not anymore. As we are looking to move away from the pytest agent and adopt rp_preproc for our move to v5 I don't think we will invest time into addressing this issue.

@petr-balogh @dahorak @vasukulkarni I believe we can close this out as "won't fix" but I'd like to know what you think.

**Comment by petr-balogh** [comment]
This can be closed as we moved to other approach.
