### ISSUE TITLE
teardown fails with getting ocp version

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#4450]
```
+ run-ci -m deployment --teardown --ocsci-conf=../ocs-ci-ocs.yaml --cluster-name=zcerza-ci-424 --cluster-path=../cluster --collect-logs
Unable to find the authentication configuration at /home/jenkins-build/workspace/ocs-ci/ocs-ci.git/data/auth.yaml, please refer to the getting started guide (https://ocs-ci.readthedocs.io/en/latest/docs/getting_started.html#authentication-config)
The kubeconfig file ../cluster/auth/kubeconfig doesn't exist!
2021-06-17 04:20:54,748 - MainThread - ocs_ci.framework.pytest_customization.ocscilib - INFO - Dump of the consolidated config file is located here: /home/jenkins-build/workspace/ocs-ci/logs/run-1623918052-config.yaml
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/venv/lib/python3.8/site-packages/_pytest/main.py", line 193, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 778, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/venv/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/venv/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/ocs_ci/framework/pytest_customization/ocscilib.py", line 298, in pytest_configure
INTERNALERROR>     set_report_portal_config(config)
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/ocs_ci/framework/pytest_customization/ocscilib.py", line 632, in set_report_portal_config
INTERNALERROR>     rp_tags.append(f"ocp_version:{get_ocp_version()}")
INTERNALERROR>   File "/home/jenkins-build/workspace/ocs-ci/ocs-ci.git/ocs_ci/utility/utils.py", line 1556, in get_ocp_version
INTERNALERROR>     raw_version = json.loads(run_cmd("oc version -o json"))["openshiftVersion"]
INTERNALERROR> KeyError: 'openshiftVersion'
Error when executing always post condition:
hudson.AbortException: script returned exit code 3
```

**Comment by petr-balogh** [comment]
I see there was not even kubeconfig:
```
../cluster/auth/kubeconfig doesn't exist!
```

So it makes sense that we fail in such case if there is no kubeconfig file no?

**Comment by vavuthu** [comment]
> I see there was not even kubeconfig:
> 
> ```
> ../cluster/auth/kubeconfig doesn't exist!
> ```
> 
> So it makes sense that we fail in such case if there is no kubeconfig file no?

cluster path is mentioned in the run.

reason why its failed is we are loaded rp settings which in turn needed ocp version. ( when we used skip_ocp_deployment enabled, we are getting OCP version from command ```oc version -o json``` ) 

We can avoid this by not loading rp settings if not used or user has to disable passing skip_ocp_deployment  so that it loads default ocp version

**Comment by vavuthu** [comment]
> I see there was not even kubeconfig:
> 
> ```
> ../cluster/auth/kubeconfig doesn't exist!
> ```
> 
> So it makes sense that we fail in such case if there is no kubeconfig file no?

not sure whats there in the cluster path. it will be mostly empty because deployment failed with prefix already exists
