### ISSUE TITLE
Prometheus API token expires after 40 minutes

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#4767]
Some tests start failing when they run for longer time and use Prometheus without renewing token.

**Comment by petr-balogh** [comment]
I think that I see the issue here:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/2271/console

```
2021-11-16 13:40:13  12:40:12 - Thread-1 - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - ERROR - For query '{'query': '(sum(rate(ceph_pool_wr_bytes[1m]) + rate(ceph_pool_rd_bytes[1m])))', 'time': '1637066412.255195'}' Prometheus returned a response which failed to be parsed.
2021-11-16 13:40:13  12:40:12 - Thread-1 - ocs_ci.utility.retry - WARNING - mapping values are not allowed here
2021-11-16 13:40:13    in "<byte string>", line 7, column 20:
2021-11-16 13:40:13              font-family: "Helvetica Neue", Helvetica, A ... 
2021-11-16 13:40:13                         ^, Retrying in 5 seconds...
```

@fbalak any update on fix for this? We don't have coverage for prometheus tests I think if we hit this issue.

**Comment by petr-balogh** [comment]
I see this issue is happening here again:
https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/2351/consoleFull

I think it should be high priority issue hence adding label for that.

**Comment by petr-balogh** [comment]
@fbalak hello,

I see that in this job in tier1 post upgrade the console output got flood by this:

```
2022-09-15 07:42:43  05:42:43 - Thread-1 - ocs_ci.utility.retry - WARNING  - mapping values are not allowed here
2022-09-15 07:42:43    in "<byte string>", line 9, column 18:
2022-09-15 07:42:43            font-family: "Open Sans";
2022-09-15 07:42:43                       ^, Retrying in 5 seconds...
2022-09-15 07:42:48  05:42:48 - Thread-1 - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - ERROR  - For query '{'query': '(sum(rate(ceph_pool_wr_bytes[1m]) + rate(ceph_pool_rd_bytes[1m])))', 'time': '1663220568.261805'}' Prometheus returned a response which failed to be parsed.
2022-09-15 07:42:48  05:42:48 - Thread-1 - ocs_ci.utility.retry - WARNING  - mapping values are not allowed here
2022-09-15 07:42:48    in "<byte string>", line 9, column 18:
2022-09-15 07:42:48            font-family: "Open Sans";
2022-09-15 07:42:48                       ^, Retrying in 5 seconds...
2022-09-15 07:42:53  05:42:53 - Thread-1 - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - ERROR  - For query '{'query': '(sum(rate(ceph_pool_wr_bytes[1m]) + rate(ceph_pool_rd_bytes[1m])))', 'time': '1663220573.455847'}' Prometheus returned a response which failed to be parsed.
2022-09-15 07:42:53  05:42:53 - Thread-1 - ocs_ci.utility.retry - WARNING  - mapping values are not allowed here
2022-09-15 07:42:53    in "<byte string>", line 9, column 18:
2022-09-15 07:42:53            font-family: "Open Sans";
2022-09-15 07:42:53                       ^, Retrying in 5 seconds...
2022-09-15 07:42:59  05:42:58 - Thread-1 - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - ERROR  - For query '{'query': '(sum(rate(ceph_pool_wr_bytes[1m]) + rate(ceph_pool_rd_bytes[1m])))', 'time': '1663220578.605092'}' Prometheus returned a response which failed to be parsed.
2022-09-15 07:42:59  05:42:58 - Thread-1 - ocs_ci.utility.retry - WARNING  - mapping values are not allowed here
2022-09-15 07:42:59    in "<byte string>", line 9, column 18:
```


Then the process got killed:
```
 11:13:05 - Thread-1 - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - ERROR  - content is not a dict, but <class 'str'>
2022-09-15 13:14:04  /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci@tmp/durable-2baf5a0b/script.sh: line 4: 93895 Killed                  run-ci --color=yes tests/ -m 'tier1 or tier_after_upgrade' -k '' --ocs-version 4.7 --ocs-registry-image quay.io/rhceph-dev/ocs-registry:4.7.13-266.ci --ocp-version 4.8 --ocsci-conf=~/current-cluster-dir/ocsci_conf.yaml --ocsci-conf=conf/deployment/aws/ipi_3az_rhcos_3m_3w.yaml --ocsci-conf=conf/upgrade/upgrade_3m_3w.yaml --collect-logs --collect-logs-on-success-run --cluster-name j-135ai3c33-uo --cluster-path ~/current-cluster-dir/openshift-cluster-dir --junit-xml ~/current-cluster-dir/logs/test_results_1663065498.xml -o junit_suite_name=testsuite --html=~/current-cluster-dir/logs/test_report_1663065498.html --self-contained-html --bugzilla --email=ocs-ci@redhat.com --squad-analysis --io-in-bg --log-cluster-utilization
```

Probably because it run OOM .

Happened in OCP upgrade job:
qe-trigger-aws-ipi-3az-rhcos-3m-3w-upgrade-ocp: https://url.corp.redhat.com/bb84f7d

From OCP 4.7 to 4.8

Full console output of job is here:
https://url.corp.redhat.com/3a158af

**Comment by petr-balogh** [comment]
I think the same happened in upgrade run to 4.13.5 here:
https://url.corp.redhat.com/fc7c32c

After discussion with Elad, he pointed out it might be related to this BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2238400

@fbalak can you please confirm ?

```
2023-11-22 09:34:54  08:34:54 - Thread-2 - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - ERROR  - For query '{'query': '(sum(rate(ceph_pool_wr_bytes[1m]) + rate(ceph_pool_rd_bytes[1m])))', 'time': '1700642094.268724'}' Prometheus returned a response which failed to be parsed.
2023-11-22 09:34:54  08:34:54 - Thread-2 - ocs_ci.utility.retry - WARNING  - mapping values are not allowed here
2023-11-22 09:34:54    in "<byte string>", line 9, column 18:
2023-11-22 09:34:54            font-family: "Open Sans";
2023-11-22 09:34:54                       ^, Retrying in 5 seconds...
2023-11-22 09:35:01  08:34:59 - Thread-2 - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - ERROR  - For query '{'query': '(sum(rate(ceph_pool_wr_bytes[1m]) + rate(ceph_pool_rd_bytes[1m])))', 'time': '1700642099.528204'}' Prometheus returned a response which failed to be parsed.
2023-11-22 09:35:01  08:34:59 - Thread-2 - ocs_ci.utility.retry - WARNING  - mapping values are not allowed here
2023-11-22 09:35:01    in "<byte string>", line 9, column 18:
2023-11-22 09:35:01            font-family: "Open Sans";
2023-11-22 09:35:01                       ^, Retrying in 5 seconds...
2023-11-22 09:35:05  08:35:05 - Thread-2 - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - ERROR  - For query '{'query': '(sum(rate(ceph_pool_wr_bytes[1m]) + rate(ceph_pool_rd_bytes[1m])))', 'time': '1700642104.7971'}' Prometheus returned a response which failed to be parsed.
2023-11-22 09:35:05  08:35:05 - Thread-2 - ocs_ci.utility.retry - WARNING  - mapping values are not allowed here
2023-11-22 09:35:05    in "<byte string>", line 9, column 18:
2023-11-22 09:35:05            font-family: "Open Sans";
2023-11-22 09:35:05                       ^, Retrying in 5 seconds...
```

**Comment by petr-balogh** [comment]
It's seen in 4.14 execution here:
```
2023-11-29 15:48:14  Traceback (most recent call last):
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py", line 513, in query
2023-11-29 15:48:14      content = yaml.safe_load(resp.content)
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/__init__.py", line 125, in safe_load
2023-11-29 15:48:14      return load(stream, SafeLoader)
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/__init__.py", line 81, in load
2023-11-29 15:48:14      return loader.get_single_data()
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
2023-11-29 15:48:14      node = self.get_single_node()
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
2023-11-29 15:48:14      document = self.compose_document()
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/composer.py", line 58, in compose_document
2023-11-29 15:48:14      self.get_event()
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/parser.py", line 118, in get_event
2023-11-29 15:48:14      self.current_event = self.state()
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/parser.py", line 193, in parse_document_end
2023-11-29 15:48:14      token = self.peek_token()
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/scanner.py", line 129, in peek_token
2023-11-29 15:48:14      self.fetch_more_tokens()
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
2023-11-29 15:48:14      return self.fetch_value()
2023-11-29 15:48:14    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/lib64/python3.8/site-packages/yaml/scanner.py", line 577, in fetch_value
2023-11-29 15:48:14      raise ScannerError(None, None,
2023-11-29 15:48:14  yaml.scanner.ScannerError: mapping values are not allowed here
2023-11-29 15:48:14    in "<byte string>", line 9, column 18:
2023-11-29 15:48:14            font-family: "Open Sans";
2023-11-29 15:48:14                       ^
```
https://url.corp.redhat.com/2765f00

Not sure if it will get fully fixed by cherry-pick of:
https://github.com/red-hat-storage/ocs-ci/pull/8915/files#diff-4886a6bf7981d26580d4266b542c4ca21982217555b3919fd2432b43ba9dd066
@fbalak can you please provide input here?

@ebenahar 

Filip pointed out that before this error the IO in bg issue causing this:

```
2023-11-27 20:23:17  19:23:17 - Thread-2 - ocs_ci.ocs.cluster_load - WARNING  - 
2023-11-27 20:23:17  =================================================================================================================================================
2023-11-27 20:23:17  Latency is too high - 3797.39 ms. Dropping the background load. Once the latency drops back to normal, the background load will be increased back
2023-11-27 20:23:17  =================================================================================================================================================
2023-11-27 20:23:17  19:23:17 - Thread-2 - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-38a3f delete Deployment pod-test-rbd-81034146223d4c64b1c5584019e
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n bg-fio-load-38a3f get Deployment pod-test-rbd-81034146223d4c64b1c5584019e -n bg-fio-load-38a3f -o yaml
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.utility.utils - WARNING  - Command stderr: Error from server (NotFound): deployments.apps "pod-test-rbd-81034146223d4c64b1c5584019e" not found
2023-11-27 20:23:18  
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.ocs.ocp - WARNING  - Failed to get resource: pod-test-rbd-81034146223d4c64b1c5584019e of kind: Deployment, selector: None, Error: Error during execution of command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n bg-fio-load-38a3f get Deployment pod-test-rbd-81034146223d4c64b1c5584019e -n bg-fio-load-38a3f -o yaml.
2023-11-27 20:23:18  Error is Error from server (NotFound): deployments.apps "pod-test-rbd-81034146223d4c64b1c5584019e" not found
2023-11-27 20:23:18  
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.ocs.ocp - WARNING  - Number of attempts to get resource reached!
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.ocs.ocp - INFO  - Deployment pod-test-rbd-81034146223d4c64b1c5584019e got deleted successfully
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-38a3f delete PersistentVolumeClaim pvc-test-a0e560c8aaa543d8936806ee09064b7
2023-11-27 20:23:19  19:23:18 - Thread-2 - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n bg-fio-load-38a3f get PersistentVolumeClaim pvc-test-a0e560c8aaa543d8936806ee09064b7 -n bg-fio-load-38a3f -o yaml
2023-11-27 20:23:19  19:23:19 - Thread-2 - ocs_ci.utility.utils - WARNING  - Command stderr: Error from server (NotFound): persistentvolumeclaims "pvc-test-a0e560c8aaa543d8936806ee09064b7" not found
2023-11-27 20:23:19  
2023-11-27 20:23:17  19:23:17 - Thread-2 - ocs_ci.ocs.cluster_load - WARNING  - 
2023-11-27 20:23:17  =================================================================================================================================================
2023-11-27 20:23:17  Latency is too high - 3797.39 ms. Dropping the background load. Once the latency drops back to normal, the background load will be increased back
2023-11-27 20:23:17
=================================================================================================================================================
2023-11-27 20:23:17  19:23:17 - Thread-2 - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-38a3f delete Deployment pod-test-rbd-81034146223d4c64b1c5584019e
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n bg-fio-load-38a3f get Deployment pod-test-rbd-81034146223d4c64b1c5584019e -n bg-fio-load-38a3f -o yaml
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.utility.utils - WARNING  - Command stderr: Error from server (NotFound): deployments.apps "pod-test-rbd-81034146223d4c64b1c5584019e" not found
2023-11-27 20:23:18  
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.ocs.ocp - WARNING  - Failed to get resource: pod-test-rbd-81034146223d4c64b1c5584019e of kind: Deployment, selector: None, Error: Error during execution of command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n bg-fio-load-38a3f get Deployment pod-test-rbd-81034146223d4c64b1c5584019e -n bg-fio-load-38a3f -o yaml.
2023-11-27 20:23:18  Error is Error from server (NotFound): deployments.apps "pod-test-rbd-81034146223d4c64b1c5584019e" not found
2023-11-27 20:23:18  
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.ocs.ocp - WARNING  - Number of attempts to get resource reached!
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.ocs.ocp - INFO  - Deployment pod-test-rbd-81034146223d4c64b1c5584019e got deleted successfully
2023-11-27 20:23:18  19:23:18 - Thread-2 - ocs_ci.utility.utils - INFO  - Executing command: oc -n bg-fio-load-38a3f delete PersistentVolumeClaim pvc-test-a0e560c8aaa543d8936806ee09064b7
2023-11-27 20:23:19  19:23:18 - Thread-2 - ocs_ci.utility.utils - INFO  - Executing command: oc --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig -n bg-fio-load-38a3f get PersistentVolumeClaim pvc-test-a0e560c8aaa543d8936806ee09064b7 -n bg-fio-load-38a3f -o yaml
2023-11-27 20:23:19  19:23:19 - Thread-2 - ocs_ci.utility.utils - WARNING  - Command stderr: Error from server (NotFound): persistentvolumeclaims "pvc-test-a0e560c8aaa543d8936806ee09064b7" not found
2023-11-27 20:23:19  
2023-11-27 20:45:03    File "/usr/lib64/python3.8/logging/__init__.py", line 1069, in flush
2023-11-27 20:45:03      self.stream.flush()
2023-11-27 20:45:03  BrokenPipeError: [Errno 108] Cannot send after transport endpoint shutdown
2023-11-27 20:45:03  Call stack:
2023-11-27 20:45:03    File "/usr/lib64/python3.8/threading.py", line 890, in _bootstrap
2023-11-27 20:45:03      self._bootstrap_inner()
2023-11-27 20:45:03    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
2023-11-27 20:45:03      self.run()
2023-11-27 20:45:03    File "/usr/lib64/python3.8/threading.py", line 870, in run
2023-11-27 20:45:03      self._target(*self._args, **self._kwargs)
2023-11-27 20:45:03    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/tests/conftest.py", line 1864, in watch_load
2023-11-27 20:45:03      cl_load_obj.adjust_load_if_needed()
2023-11-27 20:45:03    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/ocs/cluster_load.py", line 433, in adjust_load_if_needed
2023-11-27 20:45:03      latency = self.calc_trim_metric_mean(constants.LATENCY_QUERY, mute_logs=True)
2023-11-27 20:45:03    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/ocs/cluster_load.py", line 376, in calc_trim_metric_mean
2023-11-27 20:45:03      vals.append(round(self.get_query(metric, mute_logs), 5))
2023-11-27 20:45:03    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/retry.py", line 31, in f_retry
2023-11-27 20:45:03      return f(*args, **kwargs)
2023-11-27 20:45:03    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/ocs/cluster_load.py", line 356, in get_query
2023-11-27 20:45:03      self.prometheus_api.query(
2023-11-27 20:45:03    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py", line 511, in query
2023-11-27 20:45:03      resp = self.get("query", payload=query_payload)
2023-11-27 20:45:03    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py", line 428, in get
2023-11-27 20:45:03      logger.debug(f"GET {self._endpoint + pattern}")
2023-11-27 20:45:03  Message: 'GET https://prometheus-k8s-openshift-monitoring.apps.j-336ai3c333-t1.qe.rh-ocs.com/api/v1/query'
2023-11-27 20:45:03  Arguments: ()
2023-11-27 20:45:03  --- Logging error ---
2023-11-27 20:45:03  Traceback (most recent call last):
2023-11-27 20:45:03    File "/usr/lib64/python3.8/logging/__init__.py", line 1089, in emit
```

What options do we have here to prevent such issues?

**Comment by ebenahar** [comment]
It's probably same as https://bugzilla.redhat.com/show_bug.cgi?id=2238400 and it is supposed to be fixed with ODF 4.14.

@fbalak @DanielOsypenko can you confirm it's the same?

**Comment by petr-balogh** [comment]
```
2023-12-06 09:10:59  08:10:58 - MainThread - /home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/prometheus.py - WARNING  - There was an error in response: <html>
2023-12-06 09:10:59    <head>
2023-12-06 09:10:59      <meta name="viewport" content="width=device-width, initial-scale=1">
2023-12-06 09:10:59  
2023-12-06 09:10:59      <style type="text/css">
2023-12-06 09:10:59        body {
2023-12-06 09:10:59          font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
2023-12-06 09:10:59          line-height: 1.66666667;
2023-12-06 09:10:59          font-size: 16px;
2023-12-06 09:10:59          color: #333;
2023-12-06 09:10:59          background-color: #fff;
2023-12-06 09:10:59          margin: 2em 1em;
2023-12-06 09:10:59        }
```
https://url.corp.redhat.com/0b2678d

@DanielOsypenko  can you please take a look?

**Comment by fbalak** [comment]
Issues during upgrade happened because prometheus endpoint was unavailable during node drain, not due to API token expiration.
