### ISSUE TITLE
Error ModuleNotFoundError: No module named 'hcl2'

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#5114]
Getting this error while running test case. run-ci command fails with this error.
```
Traceback (most recent call last):
  File "/home/jijoy/.local/bin/run-ci", line 33, in <module>
    sys.exit(load_entry_point('ocs-ci', 'console_scripts', 'run-ci')())
  File "/home/jijoy/.local/bin/run-ci", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jijoy/ocs-ci/ocs_ci/framework/main.py", line 13, in <module>
    from ocs_ci.utility import utils
  File "/home/jijoy/ocs-ci/ocs_ci/utility/utils.py", line 22, in <module>
    import hcl2
ModuleNotFoundError: No module named 'hcl2'
```

**Comment by jilju** [comment]
python-hcl2 is already installed
```
Requirement already satisfied: python-hcl2==3.0.1 in /home/jijoy/ocs-monkey/venv/lib/python3.9/site-packages (from ocs-ci==4.6.0->-r requirements.txt (line 2)) (3.0.1)```

**Comment by jilju** [comment]
Using Python 3.9.7

**Comment by vavuthu** [comment]
Could you give the o/p of ```$ pip freeze | grep -i hcl```

**Comment by jilju** [comment]
> Could you give the o/p of `$ pip freeze | grep -i hcl`


$ pip freeze | grep -i hcl
python-hcl2==3.0.1

**Comment by jilju** [comment]
Force reinstall the requirements worked. Closing the issue.
