### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#5125]
I started ocs-ci managed deployment with the following configuration:

- ocs-ci tag stable-ocs-4.9-202111171517 (commit 0f1c62cb)
- `--ocsci-conf=conf/ocsci/custom-ingress-ssl-certificate.yaml`
- `--ocsci-conf=conf/ocsci/skip_ocs_deploy.yam`
- `--ocp-version 4.8`

And noticed the following traceback in the logs:

```
16:53:57 - MainThread - ocs_ci.utility.utils - INFO - testrun_name: OCS4-8-Downstream-OCP4-8-VSPHERE-UPI-3AZ-RHCOS-LSO-3M-6W-deployment
16:53:57 - MainThread - ocs_ci.utility.utils - INFO - Executing command: ['oc', 'login', '-u', 'kubeadmin', '-p', '*****']
16:54:00 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: error: x509: certificate signed by unknown authority

16:54:00 - MainThread - tests.conftest - ERROR - There was a problem with connecting to Prometheus
Traceback (most recent call last):
  File "/home/ocsqe/projects/ocs-ci-deploy/tests/conftest.py", line 3037, in log_alerts
    prometheus = PrometheusAPI()
  File "/home/ocsqe/projects/ocs-ci-deploy/ocs_ci/utility/prometheus.py", line 318, in __init__
    self.refresh_connection()
  File "/home/ocsqe/projects/ocs-ci-deploy/ocs_ci/utility/prometheus.py", line 332, in refresh_connection
    assert ocp.login(self._user, self._password), "Login to OCP failed"
  File "/home/ocsqe/projects/ocs-ci-deploy/ocs_ci/ocs/ocp.py", line 452, in login
    status = exec_cmd(command, secrets=[password])
  File "/home/ocsqe/projects/ocs-ci-deploy/ocs_ci/utility/utils.py", line 511, in exec_cmd
    raise CommandFailed(
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: ['oc', 'login', '-u', 'kubeadmin', '-p', '*****'].
Error is error: x509: certificate signed by unknown authority

16:54:00 - MainThread - tests.conftest - ERROR - There was a problem with collecting alerts for analysis
Traceback (most recent call last):
  File "/home/ocsqe/projects/ocs-ci-deploy/tests/conftest.py", line 3043, in _collect_alerts
    alerts_response = prometheus.get(
AttributeError: 'NoneType' object has no attribute 'get'
```

There seems to be no problem with the deployed cluster.

Does it mean that there is some pending work to integrate our QE CA with the test code?

**Comment by dahorak** [comment]
@mbukatov wasn't this related to the leftover certificates from previous run (for different cluster)?

**Comment by mbukatov** [comment]
Right, I discussed this with Daniel offline. When one uses `custom-ingress-ssl-certificate.yaml`, it's important to specify `ingress_ssl_cert:` and `ingress_ssl_key` so that these are unique to each cluster, eg. insider cluster dir. Jenkis job is out of scope of this issue.
