### ISSUE TITLE
  File "/Users/vasukulkarni/ocs/ocs-ci/utility/utils.py", line 690, in destroy_cluster

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#53]
Handle fresh install case and set the dir probably in ocp_install ?

```

INFO:test_ocs_basic_install:HEALTH_OK, install successful.
2019-05-16 13:26:01,785 - test_ocs_basic_install - INFO - HEALTH_OK, install successful.
DEBUG:ocsci.framework:Test case info:
{'abort_on_fail': True,
 'desc': 'Minimal installation of OCS',
 'destroy_cluster': False,
 'duration': 2624.847946166992,
 'end': 1558038361.7858372,
 'file': 'test_ocs_basic_install.py',
 'log_link': 'http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1558035736932/install_OCS_0.log',
 'name': 'install OCS',
 'polarion_id': None,
 'post_results': False,
 'rp_service': None,
 'start': 1558035736.937891,
 'status': <TestStatus.PASSED: 0>,
 'suite_name': 'ocs_basic_install',
 'test_kwargs': {'config': {}, 'test_data': {'no-destroy': False}},
 'test_mod': <module 'test_ocs_basic_install' from '/Users/vasukulkarni/ocs/ocs-ci/tests/test_ocs_basic_install.py'>,
 'unique_name': 'install_OCS_0'}
INFO:utility.utils:Test logfile: /tmp/cephci-run-1558035736932/destroy_OCS_cluster_0.log
2019-05-16 13:26:01,787 - utility.utils - INFO - Test logfile: /tmp/cephci-run-1558035736932/destroy_OCS_cluster_0.log
INFO:utility.utils:Completed log configuration
2019-05-16 13:26:01,787 - utility.utils - INFO - Completed log configuration
INFO:ocsci.framework:Executing test case: destroy_OCS_cluster_0
2019-05-16 13:26:01,790 - ocsci.framework - INFO - Executing test case: destroy_OCS_cluster_0
INFO:test_destroy_cluster:Running OCS cluster destroy
2019-05-16 13:26:01,790 - test_destroy_cluster - INFO - Running OCS cluster destroy
ERROR:utility.utils:Traceback (most recent call last):
  File "/Users/vasukulkarni/ocs/ocs-ci/utility/utils.py", line 690, in destroy_cluster
    cluster_path = os.path.normpath(cluster_path)
  File "/Users/vasukulkarni/anaconda3/lib/python3.7/posixpath.py", line 333, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

2019-05-16 13:26:01,793 - utility.utils - ERROR - Traceback (most recent call last):
  File "/Users/vasukulkarni/ocs/ocs-ci/utility/utils.py", line 690, in destroy_cluster
    cluster_path = os.path.normpath(cluster_path)
  File "/Users/vasukulkarni/anaconda3/lib/python3.7/posixpath.py", line 333, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by petr-balogh** [comment]
This was case of old runner right? Or is it still valid for pytest execution?

**Comment by gklein** [comment]
Never saw this on recent deployment/teardown cycles. Is this still an issue or can we close it?
