### ISSUE TITLE
black checks are failing

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#5641]
```
  black run-test-pre: PYTHONHASHSEED='1981901166'
  black run-test: commands[0] | black . --check
  Traceback (most recent call last):
    File "/home/runner/work/ocs-ci/ocs-ci/.tox/black/bin/black", line 8, in <module>
      sys.exit(patched_main())
    File "/home/runner/work/ocs-ci/ocs-ci/.tox/black/lib/python3.9/site-packages/black/__init__.py", line 1322, in patched_main
      patch_click()
    File "/home/runner/work/ocs-ci/ocs-ci/.tox/black/lib/python3.9/site-packages/black/__init__.py", line 1308, in patch_click
      from click import _unicodefun
  ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/work/ocs-ci/ocs-ci/.tox/black/lib/python3.9/site-packages/click/__init__.py)
  Error: ERROR: InvocationError for command /home/runner/work/ocs-ci/ocs-ci/.tox/black/bin/black . --check (exited with code 1)
```

link: https://github.com/red-hat-storage/ocs-ci/runs/5732105902?check_suite_focus=true

**Comment by vavuthu** [comment]
click 8.1.0  which was released yesterday ( Mar 28, 2022 ) is breaking older releases of black version. Either we need to update black to 22.3.0 or pin to use older version of click
