### ISSUE TITLE
run-ci fails due to pkg_resources.ContextualVersionConflict

### ISSUE THREAD

**Issue by fbalak** [red-hat-storage/ocs-ci#5957]
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/13054/console

```
2022-05-28 09:39:16  + run-ci --color=yes ./tests/ -m deployment --ocs-version 4.10 --ocp-version 4.10 --osd-size 4096 --ocsci-conf=/tmp/3HY6ER33EU19 '--ocsci-conf=~/current-cluster-dir/ocsci_conf.yaml' --ocsci-conf=conf/deployment/rosa/managed_3az_provider_qe_3m_3w_m54x.yaml '--ocsci-conf=~/current-cluster-dir/ocsci_custom_conf.yaml' --cluster-name fbalak-m28p --cluster-path /home/jenkins/current-cluster-dir/openshift-cluster-dir --junit-xml /home/jenkins/current-cluster-dir/logs/deployment_results_1653723048.xml -o junit_suite_name=testsuite '--html=~/current-cluster-dir/logs/deployment_report_1653723048.html' --self-contained-html --deploy --live-deploy
2022-05-28 09:39:16  + set +x
2022-05-28 09:39:17  Traceback (most recent call last):
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
2022-05-28 09:39:17      ws.require(__requires__)
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
2022-05-28 09:39:17      needed = self.resolve(parse_requirements(requirements))
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
2022-05-28 09:39:17      raise VersionConflict(dist, req).with_context(dependent_req)
2022-05-28 09:39:17  pkg_resources.ContextualVersionConflict: (protobuf 4.21.1 (/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.8/site-packages), Requirement.parse('protobuf<4.0.0dev,>=3.12.0; python_version > "3"'), {'google-api-core'})
2022-05-28 09:39:17  
2022-05-28 09:39:17  During handling of the above exception, another exception occurred:
2022-05-28 09:39:17  
2022-05-28 09:39:17  Traceback (most recent call last):
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/bin/run-ci", line 6, in <module>
2022-05-28 09:39:17      from pkg_resources import load_entry_point
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
2022-05-28 09:39:17      def _initialize_master_working_set():
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
2022-05-28 09:39:17      f(*args, **kwargs)
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
2022-05-28 09:39:17      working_set = WorkingSet._build_master()
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
2022-05-28 09:39:17      return cls._build_from_requirements(__requires__)
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
2022-05-28 09:39:17      dists = ws.resolve(reqs, Environment())
2022-05-28 09:39:17    File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib64/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
2022-05-28 09:39:17      raise VersionConflict(dist, req).with_context(dependent_req)
2022-05-28 09:39:17  pkg_resources.ContextualVersionConflict: (protobuf 4.21.1 (/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/venv/lib/python3.8/site-packages), Requirement.parse('protobuf<4.0.0dev,>=3.12.0; python_version > "3"'), {'google-api-core'})
```

**Comment by fbalak** [comment]
Fixed by https://github.com/red-hat-storage/ocs-ci/issues/5960
