### ISSUE TITLE
Package installation failing 

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#6134]
The command ```pip install -r requirements.txt``` is failing while collecting scipy. 

```
Collecting scipy==1.6.0
  Using cached scipy-1.6.0.tar.gz (27.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [127 lines of output]
      setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-47gwd2dy'), proceeding with generating Cython sources and expanding templates
        warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
      setup.py:563: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.core import setup
      Running from SciPy source directory.
      INFO: lapack_opt_info:
      INFO: lapack_armpl_info:
      INFO: customize UnixCCompiler
      INFO:   libraries armpl_lp64_mp not found in ['/home/jijoy/ocs-ci/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_mkl_info:
      INFO:   libraries mkl_rt not found in ['/home/jijoy/ocs-ci/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_lapack_info:
      INFO:   libraries openblas not found in ['/home/jijoy/ocs-ci/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: openblas_clapack_info:
      INFO:   libraries openblas,lapack not found in ['/home/jijoy/ocs-ci/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: flame_info:
      INFO:   libraries flame not found in ['/home/jijoy/ocs-ci/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      INFO:   NOT AVAILABLE
      INFO:
      INFO: accelerate_info:
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries tatlas,tatlas not found in /home/jijoy/ocs-ci/venv/lib
      INFO:   libraries tatlas,tatlas not found in /usr/local/lib64
      INFO:   libraries tatlas,tatlas not found in /usr/local/lib
      INFO:   libraries tatlas,tatlas not found in /usr/lib64
      INFO:   libraries tatlas,tatlas not found in /usr/lib
      INFO:   libraries tatlas,tatlas not found in /usr/lib/
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_3_10_info:
      INFO:   libraries satlas,satlas not found in /home/jijoy/ocs-ci/venv/lib
      INFO:   libraries satlas,satlas not found in /usr/local/lib64
      INFO:   libraries satlas,satlas not found in /usr/local/lib
      INFO:   libraries satlas,satlas not found in /usr/lib64
      INFO:   libraries satlas,satlas not found in /usr/lib
      INFO:   libraries satlas,satlas not found in /usr/lib/
      INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_threads_info:
      INFO: Setting PTATLAS=ATLAS
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /home/jijoy/ocs-ci/venv/lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
      INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: atlas_info:
      INFO:   libraries f77blas,cblas,atlas not found in /home/jijoy/ocs-ci/venv/lib
      INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib64
      INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib
      INFO:   libraries f77blas,cblas,atlas not found in /usr/lib64
      INFO:   libraries f77blas,cblas,atlas not found in /usr/lib
      INFO:   libraries f77blas,cblas,atlas not found in /usr/lib/
      INFO: <class 'numpy.distutils.system_info.atlas_info'>
      INFO:   NOT AVAILABLE
      INFO:
      INFO: lapack_info:
      INFO:   libraries lapack not found in ['/home/jijoy/ocs-ci/venv/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
      INFO:   NOT AVAILABLE
      INFO:
      /tmp/pip-build-env-aqpmva4k/overlay/lib64/python3.10/site-packages/numpy/distutils/system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO: lapack_src_info:
      INFO:   NOT AVAILABLE
      INFO:
      /tmp/pip-build-env-aqpmva4k/overlay/lib64/python3.10/site-packages/numpy/distutils/system_info.py:1902: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      INFO:   NOT AVAILABLE
      INFO:
      Traceback (most recent call last):
        File "/home/jijoy/ocs-ci/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/jijoy/ocs-ci/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/jijoy/ocs-ci/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-aqpmva4k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-aqpmva4k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 253, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-aqpmva4k/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 145, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 588, in <module>
          setup_package()
        File "setup.py", line 584, in setup_package
          setup(**metadata)
        File "/tmp/pip-build-env-aqpmva4k/overlay/lib64/python3.10/site-packages/numpy/distutils/core.py", line 135, in setup
          config = configuration()
        File "setup.py", line 499, in configuration
          raise NotFoundError(msg)
      numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
      To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
      See site.cfg.example in the Scipy source directory and
      https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

```
$ pip install --upgrade pip setuptools
Requirement already satisfied: pip in ./venv/lib/python3.10/site-packages (22.1.2)
Requirement already satisfied: setuptools in ./venv/lib/python3.10/site-packages (63.1.0)
```

Python 3.10.5

**Comment by vavuthu** [comment]
issue is fixed after updating scipy package to 1.8.1
