### ISSUE TITLE
ocs-ci setup fails on scipy 1.8.1 dependency

### ISSUE THREAD

**Issue by schaefm-ibm** [red-hat-storage/ocs-ci#6326]
Running on RHEL 8.6, s390x architecture. The ocs-ci setup - `pip install -r requirements.txt` fails on building `scipy==1.8.1`, seemingly because of a numpy build error.

Environment:
```
$ python --version
Python 3.8.12
$ python -m venv ocs-ci-venv
$ source ocs-ci-venv/bin/activate
$ pip install --upgrade pip setuptools wheel
Collecting pip
  Using cached https://files.pythonhosted.org/packages/1f/2c/d9626f045e7b49a6225c6b09257861f24da78f4e5f23af2ddbdf852c99b8/pip-22.2.2-py3-none-any.whl                                                                      
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/a2/dd/d8cdd14320106ff58d4eb6e6553bae7a822e174ad5b05db486332d50d4ec/setuptools-65.0.0-py3-none-any.whl                                                               
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/27/d6/003e593296a85fd6ed616ed962795b2f87709c3eee2bca4f6d0fe55c6d00/wheel-0.37.1-py2.py3-none-any.whl                                                                
Installing collected packages: pip, setuptools, wheel
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
  Found existing installation: setuptools 41.6.0
    Uninstalling setuptools-41.6.0:
      Successfully uninstalled setuptools-41.6.0
Successfully installed pip-22.2.2 setuptools-65.0.0 wheel-0.37.1
```

When setting up the dependencies in the venv:
```
$ pip install -r requirements.txt
Obtaining ocp-network-split from git+https://gitlab.com/mbukatov/ocp-network-split.git@v0.1.0#egg=ocp-network-split (from -r requirements.txt (line 1))
  Updating /home/schaefm/ocs-ci-venv/src/ocp-network-split clone (to revision v0.1.0)
  Running command git fetch -q --tags
  Running command git reset --hard -q 42962e3a0aae2158733847ae3098e7373fc457f7
  Preparing metadata (setup.py): started
...
Collecting scipy==1.8.1
  Using cached scipy-1.8.1.tar.gz (38.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  error: subprocess-exited-with-error

  ~W pip subprocess to install build dependencies did not run successfully.
  ~T~B exit code: 1
  ~U~T~@> [118 lines of output]
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.8" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64" and platform_machine != "s390x" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.10" and platform_python_implementation != "PyPy"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.11"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_python_implementation == "PyPy"' don't match your environment
      Collecting wheel<0.38.0
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting setuptools<60.0.0
        Using cached setuptools-59.8.0-py3-none-any.whl (952 kB)
      Collecting Cython<3.0,>=0.29.18
        Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
      Collecting pybind11<2.9.0,>=2.4.3
        Using cached pybind11-2.8.1-py2.py3-none-any.whl (208 kB)
      Collecting pythran<0.11.0,>=0.10.0
        Using cached pythran-0.10.0-py3-none-any.whl (4.3 MB)
      Collecting numpy==1.17.5
        Using cached numpy-1.17.5.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting beniget~=0.4.0
        Using cached beniget-0.4.1-py3-none-any.whl (9.4 kB)
      Collecting gast~=0.5.0
        Using cached gast-0.5.3-py3-none-any.whl (19 kB)
      Collecting ply>=3.4
        Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        ~W python setup.py bdist_wheel did not run successfully.
        ~T~B exit code: 1
        ~U~T~@> [15 lines of output]
            Running from numpy source directory.
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/setup.py", line 444, in <module>
                setup_package()
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/setup.py", line 423, in setup_package
                from numpy.distutils.core import setup
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/numpy/distutils/core.py", line 26, in <module>
                from numpy.distutils.command import config, config_compiler, \
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/numpy/distutils/command/config.py", line 20, in <module>
                from numpy.distutils.mingw32ccompiler import generate_manifest
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/numpy/distutils/mingw32ccompiler.py", line 34, in <module>
                from distutils.msvccompiler import get_build_version as get_build_msvc_version
            ModuleNotFoundError: No module named 'distutils.msvccompiler'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error

        ~W python setup.py clean did not run successfully.
        ~T~B exit code: 1
        ~U~T~@> [10 lines of output]
            Running from numpy source directory.

            `setup.py clean` is not supported, use one of the following instead:

              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)

            Add `--force` to your command to use it anyway if you must (unsupported).

            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      Installing collected packages: ply, wheel, setuptools, pybind11, numpy, gast, Cython, beniget, pythran
        Running setup.py install for numpy: started
        Running setup.py install for numpy: finished with status 'error'
        error: subprocess-exited-with-error

        ~W Running setup.py install for numpy did not run successfully.
        ~T~B exit code: 1
        ~U~T~@> [24 lines of output]
            Running from numpy source directory.

            Note: if you need reliable uninstall behavior, then install
            with pip instead of using `setup.py install`:

              - `pip install .`       (from a git repo or downloaded source
                                       release)
              - `pip install numpy`   (last NumPy release on PyPi)


            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/setup.py", line 444, in <module>
                setup_package()
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/setup.py", line 423, in setup_package
                from numpy.distutils.core import setup
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/numpy/distutils/core.py", line 26, in <module>
                from numpy.distutils.command import config, config_compiler, \
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/numpy/distutils/command/config.py", line 20, in <module>
                from numpy.distutils.mingw32ccompiler import generate_manifest
              File "/tmp/pip-install-t9wmff_0/numpy_cd62f01a6dac4b9fa8f52f9effca4b22/numpy/distutils/mingw32ccompiler.py", line 34, in <module>
                from distutils.msvccompiler import get_build_version as get_build_msvc_version
            ModuleNotFoundError: No module named 'distutils.msvccompiler'
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure

      ~W Encountered error while trying to install package.
      ~U~T~@> numpy

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

~W pip subprocess to install build dependencies did not run successfully.
~T~B exit code: 1
~U~T~@> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

As mentioned in https://github.com/red-hat-storage/ocs-ci/issues/6325, the setup.py is using a newer `gevent`:
```
$ git diff setup.py 
diff --git a/setup.py b/setup.py
index 1149be27..8aa85619 100644
--- a/setup.py
+++ b/setup.py
@@ -18,7 +18,7 @@ setup(
         "apache-libcloud==3.1.0",
         "cryptography==36.0.2",
         "docopt==0.6.2",
-        "gevent==20.9.0",
+        "gevent==21.12.0",
         "reportportal-client==3.2.3",
         "requests==2.23.0",
         "paramiko==2.11.0",
@@ -67,7 +67,7 @@ setup(
         "webdriver-manager==3.2.2",
         # greenlet 1.0.0 is broken on ppc64le
         # https://github.com/python-greenlet/greenlet/issues/230
-        "greenlet<1.0.0",
+        #"greenlet<1.0.0",
         "ovirt-engine-sdk-python==4.4.11",
         "junitparser",
         "flaky==3.7.0",
```

**Comment by aditidukle** [comment]
its failing on ppc64le platform too.

**Comment by aditidukle** [comment]
This worked for us with setuptools 63.2.0 version. 
https://github.com/numpy/numpy/issues/22135

**Comment by schaefm-ibm** [comment]
Thanks for the hint - venv update with `pip install --upgrade pip "setuptools<=64.0.0" wheel` before actual ocs-ci dependencies works for s390 / RHEL.
