### ISSUE TITLE
ImportError: cannot import name 'Log' from 'distutils.log' (/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/setuptools/_distutils/log.py)

### ISSUE THREAD

**Issue by achuzhoy** [red-hat-storage/ocs-ci#6667]
Executing tests started to fail with:

```
Traceback (most recent call last):
  File "/home/kni/ocs-ci/.venv//bin/run-ci", line 33, in <module>
    sys.exit(load_entry_point('ocs-ci', 'console_scripts', 'run-ci')())
  File "/home/kni/ocs-ci/.venv//bin/run-ci", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/kni/ocs-ci/.venv/lib64/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/kni/ocs-ci/.venv/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/kni/ocs-ci/ocs_ci/framework/main.py", line 13, in <module>
    from ocs_ci.utility import utils
  File "/home/kni/ocs-ci/ocs_ci/utility/utils.py", line 21, in <module>
    from scipy.stats import tmean, scoreatpercentile
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/stats/__init__.py", line 453, in <module>
    from ._stats_py import *
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 44, in <module>
    from . import distributions
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/stats/distributions.py", line 8, in <module>
    from ._distn_infrastructure import (rv_discrete, rv_continuous, rv_frozen)
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/stats/_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/optimize/__init__.py", line 400, in <module>
    from ._minimize import *
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 27, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/optimize/_trustregion_constr/__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/optimize/_trustregion_constr/minimize_trustregion_constr.py", line 5, in <module>
    from .._constraints import (
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/scipy/optimize/_constraints.py", line 8, in <module>
    from numpy.testing import suppress_warnings
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from ._private import extbuild, decorators as dec
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/numpy/testing/_private/extbuild.py", line 11, in <module>
    from numpy.distutils.ccompiler import new_compiler
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/numpy/distutils/__init__.py", line 24, in <module>
    from . import ccompiler
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 20, in <module>
    from numpy.distutils import log
  File "/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/numpy/distutils/log.py", line 4, in <module>
    from distutils.log import Log as old_Log
ImportError: cannot import name 'Log' from 'distutils.log' (/home/kni/ocs-ci/.venv/lib/python3.8/site-packages/setuptools/_distutils/log.py)
```

**Comment by achuzhoy** [comment]
The workaround is to append prior to running "pip install -r requirements.txt" the following to requirements.txt:
```setuptools<=65.5.1```

**Comment by achuzhoy** [comment]
@petr-balogh @ebenahar

**Comment by ebenahar** [comment]
Thanks @achuzhoy for reporting and finding the workaround.

**Comment by ebenahar** [comment]
@OdedViner could you please take a look?

**Comment by OdedViner** [comment]
There is a bug on numpy with setuptools 65.6.0 https://github.com/numpy/numpy/issues/22623


The WA is installation setuptools==65.5.0
pip install setuptools==65.5.0

Full Procedure:
python3.8 -m venv venv
source venv/bin/activate
pip install --upgrade pip setuptools
pip install setuptools==65.5.0
pip install -r requirements.txt

If you clone a new project,  you will get the following result [without WA]:
```
    from . import ccompiler
  File "/home/odedviner/ClusterPath/auth/test1/ocs-ci/venv/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 20, in <module>
    from numpy.distutils import log
  File "/home/odedviner/ClusterPath/auth/test1/ocs-ci/venv/lib/python3.8/site-packages/numpy/distutils/log.py", line 4, in <module>
    from distutils.log import Log as old_Log
ImportError: cannot import name 'Log' from 'distutils.log' (/home/odedviner/ClusterPath/auth/test1/ocs-ci/venv/lib/python3.8/site-packages/setuptools/_distutils/log.py)
```
