### ISSUE TITLE
mcg connection issue while retriving token using rpc calls on IPV6 based cluster

### ISSUE THREAD

**Issue by parikshithb** [red-hat-storage/ocs-ci#6712]
`07:57:56 - MainThread - /root/ocs-ci/ocs_ci/ocs/resources/mcg.py - INFO  - Sending MCG RPC query:
auth_api create_auth {'role': 'admin', 'system': 'noobaa', 'email': 'admin@noobaa.io', 'password': '/P6KsW8KK/wkiu/YR5KUDA=='}
07:57:56 - MainThread - ocs_ci.utility.utils - ERROR  - Exception raised during iteration: HTTPSConnectionPool(host='noobaa-mgmt-openshift-storage.apps.bm.example.com', port=443): Max retries exceeded with url: /rpc (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7f5bb1a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Traceback (most recent call last):
  File "/root/venv1/lib64/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/root/venv1/lib64/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/venv1/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/root/venv1/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/root/venv1/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/root/venv1/lib64/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/root/venv1/lib64/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe7f5bb1a60>: Failed to establish a new connection: [Errno -2] Name or service not known
`

**Comment by parikshithb** [comment]
Complete run logs: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/ipv6/acceptance_1670312673/acceptance_console.log

**Comment by vavuthu** [comment]
infra issue whic was fixed and rerun the acceptance sute where all tests are passed

RUN ID: 1670412411
