### ISSUE TITLE
test_s3_upload_with_java failed with ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh session-java-s3-3f2c7f4ca1a1481eb1e25bb2 mvn exec:java -Dexec.mainClass=amazons3.s3test.ChunkedUploadApplication -Dexec.args="https://s3.openshift-storage.svc:443 DqfjqajAFJ2yZEMocFDx de473JhpfwgrZ4KeJAVrfyCY79DlVGo+Dt3Pocep s3-bucket-6a49a1d1ffcb40dc9d1322b3bb6f2e True" -Dmaven.test.skip=true package.

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#6763]
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6790/280850/280959/280961/log
Run ID: 1669734217
Test Case: test_s3_upload_with_java
ODF Build: 4.12.0-120
OCP Version: 4.13
Job name: AWS IPI 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6183/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-157ai3c33-uo/j-157ai3c33-uo_20221129T063027/logs/

Failure Details:
```
Message: ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh session-java-s3-3f2c7f4ca1a1481eb1e25bb2 mvn exec:java -Dexec.mainClass=amazons3.s3test.ChunkedUploadApplication -Dexec.args="https://s3.openshift-storage.svc:443 DqfjqajAFJ2yZEMocFDx de473JhpfwgrZ4KeJAVrfyCY79DlVGo+Dt3Pocep s3-bucket-6a49a1d1ffcb40dc9d1322b3bb6f2e True" -Dmaven.test.skip=true package.
Error is Nov 29, 2022 7:14:56 PM com.amazonaws.http.AmazonHttpClient createSocketFactoryRegistry
WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
Nov 29, 2022 7:14:56 PM com.amazonaws.util.Base64 warn
WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: lb2lmdif-97yuh3-340; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6531)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
	at amazons3.s3test.ChunkedUploadApplication.regularUpload(ChunkedUploadApplication.java:140)
	at amazons3.s3test.ChunkedUploadApplication.testCycle(ChunkedUploadApplication.java:78)
	at amazons3.s3test.ChunkedUploadApplication.main(ChunkedUploadApplication.java:50)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
	at java.base/java.lang.Thread.run(Thread.java:829)
command terminated with exit code 1
Type: None

Text:
self = <tests.manage.mcg.test_s3_with_java_sdk.TestS3WithJavaSDK object at 0x7fd75bdc4d60>
bucket_factory = <function bucket_factory_fixture.<locals>._create_buckets at 0x7fd782513820>
javasdk_pod_session = <ocs_ci.ocs.resources.pod.Pod object at 0x7fd75a8c5520>
mcg_obj_session = <ocs_ci.ocs.resources.mcg.MCG object at 0x7fd75c48b670>
is_multipart = True

    @bugzilla("2064304")
    @pytest.mark.parametrize(
        argnames=["is_multipart"],
        argvalues=[
            pytest.param(*[False], marks=[tier1, pytest.mark.polarion_id("OCS-3964")]),
            pytest.param(*[True], marks=[tier1, pytest.mark.polarion_id("OCS-3978")]),
        ],
    )
    def test_s3_upload_with_java(
        self, bucket_factory, javasdk_pod_session, mcg_obj_session, is_multipart
    ):
        """
        Tests S3 upload with Java application
        """
    
        regular_bucket_name = bucket_factory()[0].name
        namespace_bucketclass_dict = {
            "interface": "OC",
            "namespace_policy_dict": {
                "type": "Single",
                "namespacestore_dict": {"aws": [(1, "eu-central-1")]},
            },
        }
        namespace_bucket_name = bucket_factory(bucketclass=namespace_bucketclass_dict)[
            0
        ].name
    
        if is_multipart:
            logger.info(
                f"Initiating Multipart upload operation on buckets {regular_bucket_name} and {namespace_bucket_name}"
            )
        else:
            logger.info(
                f"Initiating upload operation on buckets {regular_bucket_name} and {namespace_bucket_name}"
            )
    
        # initiating upload operation with regular s3 bucket
>       assert upload_objects_with_javasdk(
            javas3_pod=javasdk_pod_session,
            s3_obj=mcg_obj_session,
            bucket_name=regular_bucket_name,
            is_multipart=is_multipart,
        ), f"Upload objects failed for bucket {regular_bucket_name}"

tests/manage/mcg/test_s3_with_java_sdk.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/ocs/bucket_utils.py:309: in upload_objects_with_javasdk
    return javas3_pod.exec_cmd_on_pod(command=command, out_yaml_format=False)
ocs_ci/ocs/resources/pod.py:175: in exec_cmd_on_pod
    return self.ocp.exec_oc_cmd(
ocs_ci/ocs/ocp.py:163: in exec_oc_cmd
    out = run_cmd(
ocs_ci/utility/utils.py:473: in run_cmd
    completed_process = exec_cmd(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cmd = ['oc', '-n', 'openshift-storage', 'rsh', 'session-java-s3-3f2c7f4ca1a1481eb1e25bb2', 'mvn', ...]
secrets = None, timeout = 600, ignore_error = False, threading_lock = None
silent = False, kwargs = {}
masked_cmd = 'oc -n openshift-storage rsh session-java-s3-3f2c7f4ca1a1481eb1e25bb2 mvn exec:java -Dexec.mainClass=amazons3.s3test.C...de473JhpfwgrZ4KeJAVrfyCY79DlVGo+Dt3Pocep s3-bucket-6a49a1d1ffcb40dc9d1322b3bb6f2e True" -Dmaven.test.skip=true package'
completed_process = CompletedProcess(args=['oc', '-n', 'openshift-storage', 'rsh', 'session-java-s3-3f2c7f4ca1a1481eb1e25bb2', 'mvn', 'exe...n(ExecJavaMojo.java:279)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\ncommand terminated with exit code 1\n')
masked_stdout = '[INFO] Scanning for projects...\n[INFO] \n[INFO] --------------------------< amazons3:s3test >-----------------------...-\n[INFO] \n[INFO] --- exec-maven-plugin:3.1.0:java (default-cli) @ s3test ---\nUpload objects failed\nTEST FAILED!!\n'
masked_stderr = 'Nov 29, 2022 7:14:56 PM com.amazonaws.http.AmazonHttpClient createSocketFactoryRegistry\nWARNING: SSL Certificate che...un(ExecJavaMojo.java:279)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\ncommand terminated with exit code 1\n'

    def exec_cmd(
        cmd,
        secrets=None,
        timeout=600,
        ignore_error=False,
        threading_lock=None,
        silent=False,
        **kwargs,
    ):
        """
        Run an arbitrary command locally
    
        If the command is grep and matching pattern is not found, then this function
        returns "command terminated with exit code 1" in stderr.
    
        Args:
            cmd (str): command to run
            secrets (list): A list of secrets to be masked with asterisks
                This kwarg is popped in order to not interfere with
                subprocess.run(``**kwargs``)
            timeout (int): Timeout for the command, defaults to 600 seconds.
            ignore_error (bool): True if ignore non zero return code and do not
                raise the exception.
            threading_lock (threading.Lock): threading.Lock object that is used
                for handling concurrent oc commands
            silent (bool): If True will silent errors from the server, default false
    
        Raises:
            CommandFailed: In case the command execution fails
    
        Returns:
            (CompletedProcess) A CompletedProcess object of the command that was executed
            CompletedProcess attributes:
            args: The list or str args passed to run().
            returncode (str): The exit code of the process, negative for signals.
            stdout     (str): The standard output (None if not captured).
            stderr     (str): The standard error (None if not captured).
    
        """
        masked_cmd = mask_secrets(cmd, secrets)
        log.info(f"Executing command: {masked_cmd}")
        if isinstance(cmd, str):
            cmd = shlex.split(cmd)
        if threading_lock and cmd[0] == "oc":
            threading_lock.acquire()
        completed_process = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.PIPE,
            timeout=timeout,
            **kwargs,
        )
        if threading_lock and cmd[0] == "oc":
            threading_lock.release()
        masked_stdout = mask_secrets(completed_process.stdout.decode(), secrets)
        if len(completed_process.stdout) > 0:
            log.debug(f"Command stdout: {masked_stdout}")
        else:
            log.debug("Command stdout is empty")
    
        masked_stderr = mask_secrets(completed_process.stderr.decode(), secrets)
        if len(completed_process.stderr) > 0:
            if not silent:
                log.warning(f"Command stderr: {masked_stderr}")
        else:
            log.debug("Command stderr is empty")
        log.debug(f"Command return code: {completed_process.returncode}")
        if completed_process.returncode and not ignore_error:
            if (
                "grep" in masked_cmd
                and b"command terminated with exit code 1" in completed_process.stderr
            ):
                log.info(f"No results found for grep command: {masked_cmd}")
            else:
>               raise CommandFailed(
                    f"Error during execution of command: {masked_cmd}."
                    f"\nError is {masked_stderr}"
                )
E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh session-java-s3-3f2c7f4ca1a1481eb1e25bb2 mvn exec:java -Dexec.mainClass=amazons3.s3test.ChunkedUploadApplication -Dexec.args="https://s3.openshift-storage.svc:443 DqfjqajAFJ2yZEMocFDx de473JhpfwgrZ4KeJAVrfyCY79DlVGo+Dt3Pocep s3-bucket-6a49a1d1ffcb40dc9d1322b3bb6f2e True" -Dmaven.test.skip=true package.
E               Error is Nov 29, 2022 7:14:56 PM com.amazonaws.http.AmazonHttpClient createSocketFactoryRegistry
E               WARNING: SSL Certificate checking for endpoints has been explicitly disabled.
E               Nov 29, 2022 7:14:56 PM com.amazonaws.util.Base64 warn
E               WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
E               com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 500; Error Code: InternalError; Request ID: lb2lmdif-97yuh3-340; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
E               	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
E               	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
E               	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
E               	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
E               	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
E               	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
E               	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6531)
E               	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
E               	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
E               	at amazons3.s3test.ChunkedUploadApplication.regularUpload(ChunkedUploadApplication.java:140)
E               	at amazons3.s3test.ChunkedUploadApplication.testCycle(ChunkedUploadApplication.java:78)
E               	at amazons3.s3test.ChunkedUploadApplication.main(ChunkedUploadApplication.java:50)
E               	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
E               	at java.base/java.lang.Thread.run(Thread.java:829)
E               command terminated with exit code 1

ocs_ci/utility/utils.py:636: CommandFailed

```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7100/296186/296248/296249/log
Run ID: 1670263326
Test Case: test_s3_upload_with_java
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: AWS UPI Disconnected 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6300/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-066aud3c33-ua/j-066aud3c33-ua_20221205T121524/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh session-java-s3-5488f8fc0d5e482897fbd04d mvn clean compile.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6805/281880/281989/281990/log
Run ID: 1669759366
Test Case: test_s3_upload_with_java
ODF Build: 4.12.0-120
OCP Version: 4.12
Job name: AWS UPI Proxy 3AZ RHCOS 3M 3W tier1 or tier_after_upgrade post upgrade
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6185/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-002aup3c33-uba/j-002aup3c33-uba_20221129T140742/logs/
Error Message: ```ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage rsh session-java-s3-3aff179c1cd84d65a38bebc2 mvn clean compile.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6998/291593/291770/291772/log
Run ID: 1669980540
Test Case: test_rook_ceph_operator_log_type
ODF Build: 4.12.0-122
OCP Version: 4.12
Job name: BAREMETAL UPI 1AZ RHCOS NVME INTEL COMPACT MODE 3M 0W tier2
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6270/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-003bu1cni30-t2/j-003bu1cni30-t2_20221202T102339/logs/
Error Message: ```failed on teardown with "ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage patch ConfigMap rook-ceph-operator-config -n openshift-storage -p '[{"op": "add", "path": "/data/ROOK_LOG_LEVEL", "value": "INFO"}]' --type json.```

**Comment by ebenahar** [comment]
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6545/269251/269416/269418/log
Run ID: 1669185621
Test Case: test_rook_ceph_operator_log_type
ODF Build: 4.12.0-114
OCP Version: 4.12
Job name: VSPHERE6 UPI Disconnected 1AZ RHCOS VSAN 3M 3W tier2
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6119/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-001vud1cs33-t2/j-001vud1cs33-t2_20221123T044902/logs/
Error Message: ```failed on teardown with "ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-storage patch ConfigMap rook-ceph-operator-config -n openshift-storage -p '[{"op": "add", "path": "/data/ROOK_LOG_LEVEL", "value": "INFO"}]' --type json.```
