### ISSUE TITLE
Consolidate custom configuration CLI arguments

### ISSUE THREAD

**Issue by clacroix12** [red-hat-storage/ocs-ci#700]
We currently have two CLI arguments for updating the configuration with non-default values. Both of these options effectively do the same thing. One of them (--ocsci-conf) is specifically used by jenkins which makes it unusable by users for jenkins executions. The other (--cluster-conf) is available for users. The name `--cluster-conf` is a bit disingenuous as well since values can be added to the file you pass here to effect all areas of the configuration, not just values specific to the cluster.

After some discussion with a few team members we thought it would be better to consolidate to having only one option, but make it able to be repeated so multiple configuration files may be passed that will override the default config values. We think sticking with `--ocsci-conf`, making it repeatable, and removing `--cluster-conf` is the right way to do this.

This approach will have to take order into consideration:
```
run-ci --ocsci-conf file1.yml --ocsci-conf file2.yml --ocsci-conf file3.yml
```
In this scenario the default config will be updated with `file1.yml` first, followed by `file2.yml`, and then finally `file3.yml`. If any of the custom config files share keys, the latter file's value will be used.

Objectives:
- [x] Remove `--cluster-conf`
- [x] Make `--ocsci-conf` a repeatable argument
- [x] Remove `--cluster-conf` field from jenkins job definitions

**Comment by vasukulkarni** [comment]
👍

**Comment by petr-balogh** [comment]
This needs to be well organized and after the PR is prepared we need to align also our jenkins job definition for it, test together and once both changes are verified we need to merge together.  Otherwise the definition above looks fine to me. Thanks

**Comment by petr-balogh** [comment]
@clacroix12 I didn't make --ocsci-conf repeatable, instead I am allowing to take list of config files separated by comma which was much easier for implementation in current state as we don't use argparse and parsing those parameters ourself. 

Starting with this parameter ocsci-conf so once we will merge we can start changing our jobs to use this one parameter only and once we and engineering is done with this change in the jenkins jobs we can remove cluster-conf parameter and use just this one.

**Comment by clacroix12** [comment]
@petr-balogh it's actuall easy to change `--ocsci-conf` from storing one value to being repeatable. We can do this by changing the `action` to `append`. I believe the default action is `store`.

```python
    parser.addoption(
        '--ocsci-conf',
        action="append"
        dest='ocsci_conf',
        help="Path to config file of OCS CI",
    )
```

This will change `ocsci_conf` from a single value to a list of values.

I tested this locally with some dummy code:
```python
def pytest_addoption(parser):
    parser.addoption(
        "--config", action="append", dest="custom_config", default=None, help="custom config value"
    )

def pytest_configure(config):
    print(config.getoption('custom_config'))
```
```console
$ pytest --capture=no --config one --config two --config three
['one', 'two', 'three']
```

**Comment by petr-balogh** [comment]
@clacroix12 , that is not so easy in our case as we need to have config even before we run pytest.
See here: 
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/main.py#L39
We have function own function for getting params here:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/main.py#L11

Pytest is invoked at the end of main here:
https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/framework/main.py#L64

**Comment by clacroix12** [comment]
@petr-balogh I see your point. In that case, can't we just use argparse ourselves instead of trying to do all the heavy lifting manually?

```python
def init_ocsci_conf(arguments=None):
    ...
    parser = argparse.ArgumentParser()
    parser.add_argument('--ocsci-conf', action="append", dest="ocsci_conf")
    args, unknown = parser.parse_known_args(arguments)
    for cfg in args.ocsci_conf:
        with open(os.path.expanduser(cfg)) as file_stream:
            custom_config_data = yaml.safe_load(file_stream)
            framework.config.update(custom_config_data)
    ...
```

**Comment by petr-balogh** [comment]
@clacroix12 The reason for not using it was that in case we use argparse it will take the responsibility of printing info for --help and so on, but we want to pytest to process it and print its info for help and so on. I thought about using argparse before but this was the reason why I implemented this function which we are using here just for process 2 parameters for config. When we will move to one parameter we will use only one here before running pytest. So I think it's easier for us to have just one function and the rest let pytest to process instead of using argparse with the issues mentioned above.

**Comment by clacroix12** [comment]
> So I think it's easier for us to have just one function and the rest let pytest to process instead of using argparse with the issues mentioned above.

Unless I'm missing something here we aren't actually letting pytest process these arguments. We are processing them ourselves before we call pytest. We add the options but pytest doesn't actually DO anything with the values.

> The reason for not using it was that in case we use argparse it will take the responsibility of printing info for --help and so on

I don't see how this is the case. Argparse won't take responsibility for printing help, pytest will still do that if we are executing `run-ci --help`.  As long as what we have in our pytest help matches what argparse is expecting, I don't see an issue since we are already manually parsing out and using the values from the config options anyways.

The reason I think an approach like this might be better for us is because it matches the actual functionality that pytest parser provides (which i'm pretty sure is argparse under the hood). In addition, being able to add this option multiple times probably makes the changes on the jenkins job side easier as well. Instead of having to inject the custom config file into the value given by the user, we can simply call `--ocsci-conf` again with the value needed for jenkins.

Overall, as long as we can utilize one option for passing config overrides it's not a big deal. My main concern is consistency with how other CLI options function and wanting to leverage existing methods that do the work for us instead of implementing our own option parser code.

**Comment by petr-balogh** [comment]
> > So I think it's easier for us to have just one function and the rest let pytest to process instead of using argparse with the issues mentioned above.
> 
> Unless I'm missing something here we aren't actually letting pytest process these arguments. We are processing them ourselves before we call pytest. We add the options but pytest doesn't actually DO anything with the values.

@clacroix12  yep, that's true, but at least we are abusing pytest for printing help info for us for this argument.

> 
> > The reason for not using it was that in case we use argparse it will take the responsibility of printing info for --help and so on
> 
> I don't see how this is the case. Argparse won't take responsibility for printing help, pytest will still do that if we are executing `run-ci --help`. As long as what we have in our pytest help matches what argparse is expecting, I don't see an issue since we are already manually parsing out and using the values from the config options anyways.

let me explain here:

I used your example for demonstrate the output here:
```console
(.venv) pbalogh@MacBook-Pro ocs-ci (consolidate-custom-config-files) $ run-ci --help
usage: run-ci [-h] [--ocsci-conf OCSCI_CONF]

optional arguments:
  -h, --help            show this help message and exit
  --ocsci-conf OCSCI_CONF
```

as you can see arparse take action about printing all the info, but for user we want to print pytest output.

But if we don't use arparse and let pytest take care of it you will see this output:
```console
(.venv) pbalogh@MacBook-Pro ocs-ci (consolidate-custom-config-files) $ run-ci --help
usage: run-ci [options] [file_or_dir] [file_or_dir] [...]

positional arguments:
  file_or_dir

general:
  -k EXPRESSION         only run tests which match the given substring
                        expression. An expression is a python evaluatable
                        expression where all names are substring-matched
                        against test names and their parent classes. Example:
                        -k 'test_method or test_other' matches all test
                        functions and classes whose name contains
                        'test_method' or 'test_other', while -k 'not
                        test_method' matches those that don't contain
                        'test_method' in their names. -k 'not test_method and
                        not test_other' will eliminate the matches.
                        Additionally keywords are matched to classes and
                        functions containing extra names in their
                        'extra_keyword_matches' set, as well as functions
                        which have names assigned directly to them.
  -m MARKEXPR           only run tests matching given mark expression.
                        example: -m 'mark1 and not mark2'.
  --markers             show markers (builtin, plugin and per-project ones).
  -x, --exitfirst       exit instantly on first error or failed test.
  --maxfail=num         exit after first num failures or errors.
  --strict-markers, --strict
                        markers not registered in the `markers` section of the
                        configuration file raise errors.
  -c file               load configuration from `file` instead of trying to
                        locate one of the implicit configuration files.
  --continue-on-collection-errors
                        Force test execution even if collection errors occur.
  --rootdir=ROOTDIR     Define root directory for tests. Can be relative path:
                        'root_dir', './root_dir', 'root_dir/another_dir/';
                        absolute path: '/home/user/root_dir'; path with
                        variables: '$HOME/root_dir'.
  --fixtures, --funcargs
                        show available fixtures, sorted by plugin appearance
                        (fixtures with leading '_' are only shown with '-v')
  --fixtures-per-test   show fixtures per test
  --import-mode={prepend,append}
                        prepend/append to sys.path when importing test
                        modules, default is to prepend.
  --pdb                 start the interactive Python debugger on errors or
                        KeyboardInterrupt.
  --pdbcls=modulename:classname
                        start a custom interactive Python debugger on errors.
                        For example:
                        --pdbcls=IPython.terminal.debugger:TerminalPdb
  --trace               Immediately break when running each test.
  --capture=method      per-test capturing method: one of fd|sys|no.
  -s                    shortcut for --capture=no.
  --runxfail            report the results of xfail tests as if they were not
                        marked
  --lf, --last-failed   rerun only the tests that failed at the last run (or
                        all if none failed)
  --ff, --failed-first  run all tests but run the last failures first. This
                        may re-order tests and thus lead to repeated fixture
                        setup/teardown
  --nf, --new-first     run tests from new files first, then the rest of the
                        tests sorted by file mtime
  --cache-show=[CACHESHOW]
                        show cache contents, don't perform collection or
                        tests. Optional argument: glob (default: '*').
  --cache-clear         remove all cache contents at start of test run.
  --lfnf={all,none}, --last-failed-no-failures={all,none}
                        which tests to run with no previously (known)
                        failures.
  --sw, --stepwise      exit on test failure and continue from last failing
                        test next time
  --stepwise-skip       ignore the first failing test but stop on the next
                        failing test

reporting:
  --durations=N         show N slowest setup/test durations (N=0 for all).
  -v, --verbose         increase verbosity.
  -q, --quiet           decrease verbosity.
  --verbosity=VERBOSE   set verbosity
  -r chars              show extra test summary info as specified by chars:
                        (f)ailed, (E)rror, (s)kipped, (x)failed, (X)passed,
                        (p)assed, (P)assed with output, (a)ll except passed
                        (p/P), or (A)ll. (w)arnings are enabled by default
                        (see --disable-warnings).
  --disable-warnings, --disable-pytest-warnings
                        disable warnings summary
  -l, --showlocals      show locals in tracebacks (disabled by default).
  --tb=style            traceback print mode (auto/long/short/line/native/no).
  --show-capture={no,stdout,stderr,log,all}
                        Controls how captured stdout/stderr/log is shown on
                        failed tests. Default is 'all'.
  --full-trace          don't cut any tracebacks (default is to cut).
  --color=color         color terminal output (yes/no/auto).
  --pastebin=mode       send failed|all info to bpaste.net pastebin service.
  --junit-xml=path      create junit-xml style report file at given path.
  --junit-prefix=str    prepend prefix to classnames in junit-xml output
  --result-log=path     DEPRECATED path for machine-readable result log.
  --html=path           create html report file at given path.
  --self-contained-html
                        create a self-contained html file containing all
                        necessary styles, scripts, and images - this means
                        that the report may not render or function where CSP
                        restrictions are in place (see
                        https://developer.mozilla.org/docs/Web/Security/CSP)
  --css=path            append given css file content to report style file.

collection:
  --collect-only        only collect tests, don't execute them.
  --pyargs              try to interpret all arguments as python packages.
  --ignore=path         ignore path during collection (multi-allowed).
  --ignore-glob=path    ignore path pattern during collection (multi-allowed).
  --deselect=nodeid_prefix
                        deselect item during collection (multi-allowed).
  --confcutdir=dir      only load conftest.py's relative to specified dir.
  --noconftest          Don't load any conftest.py files.
  --keep-duplicates     Keep duplicate tests.
  --collect-in-virtualenv
                        Don't ignore tests in a local virtualenv directory
  --doctest-modules     run doctests in all .py modules
  --doctest-report={none,cdiff,ndiff,udiff,only_first_failure}
                        choose another output format for diffs on doctest
                        failure
  --doctest-glob=pat    doctests file matching pattern, default: test*.txt
  --doctest-ignore-import-errors
                        ignore doctest ImportErrors
  --doctest-continue-on-failure
                        for a given doctest, continue to run after the first
                        failure

test session debugging and configuration:
  --basetemp=dir        base temporary directory for this test run.(warning:
                        this directory is removed if it exists)
  --version             display pytest lib version and import information.
  -h, --help            show help message and configuration info
  -p name               early-load given plugin module name or entry point
                        (multi-allowed). To avoid loading of plugins, use the
                        `no:` prefix, e.g. `no:doctest`.
  --trace-config        trace considerations of conftest.py files.
  --debug               store internal tracing debug information in
                        'pytestdebug.log'.
  -o OVERRIDE_INI, --override-ini=OVERRIDE_INI
                        override ini option with "option=value" style, e.g.
                        `-o xfail_strict=True -o cache_dir=cache`.
  --assert=MODE         Control assertion debugging tools. 'plain' performs no
                        assertion debugging. 'rewrite' (the default) rewrites
                        assert statements in test modules on import to provide
                        assert expression information.
  --setup-only          only setup fixtures, do not execute tests.
  --setup-show          show setup of fixtures while executing tests.
  --setup-plan          show what fixtures and tests would be executed but
                        don't execute anything.

pytest-warnings:
  -W PYTHONWARNINGS, --pythonwarnings=PYTHONWARNINGS
                        set which warnings to report, see -W option of python
                        itself.

logging:
  --no-print-logs       disable printing caught logs on failed tests.
  --log-level=LOG_LEVEL
                        logging level used by the logging module
  --log-format=LOG_FORMAT
                        log format as used by the logging module.
  --log-date-format=LOG_DATE_FORMAT
                        log date format as used by the logging module.
  --log-cli-level=LOG_CLI_LEVEL
                        cli logging level.
  --log-cli-format=LOG_CLI_FORMAT
                        log format as used by the logging module.
  --log-cli-date-format=LOG_CLI_DATE_FORMAT
                        log date format as used by the logging module.
  --log-file=LOG_FILE   path to a file when logging will be written to.
  --log-file-level=LOG_FILE_LEVEL
                        log file logging level.
  --log-file-format=LOG_FILE_FORMAT
                        log format as used by the logging module.
  --log-file-date-format=LOG_FILE_DATE_FORMAT
                        log date format as used by the logging module.

Bugzilla integration:
  --bugzilla            Enable Bugzilla support.
  --bugzilla-url=url    Overrides the xmlrpc url for bugzilla found in
                        bugzilla.cfg.
  --bugzilla-user=username
                        Overrides the bugzilla username in bugzilla.cfg.
  --bugzilla-password=password
                        Overrides the bugzilla password in bugzilla.cfg.
  --bugzilla-project-version=version
                        Overrides the project version in bugzilla.cfg.
  --bugzilla-looseversion-fields=loose
                        Overrides the project loose in bugzilla.cfg.

reporting:
  --rp-launch=RP_LAUNCH
                        Launch name (overrides rp_launch config option)
  --rp-launch-description=RP_LAUNCH_DESCRIPTION
                        Launch description (overrides rp_launch_description
                        config option)
  --reportportal        Enable ReportPortal plugin
  --rp-log-level=RP_LOG_LEVEL
                        Logging level for automated log records reporting

logger:
  --logger-logsdir=LOGGER_LOGSDIR
                        pick you own logs directory instead of default
                        directory under session tmpdir
  --loggers=LOGGER,LOGGER.LEVEL,...
                        comma delimited list of loggers optionally suffixed
                        with level preceded by a dot. Levels can be lower or
                        uppercase, or numeric. For example:
                        "logger1,logger2.info,logger3.FATAL,logger4.25"

custom options:
  --ocsci-conf=OCSCI_CONF
                        Path to config file of OCS CI
  --cluster-conf=CLUSTER_CONF
                        Path to cluster configuration yaml file
  --cluster-path=CLUSTER_PATH
                        Path to cluster directory
  --cluster-name=CLUSTER_NAME
                        Name of cluster
  --teardown            If provided the test cluster will be destroyed after
                        tests complete
  --deploy              If provided a test cluster will be deployed on AWS to
                        use for testing
  --email=EMAIL         Email ID to send results
  --collect-logs        Collect OCS logs when test case failed
  --io_in_bg            Run IO in the background
  --metadata=key value  additional metadata.

[pytest] ini-options in the first pytest.ini|tox.ini|setup.cfg file found:

  markers (linelist):   markers for test functions
  empty_parameter_set_mark (string):
                        default marker for empty parametersets
  norecursedirs (args): directory patterns to avoid for recursion
  testpaths (args):     directories to search for tests when no files or directories are given in the command line.
  usefixtures (args):   list of default fixtures to be used with this project
  python_files (args):  glob-style file patterns for Python test module discovery
  python_classes (args):
                        prefixes or glob names for Python test class discovery
  python_functions (args):
                        prefixes or glob names for Python test function and method discovery
  disable_test_id_escaping_and_forfeit_all_rights_to_community_support (bool):
                        disable string escape non-ascii characters, might cause unwanted side effects(use at your own risk)
  console_output_style (string):
                        console output: "classic", or with additional progress information ("progress" (percentage) | "count").
  xfail_strict (bool):  default for the strict parameter of xfail markers when not given explicitly (default: False)
  enable_assertion_pass_hook (bool):
                        Enables the pytest_assertion_pass hook.Make sure to delete any previously generated pyc cache files.
  junit_suite_name (string):
                        Test suite name for JUnit report
  junit_logging (string):
                        Write captured log messages to JUnit report: one of no|system-out|system-err
  junit_log_passing_tests (bool):
                        Capture log information for passing tests to JUnit report:
  junit_duration_report (string):
                        Duration time to report: one of total|call
  junit_family (string):
                        Emit XML for schema: one of legacy|xunit1|xunit2
  doctest_optionflags (args):
                        option flags for doctests
  doctest_encoding (string):
                        encoding used for doctest files
  cache_dir (string):   cache directory path.
  filterwarnings (linelist):
                        Each line specifies a pattern for warnings.filterwarnings. Processed after -W and --pythonwarnings.
  log_print (bool):     default value for --no-print-logs
  log_level (string):   default value for --log-level
  log_format (string):  default value for --log-format
  log_date_format (string):
                        default value for --log-date-format
  log_cli (bool):       enable log display during test run (also known as "live logging").
  log_cli_level (string):
                        default value for --log-cli-level
  log_cli_format (string):
                        default value for --log-cli-format
  log_cli_date_format (string):
                        default value for --log-cli-date-format
  log_file (string):    default value for --log-file
  log_file_level (string):
                        default value for --log-file-level
  log_file_format (string):
                        default value for --log-file-format
  log_file_date_format (string):
                        default value for --log-file-date-format
  faulthandler_timeout (string):
                        Dump the traceback of all threads if a test takes more than TIMEOUT seconds to finish. Not available on Windows.
  addopts (args):       extra command line options
  minversion (string):  minimally required pytest version
  rp_log_level (string):
                        Logging level for automated log records reporting
  rp_uuid (string):     UUID
  rp_endpoint (string): Server endpoint
  rp_project (string):  Project name
  rp_launch (string):   Launch name
  rp_launch_tags (args):
                        Launch tags, i.e Performance Regression
  rp_tests_tags (args): Tags for all tests items, e.g. Smoke
  rp_launch_description (string):
                        Launch description
  rp_log_batch_size (string):
                        Size of batch log requests in async mode
  rp_ignore_errors (bool):
                        Ignore Report Portal errors (exit otherwise)
  rp_ignore_tags (args):
                        Ignore specified pytest markers, i.e parametrize
  rp_hierarchy_dirs_level (string):
                        Directory starting hierarchy level
  rp_hierarchy_dirs (bool):
                        Enables hierarchy for directories
  rp_hierarchy_module (bool):
                        Enables hierarchy for module
  rp_hierarchy_class (bool):
                        Enables hierarchy for class
  rp_hierarchy_parametrize (bool):
                        Enables hierarchy for parametrized tests
  rp_issue_marks (args):
                        Pytest marks to get issue information
  rp_issue_system_url (string):
                        URL to get issue description. Issue id from pytest mark will be added to this URL
  rp_verify_ssl (bool): Verify HTTPS calls
  logger_logsdir (string):
                        base directory with log files for file loggers [basetemp]

environment variables:
  PYTEST_ADDOPTS           extra command line options
  PYTEST_PLUGINS           comma-separated plugins to load during startup
  PYTEST_DISABLE_PLUGIN_AUTOLOAD set to disable plugin auto-loading
  PYTEST_DEBUG             set to enable debug tracing of pytest's internals


to see available markers type: pytest --markers
to see available fixtures type: pytest --fixtures
(shown according to specified file_or_dir or current dir if not specified; fixtures with leading '_' are only shown with the '-v' option
```
> 
> The reason I think an approach like this might be better for us is because it matches the actual functionality that pytest parser provides (which i'm pretty sure is argparse under the hood). In addition, being able to add this option multiple times probably makes the changes on the jenkins job side easier as well. Instead of having to inject the custom config file into the value given by the user, we can simply call `--ocsci-conf` again with the value needed for jenkins.
This is not big deal, I will need to iterate over those configs anyway to pass them to run-ci from jenkins.
> 
> Overall, as long as we can utilize one option for passing config overrides it's not a big deal. My main concern is consistency with how other CLI options function and wanting to leverage existing methods that do the work for us instead of implementing our own option parser code.
I wanted also to use arparse instead of writing mine get_param function but you see the reason on the example above and maybe now understand what I meant. Anyway, update the function to take repeatable arguments won't be so hard, so I can update that function like that.

**Comment by dahorak** [comment]
@petr-balogh Wouldn't be possible to use argparse and [disable the help output](https://docs.python.org/3/library/argparse.html#add-help)?
```
parser = argparse.ArgumentParser(add_help=False)
```
(I didn't try it together with the pytest code, so not sure if it can work or not.)

**Comment by clacroix12** [comment]
@dahorak I tested and hit other issues:
```
(venv) ➜  ocs-ci git:(wip-repeatable-config) ✗ run-ci --help
Traceback (most recent call last):
  File "/Users/clacroix/workspace/ocs-ci/venv/bin/run-ci", line 11, in <module>
    load_entry_point('ocs-ci', 'console_scripts', 'run-ci')()
  File "/Users/clacroix/workspace/ocs-ci/ocs_ci/run_ocsci.py", line 8, in main
    exit(runner.main(arguments))
  File "/Users/clacroix/workspace/ocs-ci/ocs_ci/framework/main.py", line 63, in main
    init_ocsci_conf(arguments)
  File "/Users/clacroix/workspace/ocs-ci/ocs_ci/framework/main.py", line 46, in init_ocsci_conf
    for cfg in args.ocsci_conf:
TypeError: 'NoneType' object is not iterable
```

I suspect this is because the `--help` is entirely suppressed and not ignored and passed along to `pytest`

**Comment by dahorak** [comment]
@clacroix12 I think it should work somehow like this: https://github.com/dahorak/ocs-ci/commit/5ac3c66ee641582f661ba76d2b257c9c897e9577
Didn't tested it too deeply though.

**Comment by clacroix12** [comment]
This was completed some time ago.
