### ISSUE TITLE
`tests/manage/mcg/test_bucket_replication.py::TestReplication::test_unidirectional_bucket_replication` fails with Internal Error sometimes

### ISSUE THREAD

**Issue by mashetty330** [red-hat-storage/ocs-ci#7098]
tests/manage/mcg/test_bucket_replication.py::TestReplication::test_unidirectional_bucket_replication sometimes fails with internal error while performing sync directory s3 ops. This issue not seen frequently and at the failure time stamp we could see the below errors in the noobaa endpoint logs.

> core.rpc.rpc_base_conn:: RPC CONNECTION CLOSED. got event from connection: wss://noobaa-mgmt.openshift->storage.svc:8445(56r984kqn) Error: self signed certificate
>    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
>    at TLSSocket.emit (events.js:400:28)
>   at TLSSocket.emit (domain.js:475:12)
>   at TLSSocket._finishInit (_tls_wrap.js:937:8)
>    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
>[32mFeb-3 20:01:33.238[35m [Endpoint/13] [36m   [L0][39m core.rpc.rpc_base_conn:: RPC CONNECTION CLOSED. got >event from connection: wss://noobaa-mgmt.openshift-storage.svc:8445(56r984kqn) WS CLOSED
>[32mFeb-3 20:01:33.238[35m [Endpoint/13] [31m[ERROR][39m core.rpc.rpc:: RPC._request: response ERROR srv >scrubber_api.make_room_in_tier reqid 1@wss://noobaa-mgmt.openshift-storage.svc:8445(56r984kqn) connid wss://noobaa->mgmt.openshift-storage.svc:8445(56r984kqn) params { tier: 63dd6804d233f600295d497a, bucket: >63dd6804d233f600295d497c }  Error: self signed certificate
>   at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
>    at TLSSocket.emit (events.js:400:28)
>   at TLSSocket.emit (domain.js:475:12)
>    at TLSSocket._finishInit (_tls_wrap.js:937:8)
>    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
>[32mFeb-3 20:01:33.238[35m [Endpoint/13] [31m[ERROR][39m core.server.object_services.map_server:: GetMapping: ?>ERROR Error: self signed certificate
>    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
>   at TLSSocket.emit (events.js:400:28)
>    at TLSSocket.emit (domain.js:475:12)
>    at TLSSocket._finishInit (_tls_wrap.js:937:8)
>    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
>[32mFeb-3 20:01:33.239[35m [Endpoint/13] [31m[ERROR][39m CONSOLE:: RPC._on_request: ERROR srv >object_api.get_mapping reqid 2593@fcall://fcall(7pgsev13) connid fcall://fcall(7pgsev13) Error: self signed certificate
>    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
>    at TLSSocket.emit (events.js:400:28)
>    at TLSSocket.emit (domain.js:475:12)
>    at TLSSocket._finishInit (_tls_wrap.js:937:8)
>    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)

So far we could only reproduce this issue once even after multiple attempts. Hence not sure if its a bug or automation issue

RP: 

- https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/426/8820/391713/391767/391768/log

- https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/427/8855/392767/392814/392819/log

**Comment by mashetty330** [comment]
raised bug https://bugzilla.redhat.com/show_bug.cgi?id=2168867
