### ISSUE TITLE
Submariner log collection fails when running RDR MultiCluster job on existing setup

### ISSUE THREAD

**Issue by sidhant-agrawal** [red-hat-storage/ocs-ci#7687]
Submariner log collection fails when running RDR MultiCluster job on an existing RDR setup with following error:

```
2023-05-23 16:41:14  11:11:06 - ThreadPoolExecutor-7_0 - ocs_ci.ocs.utils - INFO - C[sagrawal-hub] - Collecting submariner logs
2023-05-23 16:41:14  11:11:06 - ThreadPoolExecutor-7_0 - ocs_ci.utility.utils - INFO - C[sagrawal-hub] - Executing command: subctl gather --kubeconfig /home/jenkins/clusters/sagrawal-hub/openshift-cluster-dir/auth/kubeconfig
2023-05-23 16:41:14  11:11:06 - MainThread - ocs_ci.ocs.utils - ERROR - C[sagrawal-hub] - Must-gather collection failed
2023-05-23 16:41:14  11:11:06 - MainThread - ocs_ci.ocs.utils - ERROR - C[sagrawal-hub] - [Errno 2] No such file or directory: 'subctl'
2023-05-23 16:41:14  11:11:06 - MainThread - ocs_ci.framework.pytest_customization.ocscilib - ERROR - C[sagrawal-hub] - Failed to collect OCS logs
2023-05-23 16:41:14  Traceback (most recent call last):
2023-05-23 16:41:14    File "/home/jenkins/workspace/qe-rdr-setup/ocs-ci/ocs_ci/framework/pytest_customization/ocscilib.py", line 692, in pytest_runtest_makereport
2023-05-23 16:41:14      collect_ocs_logs(
2023-05-23 16:41:14    File "/home/jenkins/workspace/qe-rdr-setup/ocs-ci/ocs_ci/ocs/utils.py", line 1190, in collect_ocs_logs
2023-05-23 16:41:14      log.info(f.result())
2023-05-23 16:41:14    File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 437, in result
2023-05-23 16:41:14      return self.__get_result()
2023-05-23 16:41:14    File "/usr/lib64/python3.8/concurrent/futures/_base.py", line 389, in __get_result
2023-05-23 16:41:14      raise self._exception
2023-05-23 16:41:14    File "/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
2023-05-23 16:41:14      result = self.fn(*self.args, **self.kwargs)
2023-05-23 16:41:14    File "/home/jenkins/workspace/qe-rdr-setup/ocs-ci/ocs_ci/ocs/utils.py", line 1153, in _collect_ocs_logs
2023-05-23 16:41:14      out = run_cmd(submariner_log_collect)
2023-05-23 16:41:14    File "/home/jenkins/workspace/qe-rdr-setup/ocs-ci/ocs_ci/utility/utils.py", line 479, in run_cmd
2023-05-23 16:41:14      completed_process = exec_cmd(
2023-05-23 16:41:14    File "/home/jenkins/workspace/qe-rdr-setup/ocs-ci/ocs_ci/utility/utils.py", line 628, in exec_cmd
2023-05-23 16:41:14      completed_process = subprocess.run(
2023-05-23 16:41:14    File "/usr/lib64/python3.8/subprocess.py", line 493, in run
2023-05-23 16:41:14      with Popen(*popenargs, **kwargs) as process:
2023-05-23 16:41:14    File "/usr/lib64/python3.8/subprocess.py", line 858, in __init__
2023-05-23 16:41:14      self._execute_child(args, executable, preexec_fn, close_fds,
2023-05-23 16:41:14    File "/usr/lib64/python3.8/subprocess.py", line 1704, in _execute_child
2023-05-23 16:41:14      raise child_exception_type(errno_num, err_msg, err_filename)
2023-05-23 16:41:14  FileNotFoundError: [Errno 2] No such file or directory: 'subctl'
2023-05-23 16:41:14  
2023-05-23 16:41:14  tests/disaster-recovery/regional-dr/test_sequential_failover.py::TestSequentialFailover::test_sequential_failover_to_secondary[primary_down] ERROR---------------------------- live log sessionfinish ----------------------------
```
Job link : https://url.corp.redhat.com/1f7eaa4

**Comment by shylesh** [comment]
TODO: comeup with a fixture for this

**Comment by sidhant-agrawal** [comment]
Fixture added in PR https://github.com/red-hat-storage/ocs-ci/pull/9657
