### ISSUE TITLE
Test test_change_reclaim_policy_of_pv failed

### ISSUE THREAD

**Issue by jilju** [red-hat-storage/ocs-ci#7881]
Failed test cases:
tests/manage/pv_services/test_change_reclaim_policy_of_pv.py::TestChangeReclaimPolicyOfPv::test_change_reclaim_policy_of_pv[CephBlockPool-Delete]
tests/manage/pv_services/test_change_reclaim_policy_of_pv.py::TestChangeReclaimPolicyOfPv::test_change_reclaim_policy_of_pv[CephBlockPool-Retain]

Error:
```
Message: AssertionError: Volume associated with PVC pvc-test-124ba446267f401ebf2a77876362a97 still exists in backend
assert False



where False = verify_volume_deleted_in_backend(interface='CephBlockPool', image_uuid='4e35f980-ad4d-45e9-af36-c4bc18b3a6a5', pool_name='ocs-storagecluster-cephblockpool')
Type: None
```
RUN ID: 1684752447

**Comment by jilju** [comment]
The attempt to find whether the image is deleted failed.
```
2023-05-22 19:21:39,827 - MainThread - INFO - ocs_ci.utility.utils.exec_cmd.619 - Executing command: oc -n openshift-storage rsh rook-ceph-tools-5845b7c568-fbgkr rbd info -p ocs-storagecluster-cephblockpool csi-vol-1b595379-9a8c-484d-a30a-4f72b0dfa842 --format json
2023-05-22 19:31:39,883 - MainThread - ERROR - ocs_ci.utility.utils.__iter__.1201 - Exception raised during iteration: Command '['oc', '--kubeconfig', '/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig', '-n', 'openshift-storage', 'rsh', 'rook-ceph-tools-5845b7c568-fbgkr', 'rbd', 'info', '-p', 'ocs-storagecluster-cephblockpool', 'csi-vol-1b595379-9a8c-484d-a30a-4f72b0dfa842', '--format', 'json']' timed out after 600 seconds
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 1198, in __iter__
    yield self.func(*self.func_args, **self.func_kwargs)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/helpers/helpers.py", line 1853, in is_volume_present_in_backend
    ct_pod.exec_ceph_cmd(ceph_cmd=cmd, format="json")
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/pod.py", line 338, in exec_ceph_cmd
    out = self.exec_cmd_on_pod(ceph_cmd)
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/resources/pod.py", line 190, in exec_cmd_on_pod
    return self.ocp.exec_oc_cmd(
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/ocs/ocp.py", line 170, in exec_oc_cmd
    out = run_cmd(
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 479, in run_cmd
    completed_process = exec_cmd(
  File "/home/jenkins/workspace/qe-deploy-ocs-cluster/ocs-ci/ocs_ci/utility/utils.py", line 628, in exec_cmd
    completed_process = subprocess.run(
  File "/usr/lib64/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib64/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib64/python3.8/subprocess.py", line 1869, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/lib64/python3.8/subprocess.py", line 1072, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['oc', '--kubeconfig', '/home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig', '-n', 'openshift-storage', 'rsh', 'rook-ceph-tools-5845b7c568-fbgkr', 'rbd', 'info', '-p', 'ocs-storagecluster-cephblockpool', 'csi-vol-1b595379-9a8c-484d-a30a-4f72b0dfa842', '--format', 'json']' timed out after 600 seconds
2023-05-22 19:31:39,889 - MainThread - ERROR - ocs_ci.helpers.helpers.verify_volume_deleted_in_backend.1907 - Volume corresponding to uuid 1b595379-9a8c-484d-a30a-4f72b0dfa842 is not deleted in backend
```

**Comment by jilju** [comment]
This is not an automation issue but an issue in manual configuration of the tools pod.
