### ISSUE TITLE
Error on my specific run - Tried to create resource record set [name='api.vasu-ocs-ci.qe.rh-ocs.com.', type='A'] but it already exists]"

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#882]
I am not sure where the issue is, but this is affecting creating fresh cluster

```
       release image registry.svc.ci.openshift.org/ocp/release@sha256:5243c2499e6857fc3d99ba47f6361a2a7d0bfd937b4ca1f4910077d8b46d337f
14:41:58 - MainThread - ocs_ci.deployment.ocp - INFO - Destroying the cluster
14:41:58 - MainThread - ocs_ci.deployment.ocp - INFO - Destroying cluster defined in /Users/vasukulkarni/cluster-path/
14:41:58 - MainThread - ocs_ci.utility.utils - INFO - Executing command: /Users/vasukulkarni/ocs-ci/bin/openshift-install destroy cluster --dir /Users/vasukulkarni/cluster-path/ --log-level INFO
14:44:39 - MainThread - ocs_ci.utility.utils - WARNING - Command warning: level=info msg=Disassociated instance=i-09fed4d5729b5a3af name=vasu-ocs-ci-8mqdd-master-profile role=vasu-ocs-ci-8mqdd-master-role
                                                         level=info msg=Deleted InstanceProfileName=vasu-ocs-ci-8mqdd-master-profile arn="arn:aws:iam::861790564636:instance-profile/vasu-ocs-ci-8mqdd-master-profile" instance=i-09fed4d5729b5a3af
                                                         level=info msg=Terminating instance=i-09fed4d5729b5a3af
                                                         level=info msg=Terminating instance=i-06cf1046d68a18e18
                                                         level=info msg=Terminating instance=i-0395ff63d3ac42e06
                                                         level=info msg=Disassociated instance=i-07ea21814ed9b478e name=vasu-ocs-ci-8mqdd-bootstrap-profile role=vasu-ocs-ci-8mqdd-bootstrap-role
                                                         level=info msg=Deleted InstanceProfileName=vasu-ocs-ci-8mqdd-bootstrap-profile arn="arn:aws:iam::861790564636:instance-profile/vasu-ocs-ci-8mqdd-bootstrap-profile" instance=i-07ea21814ed9b478e
                                                         level=info msg=Terminating instance=i-07ea21814ed9b478e
                                                         level=info msg=Disassociated arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-090306981b7cdb7c9" id=rtbassoc-038c554a1aeba04e1
                                                         level=info msg=Disassociated arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-090306981b7cdb7c9" id=rtbassoc-005bb3ca203663362
                                                         level=info msg=Disassociated arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-090306981b7cdb7c9" id=rtbassoc-0837b50c2cdbcc066
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:natgateway/nat-098f127846a2d5751" id=nat-098f127846a2d5751
                                                         level=info msg=Disassociated arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-09e1784b7a82fc8bb" id=rtbassoc-07a1955548424cd56
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-09e1784b7a82fc8bb" id=rtb-09e1784b7a82fc8bb
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:natgateway/nat-0ebdffabbc665cbbc" id=nat-0ebdffabbc665cbbc
                                                         level=info msg=Deleted arn="arn:aws:elasticloadbalancing:us-east-2:861790564636:loadbalancer/net/vasu-ocs-ci-8mqdd-int/33ab56d01fa56034" id=net/vasu-ocs-ci-8mqdd-int/33ab56d01fa56034
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:natgateway/nat-08ac32afe6b566c71" id=nat-08ac32afe6b566c71
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 load balancer=loadbalancer/net/vasu-ocs-ci-8mqdd-ext/5a456656e9f6bd4f
                                                         level=info msg=Deleted NAT gateway=nat-08ac32afe6b566c71 arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6
                                                         level=info msg=Deleted NAT gateway=nat-0ebdffabbc665cbbc arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6
                                                         level=info msg=Deleted NAT gateway=nat-098f127846a2d5751 arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:image/ami-061a7a53ca2830f83" id=ami-061a7a53ca2830f83
                                                         level=info msg=Disassociated arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-0fac0bf444cbe9a0b" id=rtbassoc-0ce3e029c5a30c490
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-0fac0bf444cbe9a0b" id=rtb-0fac0bf444cbe9a0b
                                                         level=info msg=Disassociated arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-0a0b7e2f0b69f5164" id=rtbassoc-0142df862b452ef9f
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:route-table/rtb-0a0b7e2f0b69f5164" id=rtb-0a0b7e2f0b69f5164
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:security-group/sg-0cd11279562bbf90e" id=sg-0cd11279562bbf90e
                                                         level=info msg=Deleted arn="arn:aws:s3:::terraform-20191009213420022600000001"
                                                         level=info msg=Deleted arn="arn:aws:iam::861790564636:role/vasu-ocs-ci-8mqdd-bootstrap-role" id=vasu-ocs-ci-8mqdd-bootstrap-role name=vasu-ocs-ci-8mqdd-bootstrap-role policy=vasu-ocs-ci-8mqdd-bootstrap-policy
                                                         level=info msg=Deleted arn="arn:aws:iam::861790564636:role/vasu-ocs-ci-8mqdd-bootstrap-role" id=vasu-ocs-ci-8mqdd-bootstrap-role name=vasu-ocs-ci-8mqdd-bootstrap-role
                                                         level=info msg=Deleted arn="arn:aws:iam::861790564636:role/vasu-ocs-ci-8mqdd-master-role" id=vasu-ocs-ci-8mqdd-master-role name=vasu-ocs-ci-8mqdd-master-role policy=vasu-ocs-ci-8mqdd-master-policy
                                                         level=info msg=Deleted arn="arn:aws:iam::861790564636:role/vasu-ocs-ci-8mqdd-master-role" id=vasu-ocs-ci-8mqdd-master-role name=vasu-ocs-ci-8mqdd-master-role
                                                         level=info msg=Deleted arn="arn:aws:iam::861790564636:role/vasu-ocs-ci-8mqdd-worker-role" id=vasu-ocs-ci-8mqdd-worker-role name=vasu-ocs-ci-8mqdd-worker-role policy=vasu-ocs-ci-8mqdd-worker-policy
                                                         level=info msg=Disassociated arn="arn:aws:iam::861790564636:role/vasu-ocs-ci-8mqdd-worker-role" id=vasu-ocs-ci-8mqdd-worker-role name=vasu-ocs-ci-8mqdd-worker-profile role=vasu-ocs-ci-8mqdd-worker-role
                                                         level=info msg=Deleted InstanceProfileName=vasu-ocs-ci-8mqdd-worker-profile arn="arn:aws:iam::861790564636:instance-profile/vasu-ocs-ci-8mqdd-worker-profile" id=vasu-ocs-ci-8mqdd-worker-role name=vasu-ocs-ci-8mqdd-worker-role
                                                         level=info msg=Deleted arn="arn:aws:iam::861790564636:role/vasu-ocs-ci-8mqdd-worker-role" id=vasu-ocs-ci-8mqdd-worker-role name=vasu-ocs-ci-8mqdd-worker-role
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:subnet/subnet-0e07b4c5267e4409d" id=subnet-0e07b4c5267e4409d
                                                         level=info msg=Deleted arn="arn:aws:elasticloadbalancing:us-east-2:861790564636:targetgroup/vasu-ocs-ci-8mqdd-aint/a79b00312e41487b" id=vasu-ocs-ci-8mqdd-aint/a79b00312e41487b
                                                         level=info msg=Released arn="arn:aws:ec2:us-east-2:861790564636:elastic-ip/eipalloc-0b3dc0d9f0a39e1b5" id=eipalloc-0b3dc0d9f0a39e1b5
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:snapshot/snap-0811ccbb6043cdd22" id=snap-0811ccbb6043cdd22
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:internet-gateway/igw-0ccd3915a7778fcbf" id=igw-0ccd3915a7778fcbf
                                                         level=info msg=Released arn="arn:aws:ec2:us-east-2:861790564636:elastic-ip/eipalloc-0163bd6c2b84ab6b3" id=eipalloc-0163bd6c2b84ab6b3
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:subnet/subnet-038792fa25dfbde25" id=subnet-038792fa25dfbde25
                                                         level=info msg=Deleted arn="arn:aws:elasticloadbalancing:us-east-2:861790564636:targetgroup/vasu-ocs-ci-8mqdd-aext/ce89d089abc64caa" id=vasu-ocs-ci-8mqdd-aext/ce89d089abc64caa
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:subnet/subnet-053388df5f58281ab" id=subnet-053388df5f58281ab
                                                         level=info msg=Deleted arn="arn:aws:elasticloadbalancing:us-east-2:861790564636:targetgroup/vasu-ocs-ci-8mqdd-sint/d6d186301018e9c1" id=vasu-ocs-ci-8mqdd-sint/d6d186301018e9c1
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:security-group/sg-05aaf077cbb3854b9" id=sg-05aaf077cbb3854b9
                                                         level=info msg=Deleted NAT gateway=nat-08ac32afe6b566c71 arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6
                                                         level=info msg=Deleted NAT gateway=nat-0ebdffabbc665cbbc arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6
                                                         level=info msg=Deleted NAT gateway=nat-098f127846a2d5751 arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 network interface=eni-049d3974b398b2403
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 network interface=eni-094dacba6bdec1a7f
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 network interface=eni-0c9c69962322b009f
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 table=rtb-0c565d8e561873899
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 security group=sg-0ed6e9128bd434847
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 subnet=subnet-004b2355d0540d4d6
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 subnet=subnet-07d3a1c720248a52b
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6 subnet=subnet-0e4eacfb859c983be
                                                         level=info msg=Deleted VPC endpoint=vpce-0d810997a85d7b725 arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:vpc/vpc-0d86cda496750dba6" id=vpc-0d86cda496750dba6
                                                         level=info msg=Released arn="arn:aws:ec2:us-east-2:861790564636:elastic-ip/eipalloc-08671637287dbb0e5" id=eipalloc-08671637287dbb0e5
                                                         level=info msg=Deleted arn="arn:aws:ec2:us-east-2:861790564636:dhcp-options/dopt-05318681756ef872e" id=dopt-05318681756ef872e
14:44:39 - MainThread - ocs_ci.deployment.aws - ERROR - Traceback (most recent call last):
                                                          File "/Users/vasukulkarni/ocs-ci/ocs_ci/deployment/aws.py", line 110, in destroy_volumes
                                                            cluster_name = get_cluster_name(self.cluster_path)
                                                          File "/Users/vasukulkarni/ocs-ci/ocs_ci/deployment/aws.py", line 399, in get_cluster_name
                                                            with open(metadata_file) as f:
                                                        FileNotFoundError: [Errno 2] No such file or directory: '/Users/vasukulkarni/cluster-path/metadata.json'


================================================================================================= ERRORS =================================================================================================
___________________________________________________________________________________ ERROR at setup of test_deployment ____________________________________________________________________________________
```

**Comment by vasukulkarni** [comment]
Error I am hitting during recreation, if anyone sees similar issue

```
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: /Users/vasukulkarni/ocs-ci/bin/openshift-install create cluster --dir /Users/vasukulkarni/cluster-path/ --log-level INFO.
E           Error is level=info msg="Consuming \"Install Config\" from target directory"
E           level=info msg="Creating infrastructure resources..."
E           level=error
E           level=error msg="Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='api.vasu-ocs-ci.qe.rh-ocs.com.', type='A'] but it already exists]"
E           level=error msg="\tstatus code: 400, request id: 542d8ae7-fde0-462a-a78f-7fbf64d20131"
E           level=error
E           level=error msg="  on ../../../private/var/folders/nt/g_hzgqps1q52bc1wbfy3sl_c0000gn/T/openshift-install-629464842/route53/base.tf line 23, in resource \"aws_route53_record\" \"api_external\":"
E           level=error msg="  23: resource \"aws_route53_record\" \"api_external\" {"
E           level=error
E           level=error
E           level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```

**Comment by vasukulkarni** [comment]
Coady pointed out this is same as https://github.com/red-hat-storage/ocs-ci/issues/844

**Comment by clacroix12** [comment]
> Coady pointed out this is same as #844

To clarify, the error regarding the metadata.json file in the description is the same as #844. The issue regarding the route53 record set existing is different.

**Comment by gklein** [comment]
It can be tricky, but In case we see this error too often, we can consider enabling the [allow_overwrite](https://www.terraform.io/docs/providers/aws/r/route53_record.html#allow_overwrite) argument for  the AWS terraform provider.  If we do so, it will allow us to overwrite existing route53 DNS records and prevent similar failures.

**Comment by vasukulkarni** [comment]
Closing as I think this was under qe domain.
