### ISSUE TITLE
ERROR: openshift 0.10.0 has requirement kubernetes~=10.0, but you'll have kubernetes 9.0.0 which is incompatible.

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#935]
There seems to be some mishmash between required versions of kubernetes and openshift. Requirement installation (`pip3 install -r requirements.txt`) prints following error (even  though finish with error code `0`):
```
ERROR: openshift 0.10.0 has requirement kubernetes~=10.0, but you'll have kubernetes 9.0.0 which is incompatible.
```
And then `run-ci ...` command fails like [this](https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-destroy-ocs-cluster/1232/console):
```
+ run-ci tests/ecosystem/ -m deployment '--ocsci-conf=~/current-cluster-dir/ocsci_conf.yaml' --ocsci-conf=conf/ocsci/production-aws-ipi.yaml --cluster-name jenkins-pr920 --cluster-path /home/jenkins/current-cluster-dir/openshift-cluster-dir --junit-xml /home/jenkins/current-cluster-dir/logs/destroy_results.xml -o junit_suite_name=jenkins-pr920 --html=/home/jenkins/current-cluster-dir/logs/destroy_report.html --self-contained-html --teardown
Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (kubernetes 9.0.0 (/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages), Requirement.parse('kubernetes~=10.0'), {'openshift'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/bin/run-ci", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (kubernetes 9.0.0 (/home/jenkins/workspace/qe-destroy-ocs-cluster/ocs-ci/.venv/lib/python3.6/site-packages), Requirement.parse('kubernetes~=10.0'), {'openshift'})
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }

[Pipeline] // dir
[Pipeline] }
ERROR: script returned exit code 1
```

**Comment by dahorak** [comment]
The problem is caused by new version of `openshift` package (`0.10.0`) [released yesterday](https://pypi.org/project/openshift/#history)

**Comment by vavuthu** [comment]
is there any particular reason why we want o stick to 'kubernetes==9.0.0', If not we can go 10.0.0

**Comment by petr-balogh** [comment]
I do not remember why we stick with that version, we can bring this on todays automation mtg, but for now I would test the new version is OK for us and then I would remove the requirements to specific version WDYT? @dahorak did you do some testing with new version already? If not, can you please submit PR to remove this version requirement to go with install the latest and run tier1 test verification?

**Comment by dahorak** [comment]
First installation failed on some other reason, will try to relaunch it once more time (trying it with following patch: https://github.com/dahorak/ocs-ci/commit/b20bcaf8fe59f22e3f1a3a1fd87544d84ffa6479).
