### ISSUE TITLE
Raise clear error message when OCP deployment via Flexy fails

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#9377]
```
            cluster_config = config
>       mirror_registry = cluster_config.DEPLOYMENT["mirror_registry"]
E       KeyError: 'mirror_registry'

ocs_ci/utility/utils.py:3515: KeyError
```

Failed job:
https://url.corp.redhat.com/4420035

**Comment by dahorak** [comment]
The root cause of this failure is the failed flexy execution (failed OCP deployment via Flexy):

```
2024-02-26 11:40:16  10:40:14 - MainThread - ocs_ci.deployment.flexy - INFO  - error: unable to open source layer sha256:73e166e20e3dabaa1afab1f18c8e997935e480072137499564d1f2f9b056ef3f to copy to ec2-3-145-95-159.us-east-2.compute.amazonaws.com:5000/ocp/release: Get "https://quay.io/v2/openshift-release-dev/ocp-v4.0-art-dev/blobs/sha256:73e166e20e3dabaa1afab1f18c8e997935e480072137499564d1f2f9b056ef3f": received unexpected HTTP status: 502 Bad Gateway
2024-02-26 11:40:16  10:40:14 - MainThread - ocs_ci.deployment.flexy - INFO  - error: unable to open source layer sha256:d0baea4dd4ebe4d953b2bdc9f6d518e1f2e845b8c165e99f62a19efcc7d13b5b to copy to ec2-3-145-95-159.us-east-2.compute.amazonaws.com:5000/ocp/release: received unexpected HTTP status: 502 Bad Gateway
2024-02-26 11:40:16  10:40:14 - MainThread - ocs_ci.deployment.flexy - INFO  - error: unable to open source layer sha256:c5925ec764012a3164d0cb46b2ec97bc799bfe3b7da3124a38a7a88f459c9d7c to copy to ec2-3-145-95-159.us-east-2.compute.amazonaws.com:5000/ocp/release: received unexpected HTTP status: 502 Bad Gateway
2024-02-26 11:40:16  10:40:14 - MainThread - ocs_ci.deployment.flexy - INFO  - error: unable to copy layer sha256:648fb81684e6f546959500fabcfe1688a204edf8a014661630d632335f460e64 to ec2-3-145-95-159.us-east-2.compute.amazonaws.com:5000/ocp/release: Patch "https://ec2-3-145-95-159.us-east-2.compute.amazonaws.com:5000/v2/ocp/release/blobs/uploads/799374ce-ae32-402c-893d-3aafb917a3a6?_state=ZxSfLEDDH-7yewA-1fVtMT1v7N2zJTXA3rzHKfhKfwd7Ik5hbWUiOiJvY3AvcmVsZWFzZSIsIlVVSUQiOiI3OTkzNzRjZS1hZTMyLTQwMmMtODkzZC0zYWFmYjkxN2EzYTYiLCJPZmZzZXQiOjAsIlN0YXJ0ZWRBdCI6IjIwMjQtMDItMjZUMDc6MDY6MDEuMDMyNzQ5OTE3WiJ9": stream error: stream ID 43; INTERNAL_ERROR; received from peer
2024-02-26 11:40:16  10:40:14 - MainThread - ocs_ci.deployment.flexy - INFO  - error: unable to open source layer sha256:49fce910319df92504d878bf5a61a65e585cb48e31b6f41b159e8d4ff89dcbc0 to copy to ec2-3-145-95-159.us-east-2.compute.amazonaws.com:5000/ocp/release: Get "https://quay.io/v2/openshift-release-dev/ocp-v4.0-art-dev/blobs/sha256:49fce910319df92504d878bf5a61a65e585cb48e31b6f41b159e8d4ff89dcbc0": Get "https://quay.io/v2/auth?account=ocsqe&scope=repository%3Aopenshift-release-dev%2Focp-v4.0-art-dev%3Apull&service=quay.io": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2024-02-26 11:40:16  10:40:14 - MainThread - ocs_ci.deployment.flexy - INFO  - error: unable to open source layer sha256:4fbaccd220b499c4f4570adae4724950542434835712ab1e4ae4db47429def0e to copy to ec2-3-145-95-159.us-east-2.compute.amazonaws.com:5000/ocp/release: Get "https://quay.io/v2/openshift-release-dev/ocp-v4.0-art-dev/blobs/sha256:4fbaccd220b499c4f4570adae4724950542434835712ab1e4ae4db47429def0e": received unexpected HTTP status: 502 Bad Gateway
2024-02-26 11:40:16  10:40:14 - MainThread - ocs_ci.deployment.flexy - INFO  - info: Mirroring completed in 3h43m20.16s (1.316MB/s)
2024-02-26 11:40:16  10:40:14 - MainThread - ocs_ci.deployment.flexy - INFO  - error: one or more errors occurred while uploading images
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - tools/launch_instance.rb:624:in `installation_task': shell command failed execution, see logs (RuntimeError)
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from tools/launch_instance.rb:763:in `block in launch_template'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from tools/launch_instance.rb:762:in `each'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from tools/launch_instance.rb:762:in `launch_template'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from tools/launch_instance.rb:55:in `block (2 levels) in run'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from /home/jenkins/.gem/ruby/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from /home/jenkins/.gem/ruby/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from /home/jenkins/.gem/ruby/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from /home/jenkins/.gem/ruby/gems/commander-4.6.0/lib/commander/runner.rb:58:in `run!'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from /home/jenkins/.gem/ruby/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from tools/launch_instance.rb:92:in `run'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - from tools/launch_instance.rb:904:in `<main>'
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - waiting for operation up to 36000 seconds..
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - 
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - [10:40:15] INFO> Exit Status: 2
2024-02-26 11:40:16  10:40:15 - MainThread - ocs_ci.deployment.flexy - INFO  - deleting /mnt/flexy/workdir/awscreds20240226-386-qct4v
2024-02-26 11:40:16  10:40:16 - MainThread - ocs_ci.deployment.flexy - ERROR  - Flexy command failed
2024-02-26 11:40:16  10:40:16 - MainThread - ocs_ci.deployment.flexy - ERROR  - Command '['podman', 'run', '--rm=true', '--env-file=/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/data/flexy-dir/ocs-flexy-env-file-updated.env', '-w=/mnt', '--mount=type=bind,source=/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/data/flexy-dir,destination=/mnt,relabel=shared', 'images.paas.redhat.com/dno-ood/ocp4:latest']' returned non-zero exit status 1.
```

I'll review the code and try to make it more clear in case of such failure, but AFAIR, we are initially ignoring the Flexy return code, because there were cases, when it existed with non-zero exit status but the cluster was actually correctly deployed.
