### ISSUE TITLE
ocs-build --image --ocs-version 4.16 failing on TagNotFoundException: Couldn't find any desired tag

### ISSUE THREAD

**Issue by dahorak** [red-hat-storage/ocs-ci#9815]
There seems to be some issue with obtaining latest image for 4.16, because the `ocs-build` command is failing with following traceback:
```
2024-05-17 18:50:09  + ocs-build --image --ocs-version 4.16
2024-05-17 18:50:31  Traceback (most recent call last):
2024-05-17 18:50:31    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/venv/bin/ocs-build", line 33, in <module>
2024-05-17 18:50:31      sys.exit(load_entry_point('ocs-ci', 'console_scripts', 'ocs-build')())
2024-05-17 18:50:31    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/ocs_build.py", line 55, in main
2024-05-17 18:50:31      latest_ocs_build = get_latest_ds_olm_tag()
2024-05-17 18:50:31    File "/home/jenkins/workspace/qe-deploy-ocs-cluster-prod/ocs-ci/ocs_ci/utility/utils.py", line 2650, in get_latest_ds_olm_tag
2024-05-17 18:50:31      raise TagNotFoundException("Couldn't find any desired tag!")
2024-05-17 18:50:31  ocs_ci.ocs.exceptions.TagNotFoundException: Couldn't find any desired tag!
```

All  recent production jobs failed because of this issue.

**Comment by dahorak** [comment]
Looks like the root cause here is that the image with `latest-stable-4.16` tag doesn't have assigned any "version" specific tag (like `4.16.0-xxx`). Opened chat in virtual-teams room about that, will update here once I'll have more info about that.

**Comment by dahorak** [comment]
The tags were fixed.

```
$ ocs-build --image --ocs-version 4.16
quay.io/rhceph-dev/ocs-registry:4.16.0-102
```
